/**
 * GEBCO bathymetry client.
 *
 * The browser talks only to the existing Flask endpoint:
 *
 *   /api/gebco/depth
 *
 * The Flask backend talks to the ODB GEBCO API.
 *
 * We intentionally do NOT call OpenTopoData from the browser because
 * that was the source of the individual quota error.
 */

export interface GebcoTransectPoint {
  distance_m: number;
  lat: number;
  lng: number;
  elevation: number;
  depth_m: number;
  depth_ft: number;
  slope_deg: number;
}

export interface GebcoGridCell {
  lat: number;
  lng: number;
  elevation: number;
  depth_m: number;
}

export interface GebcoGridData {
  rows: number;
  cols: number;
  span_km: number;
  matrix: GebcoGridCell[][];
}

export interface GebcoProvenance {
  source_name: string;
  source_type: 'live' | 'synthetic_fallback';
  is_live: boolean;
  is_synthetic: boolean;
  warning?: string | null;
}

export interface GebcoDepthResponse {
  status: 'success' | 'error';
  api_connected: boolean;
  dataset: string;
  source: string;
  resolution: string;
  provenance: GebcoProvenance;
  coordinates: {
    lat: number;
    lng: number;
  };
  bathymetry: {
    depth_m: number;
    depth_ft: number;
    elevation_m: number;
    is_underwater: boolean;
    average_transect_depth_m: number;
    min_depth_m: number;
    max_depth_m: number;
    seabed_gradient_deg: number;
  };
  oceanography: {
    zone: string;
    zone_description: string;
    estimated_water_temp_c: number;
    sound_speed_mps: number;
    sound_speed_fps: number;
    hydrostatic_pressure_bar: number;
    hydrostatic_pressure_psi: number;
    light_penetration_pct: number;
    diver_classification: string;
  };
  transect: GebcoTransectPoint[];
  grid: GebcoGridData;
  queried_at: string;
}

function generateFallbackBathymetry(
  lat: number,
  lng: number,
  spanKm = 1.2,
  samples = 21,
  fallbackReason?: string,
): GebcoDepthResponse {
  const lngDepth = (72.85 - lng) * 120.0;

  const latUndulation =
    Math.sin(lat * 8.0) * 4.5 +
    Math.cos(lng * 12.0) * 3.2;

  const centerDepth = Math.max(
    14.0,
    Math.min(
      320.0,
      24.0 + lngDepth + latUndulation,
    ),
  );

  const transect: GebcoTransectPoint[] = [];

  for (let i = 0; i < samples; i++) {
    const fraction =
      i / Math.max(1, samples - 1) - 0.5;

    const distM =
      fraction * spanKm * 1000;

    const slopeVariance =
      Math.sin(fraction * Math.PI * 2) * 3.8 +
      Math.cos(fraction * 3) * 1.5;

    const ptDepth = Math.max(
      10.0,
      centerDepth +
      fraction * 18.0 +
      slopeVariance,
    );

    transect.push({
      distance_m: Math.round(distM),
      lat: +lat.toFixed(5),
      lng: +(
        lng +
        fraction * 0.015
      ).toFixed(5),
      elevation:
        -Math.round(ptDepth * 10) / 10,
      depth_m:
        Math.round(ptDepth * 10) / 10,
      depth_ft:
        Math.round(
          ptDepth * 3.28084 * 10,
        ) / 10,
      slope_deg: +(
        Math.atan2(
          fraction * 18.0 +
          slopeVariance,
          Math.max(
            1,
            Math.abs(distM),
          ),
        ) *
        (180 / Math.PI)
      ).toFixed(1),
    });
  }

  const gridMatrix: GebcoGridCell[][] = [];

  for (let r = 0; r < 5; r++) {
    const row: GebcoGridCell[] = [];
    const rFrac = r / 4 - 0.5;

    for (let c = 0; c < 5; c++) {
      const cFrac = c / 4 - 0.5;

      const gDepth = Math.max(
        8.0,
        centerDepth +
        cFrac * 16.0 +
        rFrac * 8.0 +
        Math.sin(r * 2 + c) * 2.2,
      );

      row.push({
        lat: +(
          lat +
          rFrac * 0.01
        ).toFixed(5),
        lng: +(
          lng +
          cFrac * 0.01
        ).toFixed(5),
        elevation:
          -Math.round(gDepth * 10) / 10,
        depth_m:
          Math.round(gDepth * 10) / 10,
      });
    }

    gridMatrix.push(row);
  }

  const tempC = Math.max(
    4.0,
    +(
      24.0 -
      centerDepth * 0.08
    ).toFixed(1),
  );

  const soundSpeed = +(
    1449.2 +
    4.6 * tempC -
    0.055 * (tempC ** 2) +
    0.016 * centerDepth
  ).toFixed(1);

  const pressureBar = +(
    1.013 +
    centerDepth * 0.1005
  ).toFixed(2);

  const lightPct = Math.max(
    0.1,
    +(
      100.0 *
      Math.exp(
        -0.045 * centerDepth,
      )
    ).toFixed(1),
  );

  return {
    status: 'success',
    api_connected: false,
    dataset: 'OCEONIX_SYNTHETIC_FALLBACK',
    source:
      'OCEONIX local synthetic bathymetry fallback',
    resolution:
      'Synthetic model — not a GEBCO measurement',
    provenance: {
      source_name:
        'OCEONIX local synthetic bathymetry fallback',
      source_type: 'synthetic_fallback',
      is_live: false,
      is_synthetic: true,
      warning:
        fallbackReason ??
        'Live GEBCO data was unavailable. Bathymetry shown here is generated by the local synthetic fallback model and must not be treated as GEBCO data.',
    },
    coordinates: {
      lat: +lat.toFixed(5),
      lng: +lng.toFixed(5),
    },
    bathymetry: {
      depth_m:
        Math.round(
          centerDepth * 10,
        ) / 10,
      depth_ft:
        Math.round(
          centerDepth *
          3.28084 *
          10,
        ) / 10,
      elevation_m:
        -Math.round(
          centerDepth * 10,
        ) / 10,
      is_underwater: true,
      average_transect_depth_m: +(
        transect.reduce(
          (s, p) =>
            s + p.depth_m,
          0,
        ) /
        transect.length
      ).toFixed(1),
      min_depth_m: Math.min(
        ...transect.map(
          (p) => p.depth_m,
        ),
      ),
      max_depth_m: Math.max(
        ...transect.map(
          (p) => p.depth_m,
        ),
      ),
      seabed_gradient_deg:
        transect[
          Math.floor(
            transect.length / 2,
          )
        ]?.slope_deg ?? 1.2,
    },
    oceanography: {
      zone:
        centerDepth <= 200
          ? 'Epipelagic (Sunlight Zone)'
          : centerDepth <= 1000
            ? 'Mesopelagic (Twilight Zone)'
            : 'Bathypelagic (Midnight Zone)',
      zone_description:
        centerDepth <= 200
          ? 'Ample solar penetration; high acoustic stability; optimal for sonar & ROV operations.'
          : 'Faint ambient light; significant thermocline layer; ROV tether required.',
      estimated_water_temp_c:
        tempC,
      sound_speed_mps:
        soundSpeed,
      sound_speed_fps:
        +(
          soundSpeed * 3.28084
        ).toFixed(1),
      hydrostatic_pressure_bar:
        pressureBar,
      hydrostatic_pressure_psi:
        +(
          pressureBar * 14.5038
        ).toFixed(1),
      light_penetration_pct:
        lightPct,
      diver_classification:
        centerDepth <= 18
          ? 'Open Water Diver'
          : centerDepth <= 40
            ? 'Advanced / Nitrox'
            : centerDepth <= 100
              ? 'Technical Trimix'
              : 'Commercial ROV Only',
    },
    transect,
    grid: {
      rows: 5,
      cols: 5,
      span_km: spanKm,
      matrix: gridMatrix,
    },
    queried_at:
      new Date().toISOString(),
  };
}

export async function fetchGebcoDepth(
  lat: number,
  lng: number,
  opts: {
    spanKm?: number;
    samples?: number;
    signal?: AbortSignal;
  } = {},
): Promise<GebcoDepthResponse> {
  const spanKm =
    opts.spanKm ?? 1.2;

  const samples =
    opts.samples ?? 21;

  try {
    const url =
      `/api/gebco/depth?` +
      `lat=${encodeURIComponent(
        lat,
      )}` +
      `&lng=${encodeURIComponent(
        lng,
      )}` +
      `&span_km=${encodeURIComponent(
        spanKm,
      )}` +
      `&samples=${encodeURIComponent(
        samples,
      )}`;

    const response =
      await fetch(
        url,
        {
          signal:
            opts.signal,
        },
      );

    if (!response.ok) {
      throw new Error(
        `GEBCO backend returned ${response.status}`,
      );
    }

    const data =
      await response.json();

    if (
      data &&
      data.status ===
      'success' &&
      data.bathymetry
    ) {
      return data as
        GebcoDepthResponse;
    }

    throw new Error(
      data?.error ??
      'Invalid GEBCO response',
    );

  } catch (error) {
    if (
      error instanceof
      DOMException &&
      error.name ===
      'AbortError'
    ) {
      throw error;
    }

    return generateFallbackBathymetry(
      lat,
      lng,
      spanKm,
      samples,
      error instanceof Error
        ? error.message
        : 'The GEBCO backend could not be reached.',
    );
  }
}