export const xEn: Record<string, string> = {
  'adm.sub': 'Assign tasks to departments and operators across the OCEONIX command chain. Route every open case to the right unit and member.',
  'adm.openTasks': 'Open tasks',
  'adm.unassigned': 'Unassigned',
  'adm.inProgress': 'In progress',
  'adm.ktPriorityAction': 'priority action',
  'adm.assignFlow': 'Assign task → department → member',
  'adm.liveLedger': 'Live ledger',
  'adm.selectOpenTask': 'Select an open task…',
  'adm.memberOpt': 'Member…',
  'adm.assignTask': 'Assign task',
  'adm.noMembers': '{dept} has no members yet — register operators or seed the roster.',
  'adm.membersAvail': '{n} members available in {dept}.',
  'adm.ktCommandChain': 'command chain',
  'adm.assignmentLedger': 'Assignment ledger',
  'adm.noCasesTitle': 'No cases',
  'adm.noCasesDesc': 'No alerts match this view.',
  'adm.ktRoster': 'roster',
  'adm.deptsAndMembers': 'Departments & members',
  'adm.deptLoad': '{a} assigned · {u} open',
  'adm.noMembersShort': 'No members',
  'adm.registered': '{n} registered accounts joined to the platform roster.',
  'adm.opp': 'opp',
  'adm.routed': 'routed',
};

export const xHi: Record<string, string> = {
  'adm.sub': 'ओसेनिक्स कमांड श्रृंखला में विभागों और ऑपरेटरों को कार्य सौंपें। हर खुले मामले को सही इकाई और सदस्य के पास पहुँचाएँ।',
  'adm.openTasks': 'खुले कार्य',
  'adm.unassigned': 'अनियुक्त',
  'adm.inProgress': 'प्रगति में',
  'adm.ktPriorityAction': 'प्राथमिकता कार्रवाई',
  'adm.assignFlow': 'कार्य → विभाग → सदस्य नियुक्त करें',
  'adm.liveLedger': 'लाइव लेजर',
  'adm.selectOpenTask': 'एक खुला कार्य चुनें…',
  'adm.memberOpt': 'सदस्य…',
  'adm.assignTask': 'कार्य नियुक्त करें',
  'adm.noMembers': '{dept} में अभी कोई सदस्य नहीं है — ऑपरेटर पंजीकृत करें या रोस्टर भरें।',
  'adm.membersAvail': '{dept} में {n} सदस्य उपलब्ध हैं।',
  'adm.ktCommandChain': 'कमांड श्रृंखला',
  'adm.assignmentLedger': 'नियुक्ति लेजर',
  'adm.noCasesTitle': 'कोई मामला नहीं',
  'adm.noCasesDesc': 'इस व्यू से कोई अलर्ट मेल नहीं खाता।',
  'adm.ktRoster': 'रोस्टर',
  'adm.deptsAndMembers': 'विभाग और सदस्य',
  'adm.deptLoad': '{a} नियुक्त · {u} खुले',
  'adm.noMembersShort': 'कोई सदस्य नहीं',
  'adm.registered': '{n} पंजीकृत खाते प्लेटफ़ॉर्म रोस्टर से जुड़े हैं।',
  'adm.opp': 'ऑप',
  'adm.routed': 'रूटेड',
};

export const xMr: Record<string, string> = {
  'adm.sub': 'ओसेनिक्स कमांड साखळीतील विभाग आणि ऑपरेटरांना कार्ये नेमा. प्रत्येक खुल्या प्रकरणाला योग्य तुकडी आणि सदस्याकडे न्या.',
  'adm.openTasks': 'खुली कार्ये',
  'adm.unassigned': 'अनियुक्त',
  'adm.inProgress': 'प्रगतीपथावर',
  'adm.ktPriorityAction': 'प्राधान्य कृती',
  'adm.assignFlow': 'कार्य → विभाग → सदस्य नेमा',
  'adm.liveLedger': 'लाइव्ह नोंदवही',
  'adm.selectOpenTask': 'खुले कार्य निवडा…',
  'adm.memberOpt': 'सदस्य…',
  'adm.assignTask': 'कार्य नेमा',
  'adm.noMembers': '{dept} मध्ये अद्याप कोणीही सदस्य नाही — ऑपरेटर नोंदणी करा किंवा रोस्टर भरा.',
  'adm.membersAvail': '{dept} मध्ये {n} सदस्य उपलब्ध आहेत.',
  'adm.ktCommandChain': 'कमांड साखळी',
  'adm.assignmentLedger': 'नियुक्ती नोंदवही',
  'adm.noCasesTitle': 'कोणतेही प्रकरण नाही',
  'adm.noCasesDesc': 'या व्यूशी कोणताही अलर्ट जुळत नाही.',
  'adm.ktRoster': 'रोस्टर',
  'adm.deptsAndMembers': 'विभाग व सदस्य',
  'adm.deptLoad': '{a} नेमले · {u} खुले',
  'adm.noMembersShort': 'सदस्य नाहीत',
  'adm.registered': '{n} नोंदणीकृत खाती प्लॅटफॉर्म रोस्टरमध्ये सामील झाली आहेत.',
  'adm.opp': 'ऑप',
  'adm.routed': 'रूट केले',
};