export const xEn: Record<string, string> = {
  'al.sub': 'Routing engine → department inbox → operator assignment → verification. Every alert carries its full lifecycle.',
  'al.myDept': 'My department',
  'al.ktRouting': 'routing engine',
  'al.routingRules': 'Routing rules in force',
  'al.auto': 'AUTO',
  'al.thObjectClass': 'Object class',
  'al.thRiskBase': 'Risk base',
  'al.thPrimaryDept': 'Primary dept',
  'al.escalation': 'Escalation',
  'al.thFields': 'Fields',
  'al.filtVerification': 'Verification',
  'al.deptAll': 'All departments',
  'al.deptMine': 'My department only',
  'al.searchPlaceholder': 'Search alert / detection…',
  'al.thAlert': 'Alert',
  'al.thObject': 'Object',
  'al.thDept': 'Dept',
  'al.operator': 'Operator',
  'al.thDetected': 'Detected',
  'al.done': 'done',
  'al.empty': 'No alerts match the current filters.',
  'al.shown': '{n} alert(s) shown',
  'al.escHint': 'ESC/CLICK OUTSIDE TO CLOSE DETAIL',
  'al.ktDetail': 'alert detail',
  'al.confTag': 'CONF {pct}%',
  'al.recTag': '→ {dept}',
  'al.lifecycle': 'Lifecycle',
  'al.safetyTag': 'Safety',
  'al.assignedDept': 'Assigned dept',
  'al.unassigned': 'unassigned',
  'al.responseActions': 'Response actions',
  'al.toastUpdated': 'Alert updated',
  'al.ackAccept': 'Acknowledge & accept',
  'al.toastAck': 'Case acknowledged',
  'al.assignOp': 'Assign operator…',
  'al.assign': 'Assign',
  'al.assignedTo': 'Assigned {operator}',
  'al.btnProgress': 'Progress',
  'al.toastProgress': 'In progress',
  'al.btnVerify': 'Verify',
  'al.toastVerify': 'Verification requested',
  'al.btnResolve': 'Resolve',
  'al.toastResolved': 'Marked resolved',
  'al.toastResVerified': 'Resolution verified',
  'al.openCase': 'Open full case',
};

export const xHi: Record<string, string> = {
  'al.sub': 'रूटिंग इंजन → विभाग इनबॉक्स → ऑपरेटर असाइनमेंट → सत्यापन। हर अलर्ट अपने पूरे जीवनचक्र के साथ आता है।',
  'al.myDept': 'मेरा विभाग',
  'al.ktRouting': 'रूटिंग इंजन',
  'al.routingRules': 'लागू रूटिंग नियम',
  'al.auto': 'ऑटो',
  'al.thObjectClass': 'वस्तु वर्ग',
  'al.thRiskBase': 'आधार जोखिम',
  'al.thPrimaryDept': 'प्राथमिक विभाग',
  'al.escalation': 'एस्केलेशन',
  'al.thFields': 'फ़ील्ड',
  'al.filtVerification': 'सत्यापन',
  'al.deptAll': 'सभी विभाग',
  'al.deptMine': 'केवल मेरा विभाग',
  'al.searchPlaceholder': 'अलर्ट / डिटेक्शन खोजें…',
  'al.thAlert': 'अलर्ट',
  'al.thObject': 'वस्तु',
  'al.thDept': 'विभाग',
  'al.operator': 'ऑपरेटर',
  'al.thDetected': 'पहचाना गया',
  'al.done': 'पूर्ण',
  'al.empty': 'वर्तमान फ़िल्टर से कोई अलर्ट मेल नहीं खाता।',
  'al.shown': '{n} अलर्ट दिखाए गए',
  'al.escHint': 'विवरण बंद करने के लिए ESC/बाहर क्लिक करें',
  'al.ktDetail': 'अलर्ट विवरण',
  'al.confTag': 'CONF {pct}%',
  'al.recTag': '→ {dept}',
  'al.lifecycle': 'जीवनचक्र',
  'al.safetyTag': 'सुरक्षा',
  'al.assignedDept': 'नियुक्त विभाग',
  'al.unassigned': 'अनियुक्त',
  'al.responseActions': 'प्रतिक्रिया कार्रवाइयाँ',
  'al.toastUpdated': 'अलर्ट अपडेट किया गया',
  'al.ackAccept': 'स्वीकार करें और लें',
  'al.toastAck': 'मामला स्वीकार किया गया',
  'al.assignOp': 'ऑपरेटर नियुक्त करें…',
  'al.assign': 'नियुक्त करें',
  'al.assignedTo': '{operator} को नियुक्त किया गया',
  'al.btnProgress': 'प्रगति',
  'al.toastProgress': 'प्रगति में',
  'al.btnVerify': 'सत्यापित करें',
  'al.toastVerify': 'सत्यापन का अनुरोध किया गया',
  'al.btnResolve': 'हल करें',
  'al.toastResolved': 'हल के रूप में चिह्नित',
  'al.toastResVerified': 'समाधान सत्यापित किया गया',
  'al.openCase': 'पूरा मामला खोलें',
};

export const xMr: Record<string, string> = {
  'al.sub': 'रूटिंग इंजिन → विभाग इनबॉक्स → ऑपरेटर नियुक्ती → पडताळणी. प्रत्येक अलर्ट आपल्या संपूर्ण जीवनचक्रासह येतो.',
  'al.myDept': 'माझा विभाग',
  'al.ktRouting': 'रूटिंग इंजिन',
  'al.routingRules': 'लागू असलेले रूटिंग नियम',
  'al.auto': 'ऑटो',
  'al.thObjectClass': 'वस्तू वर्ग',
  'al.thRiskBase': 'आधार जोखीम',
  'al.thPrimaryDept': 'प्राथमिक विभाग',
  'al.escalation': 'एस्केलेशन',
  'al.thFields': 'फील्ड',
  'al.filtVerification': 'पडताळणी',
  'al.deptAll': 'सर्व विभाग',
  'al.deptMine': 'फक्त माझा विभाग',
  'al.searchPlaceholder': 'अलर्ट / डिटेक्शन शोधा…',
  'al.thAlert': 'अलर्ट',
  'al.thObject': 'वस्तू',
  'al.thDept': 'विभाग',
  'al.operator': 'ऑपरेटर',
  'al.thDetected': 'ओळखले',
  'al.done': 'पूर्ण',
  'al.empty': 'सध्याच्या फिल्टरशी कोणताही अलर्ट जुळत नाही.',
  'al.shown': '{n} अलर्ट दाखवले',
  'al.escHint': 'तपशील बंद करण्यासाठी ESC/बाहेर क्लिक करा',
  'al.ktDetail': 'अलर्ट तपशील',
  'al.confTag': 'CONF {pct}%',
  'al.recTag': '→ {dept}',
  'al.lifecycle': 'जीवनचक्र',
  'al.safetyTag': 'सुरक्षा',
  'al.assignedDept': 'नियुक्त विभाग',
  'al.unassigned': 'न नेमलेले',
  'al.responseActions': 'प्रतिसाद कृती',
  'al.toastUpdated': 'अलर्ट अपडेट केला',
  'al.ackAccept': 'मान्य करा आणि स्वीकारा',
  'al.toastAck': 'केस स्वीकारला',
  'al.assignOp': 'ऑपरेटर नेमा…',
  'al.assign': 'नेमा',
  'al.assignedTo': '{operator} यांना नेमले',
  'al.btnProgress': 'प्रगती',
  'al.toastProgress': 'प्रगतीपथावर',
  'al.btnVerify': 'पडताळा',
  'al.toastVerify': 'पडताळणीची विनंती केली',
  'al.btnResolve': 'निकाली करा',
  'al.toastResolved': 'निकाली म्हणून चिन्हांकित',
  'al.toastResVerified': 'उत्तर सत्यापित केले',
  'al.openCase': 'पूर्ण केस उघडा',
};