export const xEn: Record<string, string> = {
  'anx.head': "Analytics & performance",
  'anx.sub': "Trends, risk posture, workload and response performance computed live from the simulation ledger.",
  'anx.generate': "Generate report",
  'anx.ktWindow': "12-week window",
  'anx.detections': "Detections",
  'anx.ktOutcome': "outcome",
  'anx.cases': "CASES",
  'anx.ktObject': "by object",
  'anx.total': "TOTAL",
  'anx.ktSeverity': "severity",
  'anx.ktModel': "model output",
  'anx.confUnder': "<{v}",
  'anx.confRange': "{a}-{b}",
  'anx.confOver': "{v}+",
  'anx.resolved': "Resolved",
  'anx.open': "Open",
  'anx.ktGrid': "by survey grid",
  'anx.ktDepartment': "by department",
  'anx.hours': "{v}h",
  'anx.avgNote': "Average hours detection→resolution for closed cases.",
  'anx.ktLoad': "open load",
  'anx.ktLogistics': "logistics",
};

export const xHi: Record<string, string> = {
  'anx.head': "विश्लेषण एवं प्रदर्शन",
  'anx.sub': "रुझान, जोखिम स्थिति, कार्यभार और प्रतिक्रिया प्रदर्शन — सिमुलेशन लेजर से लाइव गणना।",
  'anx.generate': "रिपोर्ट बनाएँ",
  'anx.ktWindow': "12-सप्ताह की अवधि",
  'anx.detections': "डिटेक्शन",
  'anx.ktOutcome': "परिणाम",
  'anx.cases': "मामले",
  'anx.ktObject': "वस्तु के अनुसार",
  'anx.total': "कुल",
  'anx.ktSeverity': "गंभीरता",
  'anx.ktModel': "मॉडल आउटपुट",
  'anx.confUnder': "{v} से कम",
  'anx.confRange': "{a}-{b}",
  'anx.confOver': "{v} से अधिक",
  'anx.resolved': "हल किए गए",
  'anx.open': "खुले",
  'anx.ktGrid': "सर्वेक्षण ग्रिड के अनुसार",
  'anx.ktDepartment': "विभाग के अनुसार",
  'anx.hours': "{v} घंटे",
  'anx.avgNote': "बंद मामलों के लिए डिटेक्शन से समाधान तक औसत घंटे।",
  'anx.ktLoad': "खुला कार्यभार",
  'anx.ktLogistics': "लॉजिस्टिक्स",
};

export const xMr: Record<string, string> = {
  'anx.head': "विश्लेषण आणि कामगिरी",
  'anx.sub': "कल, जोखीम स्थिती, कार्यभार आणि प्रतिसाद कामगिरी — सिम्युलेशन लेजरवरून थेट मोजलेले.",
  'anx.generate': "अहवाल तयार करा",
  'anx.ktWindow': "12-आठवड्यांची अवधी",
  'anx.detections': "डिटेक्शन",
  'anx.ktOutcome': "परिणाम",
  'anx.cases': "प्रकरणे",
  'anx.ktObject': "वस्तूनुसार",
  'anx.total': "एकूण",
  'anx.ktSeverity': "तीव्रता",
  'anx.ktModel': "मॉडेल आउटपुट",
  'anx.confUnder': "{v} पेक्षा कमी",
  'anx.confRange': "{a}-{b}",
  'anx.confOver': "{v} पेक्षा जास्त",
  'anx.resolved': "निकाली काढलेले",
  'anx.open': "खुले",
  'anx.ktGrid': "सर्वेक्षण ग्रिडनुसार",
  'anx.ktDepartment': "विभागानुसार",
  'anx.hours': "{v} तास",
  'anx.avgNote': "बंद प्रकरणांसाठी डिटेक्शन ते समाधान या सरासरी तास.",
  'anx.ktLoad': "खुला कार्यभार",
  'anx.ktLogistics': "लॉजिस्टिक्स",
};