export const xHi: Record<string, string> = {
  'al.accept': 'मामला स्वीकारें',
  'al.assign': 'ऑपरेटर निर्धारित करें',
  'al.equipment': 'उपकरण का अनुरोध करें',
  'al.escalate': 'एस्केलेट करें',
  'al.manual': 'मैन्युअल रूप से निर्धारित',
  'al.newalert': 'नया अलर्ट',
  'al.note': 'टिप्पणी जोड़ें',
  'al.progress': 'प्रगति में मार्क करें',
  'al.reqver': 'सत्यापन आवश्यक',
  'al.resolve': 'हल किया हुआ मार्क करें',
  'al.responses': 'प्रतिक्रिया क्रियाएँ',
  'al.routed': 'एआई द्वारा रूट किया गया',
  'al.rule': 'नियम-आधारित निर्धारण',
  'al.verify': 'सत्यापन का अनुरोध करें',
  'al.verifyres': 'समाधान सत्यापित करें',
  'an.confidence': 'विश्वास स्तर मूल्यांकन',
  'an.impact': 'पर्यावरणीय प्रभाव',
  'an.marine': 'समुद्री खुफिया विश्लेषण',
  'an.priority': 'प्राथमिकता मूल्यांकन',
  'an.response': 'अनुशंसित प्रतिक्रिया',
  'an.summary': 'डिटेक्शन सारांश',
  'an.verification': 'सत्यापन आवश्यकता',
  'anx.activity': 'डिटेक्शन गतिविधि',
  'anx.conf': 'विश्वास स्तर वितरण',
  'anx.deptload': 'विभाग कार्यभार',
  'anx.equip': 'उपकरण आवश्यकताएँ',
  'anx.geo': 'भौगोलिक सांद्रता',
  'anx.object': 'वस्तु वितरण',
  'anx.resp': 'प्रतिक्रिया-समय प्रदर्शन',
  'anx.rvp': 'हल किए गए बनाम लंबित',
  'app.sub': 'एआई-संचालित समुद्री कचरा व विसंगति डिटेक्शन',
  'app.title': 'OCEONIX — पानी के भीतर की खुफिया जानकारी',
  'batch.cancel': 'रद्द करें',
  'batch.done': 'प्रोसेसिंग पूर्ण',
  'batch.empty': 'कोई छवि कतार में नहीं। सोनार फ्रेम डालकर शुरू करें।',
  'batch.export': 'परिणाम निर्यात करें',
  'batch.pause': 'रोकें',
  'batch.results': 'परिणाम देखें',
  'batch.resume': 'फिर से शुरू करें',
  'batch.retry': 'विफल पुनः प्रयास करें',
  'batch.start': 'स्कैन शुरू करें',
  'batch.title': 'बैच सोनार स्कैन',
  'batch.upload': 'सोनार छवियाँ या फ़ोल्डर अपलोड करें',
  'cat.anomaly': 'विसंगति',
  'cat.debris': 'समुद्री कचरा',
  'cat.infrastructure': 'अवसंरचना',
  'cat.marine-life': 'समुद्री जीवन',
  'cat.safety': 'सुरक्षा / आपातकाल',
  'common.all': 'सभी',
  'common.apply': 'लागू करें',
  'common.close': 'बंद करें',
  'common.completed': 'पूर्ण',
  'common.failed': 'विफल',
  'common.live': 'लाइव',
  'common.loading': 'लोड हो रहा है',
  'common.logout': 'लॉग आउट',
  'common.none': 'कोई नहीं',
  'common.notifications': 'सूचनाएँ',
  'common.open': 'खोलें',
  'common.paused': 'रोका गया',
  'common.processing': 'प्रोसेसिंग',
  'common.queued': 'कतार में',
  'common.refresh': 'रीफ़्रेश करें',
  'common.reset': 'रीसेट करें',
  'common.saved': 'सेटिंग्स सहेजी गईं',
  'common.see': 'देखें',
  'dash.activity': 'डिटेक्शन गतिविधि',
  'dash.cathist': 'कचरा / विसंगति श्रेणियाँ',
  'dash.command': 'संचालन कमांड',
  'dash.last24': 'पिछले 24 घंटे',
  'dash.respstat': 'प्रतिक्रिया स्थिति',
  'dash.updated': 'अपडेट किया गया',
  'dash.wk': 'इस सप्ताह',
  'dept.busy': 'व्यस्त',
  'dept.id': 'विभाग आईडी',
  'dept.offline': 'ऑफ़लाइन',
  'dept.online': 'ऑनलाइन',
  'dept.operator': 'सक्रिय ऑपरेटर',
  'dept.standby': 'स्टैंडबाय',
  'det.inspect': 'निरीक्षण करें',
  'det.noobjects': 'इस फ्रेम में कोई वस्तु डिटेक्ट नहीं हुई',
  'det.or': 'या',
  'det.simulate': 'नमूना सोनार फ्रेम उपयोग करें',
  'det.stage1': 'सोनार फ्रेम लोड हो रहा है',
  'det.stage2': 'ध्वनिक छवि बढ़ाई जा रही है',
  'det.stage3': 'डिटेक्शन मॉडल चल रहा है',
  'det.stage4': 'वस्तुओं का विश्लेषण हो रहा है',
  'det.stage5': 'मूल्यांकन तैयार हो रहा है',
  'det.uploadedAs': 'अपलोड किया गया',
  'his.export': 'सीएसवी निर्यात करें',
  'his.total': 'रिकॉर्ड',
  'live.alerts': 'सक्रिय अलर्ट',
  'live.cpu': 'एआई कोर',
  'live.depth': 'स्कैन गहराई',
  'live.gps': 'जीपीएस फ़िक्स',
  'live.health': 'सिस्टम स्वास्थ्य',
  'live.interval': 'स्कैन अंतराल',
  'live.mem': 'मेमोरी',
  'live.objects': 'डिटेक्ट की गई वस्तुएँ',
  'live.resume': 'फिर से शुरू करें',
  'live.sensitivity': 'डिटेक्शन संवेदनशीलता',
  'live.signal': 'सिग्नल शक्ति',
  'live.sonar': 'सोनार ऐरे',
  'live.threshold': 'अलर्ट सीमा',
  'login.create': 'पंजीकरण',
  'login.email': 'ईमेल पता',
  'login.failed': 'अमान्य क्रेडेंशियल। कृपया पुनः प्रयास करें।',
  'login.name': 'पूरा नाम',
  'login.operator': 'ऑपरेटर',
  'login.registerHint': 'अपनी भूमिका से मेल खाने वाला विभाग चुनें। सिस्टम प्रशासक खाते को कार्य निर्धारण विशेषाधिकार मिलते हैं।',
  'login.roleof': 'भूमिका',
  'login.signin': 'साइन इन',
  'login.signupSub': 'पोर्टल तक पहुँचने के लिए ऑपरेटर खाता बनाएँ',
  'login.success': 'सफलतापूर्वक प्रमाणित किया गया',
  'map.filters': 'फ़िल्टर',
  'map.markers': 'डिटेक्शन',
  'map.satellite': 'सैटेलाइट',
  'map.search': 'निर्देशांक या आईडी खोजें',
  'map.sonar': 'सोनार',
  'map.title': 'महासागर नक्शा',
  'map.topographic': 'चार्ट',
  'map.view': 'चार्ट दृश्य',
  'map.zoomto': 'डिटेक्शन पर ज़ूम करें',
  'ml.note': 'समुद्री जीवन — केवल निगरानी, कचरा-हटाने का अलर्ट नहीं।',
  'nav.admin': 'एडमिन कंसोल',
  'nav.config': 'कॉन्फ़िगरेशन',
  'nav.deptanalytics': 'विभाग एनालिटिक्स',
  'nav.equipment': 'उपकरण',
  'nav.groups': 'सिस्टम',
  'nav.intelligence': 'डिटेक्शन',
  'nav.myalerts': 'मेरे अलर्ट',
  'nav.mycases': 'मेरे मामले',
  'nav.response': 'प्रतिक्रिया कतार',
  'nav.response_nav': 'प्रतिक्रिया',
  'nav.routing': 'रूटिंग कॉन्फ़िग',
  'nav.users': 'ऑपरेटर',
  'ob.complete.desc': 'आप OCEONIX संचालित करने के लिए तैयार हैं।',
  'ob.complete.title': 'सिस्टम टूर पूर्ण',
  'ob.dashboard': 'डैशबोर्ड लॉन्च करें',
  'ob.detect': 'डिटेक्शन एक्सप्लोर करें',
  'ob.mydept': 'मेरा विभाग खोलें',
  'ob.step.alerts': 'अलर्ट',
  'ob.step.alerts.desc': 'डिटेक्ट की गई वस्तुएँ जोखिम और रूटिंग नियमों के आधार पर अलर्ट बनती हैं, पूर्ण लाइफसाइकिल ट्रैकिंग के साथ।',
  'ob.step.analytics': 'एनालिटिक्स',
  'ob.step.analytics.desc': 'डिटेक्शन प्रवृत्तियाँ, जोखिम वितरण, विभाग कार्यभार, भौगोलिक सांद्रता और प्रतिक्रिया प्रदर्शन।',
  'ob.step.batch': 'बैच स्कैन',
  'ob.step.batch.desc': 'प्रगति ट्रैकिंग के साथ बैच स्कैनिंग इंटरफ़ेस के माध्यम से कई सोनार फ्रेम प्रोसेस करें।',
  'ob.step.detection': 'एआई डिटेक्शन',
  'ob.step.detection.desc': 'साइड-स्कैन सोनार इमेजरी अपलोड करें और प्रति-वस्तु साक्ष्य के साथ सिम्युलेटेड एआई डिटेक्शन परिणामों की समीक्षा करें।',
  'ob.step.history': 'डिटेक्शन इतिहास',
  'ob.step.history.desc': 'पिछली डिटेक्शन और बंद मामलों को खोजें, फ़िल्टर करें और समीक्षा करें।',
  'ob.step.live': 'लाइव मॉनिटर',
  'ob.step.live.desc': 'रियल-टाइम शैली की सोनार निगरानी — संवेदनशीलता, स्कैन गहराई, सिग्नल शक्ति और सक्रिय अलर्ट।',
  'ob.step.map': 'महासागर नक्शा',
  'ob.step.map.desc': 'जीपीएस-टैग किए गए मामलों के साथ डिटेक्शन भौगोलिक रूप से दृश्यमान, जिनका आप निरीक्षण कर सकते हैं।',
  'ob.step.mydept': 'मेरा विभाग',
  'ob.step.mydept.desc': 'निर्धारित अलर्ट देखें, मामले स्वीकारें, ऑपरेटर निर्धारित करें, सत्यापन का अनुरोध करें और स्थिति अपडेट करें।',
  'ob.step.overview': 'अवलोकन डैशबोर्ड',
  'ob.step.overview.desc': 'सिस्टम-व्यापी डिटेक्शन आँकड़े, सक्रिय अलर्ट, जोखिम वितरण, प्रतिक्रिया प्रदर्शन और निगरानी क्षेत्र।',
  'ob.step.reports': 'रिपोर्ट',
  'ob.step.reports.desc': 'योजना और समीक्षा के लिए सिम्युलेटेड परिचालन रिपोर्ट बनाएँ।',
  'ob.step.routing': 'विभाग रूटिंग',
  'ob.step.routing.desc': 'OCEONIX कॉन्फ़िगर किए गए वस्तु और जोखिम नियमों का उपयोग करके प्रत्येक अलर्ट को जिम्मेदार विभाग तक रूट करता है।',
  'ob.step.settings': 'सेटिंग्स',
  'ob.step.settings.desc': 'डिटेक्शन सीमाएँ, रूटिंग नियम, समय सीमाएँ, उपकरण, सूचनाएँ और डेमो मोड कॉन्फ़िगर करें।',
  'ob.welcome.desc': 'पानी के भीतर की समुद्री विसंगतियों को डिटेक्ट, विश्लेषित, रूट और प्रबंधित करने के लिए आपका परिचालन इंटरफ़ेस।',
  'ob.welcome.sub': 'पानी के भीतर की खुफिया जानकारी और प्रतिक्रिया मंच',
  'ob.welcome.title': 'OCEONIX में आपका स्वागत है',
  'rep.csv': 'सीएसवी निर्यात करें',
  'rep.date': 'दिनांक सीमा',
  'rep.pdf': 'पीडीएफ डाउनलोड करें',
  'rep.preview': 'पूर्वावलोकन',
  'rep.print': 'प्रिंट करें',
  'rep.running': 'रिपोर्ट संकलित हो रही है',
  'set.anim': 'एनीमेशन स्तर',
  'set.beam': 'बीम चौड़ाई',
  'set.classes': 'कचरा श्रेणियाँ',
  'set.confidence': 'डिटेक्शन विश्वास स्तर सीमा',
  'set.critonly': 'केवल गंभीर',
  'set.demomode': 'डेमो मोड',
  'set.deptalerts': 'विभाग अलर्ट',
  'set.deptrules': 'विभाग नियम',
  'set.email': 'ईमेल अलर्ट',
  'set.equiprules': 'उपकरण नियम',
  'set.freq': 'फ़्रीक्वेंसी',
  'set.gain': 'गेन',
  'set.notify': 'सूचना प्राथमिकताएँ',
  'set.push': 'पुश सूचनाएँ',
  'set.range': 'रेंज',
  'set.response': 'अलर्ट प्रतिक्रिया समय',
  'set.risk': 'जोखिम सीमाएँ',
  'set.sonar': 'सोनार कैलिब्रेशन',
  'set.sound': 'ध्वनि अलर्ट',
  'set.systemalerts': 'सिस्टम अलर्ट',
  'set.tour': 'प्रोडक्ट टूर फिर से चलाएँ',
  'set.tourbtn': 'टूर शुरू करें',
  'set.tvg': 'टीवीजी',
  'sfy.category': 'सुरक्षा / आपातकाल',
  'sfy.reply': 'खोज व बचाव प्राथमिकता के रूप में लें। तटीय सेवाओं के साथ समन्वय करें।',
  'st.acknowledged': 'स्वीकार किया गया',
  'st.assigned': 'निर्धारित',
  'st.closed': 'बंद',
  'st.escalated': 'एस्केलेट किया गया',
  'st.in_progress': 'प्रगति में',
  'st.manual_verification': 'सत्यापन आवश्यक',
  'st.new': 'नया',
  'st.open': 'खुला',
  'st.overdue': 'अतिदेय',
  'st.pending': 'लंबित',
  'st.resolved': 'हल किया गया',
  'st.unacknowledged': 'अस्वीकृत',
  'st.verification': 'सत्यापन आवश्यक',
  'st.verified': 'सत्यापित',
  'sys.ok': 'सिस्टम सामान्य',
  'sys.version': 'v2.4.1',
  'tok.login': 'सत्र सक्रिय',
  'time.justNow': 'अभी-अभी',
  'time.minAgo': '{m} मिनट पहले',
  'time.hrAgo': '{h} घंटे पहले',
  'time.dayAgo': '{d} दिन पहले',
};