export const xMr: Record<string, string> = {
  'al.accept': 'प्रकरण स्वीकारा',
  'al.assign': 'ऑपरेटर नियुक्त करा',
  'al.equipment': 'उपकरणाची विनंती करा',
  'al.escalate': 'एस्केलेट करा',
  'al.manual': 'स्वतः नियुक्त केलेले',
  'al.newalert': 'नवीन अलर्ट',
  'al.note': 'टीप जोडा',
  'al.progress': 'प्रगतीपथावर चिन्हांकित करा',
  'al.reqver': 'पडताळणी आवश्यक',
  'al.resolve': 'निकाली चिन्हांकित करा',
  'al.responses': 'प्रतिसाद कृती',
  'al.routed': 'एआयद्वारे राउटेड',
  'al.rule': 'नियम-आधारित नियुक्ती',
  'al.verify': 'पडताळणीची विनंती करा',
  'al.verifyres': 'निकालाची पडताळणी करा',
  'an.confidence': 'आत्मविश्वास मूल्यांकन',
  'an.impact': 'पर्यावरणीय परिणाम',
  'an.marine': 'सागरी गुप्तचर विश्लेषण',
  'an.priority': 'प्राधान्य मूल्यांकन',
  'an.response': 'शिफारस केलेला प्रतिसाद',
  'an.summary': 'डिटेक्शन सारांश',
  'an.verification': 'पडताळणी आवश्यकता',
  'anx.activity': 'डिटेक्शन क्रियाकलाप',
  'anx.conf': 'आत्मविश्वास वितरण',
  'anx.deptload': 'विभागाचे कामाचे ओझे',
  'anx.equip': 'उपकरण आवश्यकता',
  'anx.geo': 'भौगोलिक एकाग्रता',
  'anx.object': 'वस्तू वितरण',
  'anx.resp': 'प्रतिसाद-काल कार्यक्षमता',
  'anx.rvp': 'निकाली काढलेले विरुद्ध प्रलंबित',
  'app.sub': 'एआय-आधारित सागरी कचरा व विसंगती डिटेक्शन',
  'app.title': 'OCEONIX — पाण्याखालील गुप्तहेरखबरी',
  'batch.cancel': 'रद्द करा',
  'batch.done': 'प्रक्रिया पूर्ण',
  'batch.empty': 'कोणत्याही प्रतिमा रांगेत नाहीत. सुरुवात करण्यासाठी सोनार फ्रेम टाका.',
  'batch.export': 'परिणाम निर्यात करा',
  'batch.pause': 'थांबवा',
  'batch.results': 'परिणाम पहा',
  'batch.resume': 'पुन्हा सुरू करा',
  'batch.retry': 'अयशस्वी पुन्हा करा',
  'batch.start': 'स्कॅन सुरू करा',
  'batch.title': 'बॅच सोनार स्कॅन',
  'batch.upload': 'सोनार प्रतिमा किंवा फोल्डर अपलोड करा',
  'cat.anomaly': 'विसंगती',
  'cat.debris': 'सागरी कचरा',
  'cat.infrastructure': 'पायाभूत सुविधा',
  'cat.marine-life': 'सागरी जीवन',
  'cat.safety': 'सुरक्षा / आपत्कालीन',
  'common.all': 'सर्व',
  'common.apply': 'लागू करा',
  'common.close': 'बंद करा',
  'common.completed': 'पूर्ण झाले',
  'common.failed': 'अयशस्वी',
  'common.live': 'लाइव्ह',
  'common.loading': 'लोड होत आहे',
  'common.logout': 'लॉगआउट',
  'common.none': 'काहीही नाही',
  'common.notifications': 'सूचना',
  'common.open': 'उघडा',
  'common.paused': 'थांबवलेले',
  'common.processing': 'प्रक्रिया चालू आहे',
  'common.queued': 'रांगेत असलेले',
  'common.refresh': 'रीफ्रेश करा',
  'common.reset': 'रीसेट करा',
  'common.saved': 'सेटिंग्ज जतन झाल्या',
  'common.see': 'पहा',
  'dash.activity': 'डिटेक्शन क्रियाकलाप',
  'dash.cathist': 'कचरा / विसंगती श्रेणी',
  'dash.command': 'संचालन कमांड',
  'dash.last24': 'गेल्या २४ तासांत',
  'dash.respstat': 'प्रतिसाद स्थिती',
  'dash.updated': 'अद्यतनित',
  'dash.wk': 'या आठवड्यात',
  'dept.busy': 'व्यस्त',
  'dept.id': 'विभाग आयडी',
  'dept.offline': 'ऑफलाइन',
  'dept.online': 'ऑनलाइन',
  'dept.operator': 'सक्रिय ऑपरेटर',
  'dept.standby': 'स्टँडबाय',
  'det.inspect': 'तपासा',
  'det.noobjects': 'या फ्रेममध्ये कोणतीही वस्तू आढळली नाही',
  'det.or': 'किंवा',
  'det.simulate': 'नमुना सोनार फ्रेम वापरा',
  'det.stage1': 'सोनार फ्रेम लोड होत आहे',
  'det.stage2': 'ध्वनिक प्रतिमा वाढवत आहे',
  'det.stage3': 'डिटेक्शन मॉडेल चालवत आहे',
  'det.stage4': 'वस्तूंचे विश्लेषण करत आहे',
  'det.stage5': 'मूल्यांकन तयार करत आहे',
  'det.uploadedAs': 'अपलोड केलेले',
  'his.export': 'CSV निर्यात करा',
  'his.total': 'नोंदी',
  'live.alerts': 'सक्रिय अलर्ट',
  'live.cpu': 'एआय कोर',
  'live.depth': 'स्कॅन खोली',
  'live.gps': 'जीपीएस फिक्स',
  'live.health': 'सिस्टम आरोग्य',
  'live.interval': 'स्कॅन अंतराल',
  'live.mem': 'मेमरी',
  'live.objects': 'आढळलेल्या वस्तू',
  'live.resume': 'पुन्हा सुरू करा',
  'live.sensitivity': 'डिटेक्शन संवेदनशीलता',
  'live.signal': 'सिग्नल तीव्रता',
  'live.sonar': 'सोनार अॅरे',
  'live.threshold': 'अलर्ट उंबरठा',
  'login.create': 'नोंदणी करा',
  'login.email': 'ईमेल पत्ता',
  'login.failed': 'अवैध क्रेडेन्शियल. कृपया पुन्हा प्रयत्न करा.',
  'login.name': 'पूर्ण नाव',
  'login.operator': 'ऑपरेटर',
  'login.registerHint': 'तुमच्या भूमिकेशी जुळणारा विभाग निवडा. सिस्टम प्रशासक खात्याला कार्य नियुक्तीचे विशेषाधिकार मिळतात.',
  'login.roleof': 'भूमिका',
  'login.signin': 'साइन इन',
  'login.signupSub': 'पोर्टलमध्ये प्रवेश करण्यासाठी ऑपरेटर खाते तयार करा',
  'login.success': 'यशस्वीरित्या प्रमाणीकरण झाले',
  'map.filters': 'फिल्टर',
  'map.markers': 'डिटेक्शन्स',
  'map.satellite': 'उपग्रह',
  'map.search': 'निर्देशांक किंवा आयडी शोधा',
  'map.sonar': 'सोनार',
  'map.title': 'महासागर नकाशा',
  'map.topographic': 'चार्ट',
  'map.view': 'चार्ट दृश्य',
  'map.zoomto': 'डिटेक्शनवर झूम करा',
  'ml.note': 'सागरी जीवन — केवळ निरीक्षण, कचरा-काढण्याचा अलर्ट नाही.',
  'nav.admin': 'प्रशासक कन्सोल',
  'nav.config': 'कॉन्फिगरेशन',
  'nav.deptanalytics': 'विभाग विश्लेषण',
  'nav.equipment': 'उपकरणे',
  'nav.groups': 'सिस्टम',
  'nav.intelligence': 'डिटेक्शन',
  'nav.myalerts': 'माझे अलर्ट',
  'nav.mycases': 'माझी प्रकरणे',
  'nav.response': 'प्रतिसाद रांग',
  'nav.response_nav': 'प्रतिसाद',
  'nav.routing': 'राउटिंग कॉन्फिग',
  'nav.users': 'ऑपरेटर',
  'ob.complete.desc': 'तुम्ही Oceanix चालवण्यासाठी सज्ज आहात.',
  'ob.complete.title': 'सिस्टम टूर पूर्ण',
  'ob.dashboard': 'डॅशबोर्ड सुरू करा',
  'ob.detect': 'डिटेक्शन एक्सप्लोर करा',
  'ob.mydept': 'माझा विभाग उघडा',
  'ob.step.alerts': 'अलर्ट',
  'ob.step.alerts.desc': 'आढळलेल्या वस्तू जोखीम व राउटिंग नियमांनुसार अलर्ट बनतात, संपूर्ण जीवनचक्र ट्रॅकिंगसह.',
  'ob.step.analytics': 'विश्लेषण',
  'ob.step.analytics.desc': 'डिटेक्शन कल, जोखीम वितरण, विभागाचे कामाचे ओझे, भौगोलिक एकाग्रता आणि प्रतिसाद कार्यक्षमता.',
  'ob.step.batch': 'बॅच स्कॅन',
  'ob.step.batch.desc': 'प्रगती ट्रॅकिंगसह बॅच स्कॅनिंग इंटरफेसमधून अनेक सोनार फ्रेमवर प्रक्रिया करा.',
  'ob.step.detection': 'एआय डिटेक्शन',
  'ob.step.detection.desc': 'साइड-स्कॅन सोनार प्रतिमा अपलोड करा आणि प्रत्येक वस्तूच्या पुराव्यासह सिम्युलेटेड एआय डिटेक्शन परिणामांचे पुनरावलोकन करा.',
  'ob.step.history': 'डिटेक्शन इतिहास',
  'ob.step.history.desc': 'मागील डिटेक्शन्स आणि बंद प्रकरणे शोधा, फिल्टर करा आणि पुनरावलोकन करा.',
  'ob.step.live': 'लाइव्ह मॉनिटर',
  'ob.step.live.desc': 'रिअल-टाइम शैलीतील सोनार निरीक्षण — संवेदनशीलता, स्कॅन खोली, सिग्नल तीव्रता आणि सक्रिय अलर्ट.',
  'ob.step.map': 'महासागर नकाशा',
  'ob.step.map.desc': 'जीपीएस-टॅग केलेल्या प्रकरणांसह डिटेक्शन्स भौगोलिकरित्या दृश्यमान केले जातात, जी तुम्ही तपासू शकता.',
  'ob.step.mydept': 'माझा विभाग',
  'ob.step.mydept.desc': 'नियुक्त अलर्ट पहा, प्रकरणे मान्य करा, ऑपरेटर नियुक्त करा, पडताळणीची विनंती करा आणि स्थिती अद्यतनित करा.',
  'ob.step.overview': 'विहंगावलोकन डॅशबोर्ड',
  'ob.step.overview.desc': 'सिस्टम-व्यापी डिटेक्शन आकडेवारी, सक्रिय अलर्ट, जोखीम वितरण, प्रतिसाद कार्यक्षमता आणि निरीक्षण क्षेत्रे.',
  'ob.step.reports': 'अहवाल',
  'ob.step.reports.desc': 'नियोजन आणि पुनरावलोकनासाठी सिम्युलेटेड परिचालन अहवाल तयार करा.',
  'ob.step.routing': 'विभाग राउटिंग',
  'ob.step.routing.desc': 'OCEONIX कॉन्फिगर केलेल्या वस्तू आणि जोखीम नियमांचा वापर करून प्रत्येक अलर्ट जबाबदार विभागाकडे राउट करते.',
  'ob.step.settings': 'सेटिंग्ज',
  'ob.step.settings.desc': 'डिटेक्शन उंबरठे, राउटिंग नियम, मुदती, उपकरणे, सूचना आणि डेमो मोड कॉन्फिगर करा.',
  'ob.welcome.desc': 'पाण्याखालील सागरी विसंगती शोधण्यासाठी, विश्लेषण करण्यासाठी, राउट करण्यासाठी आणि व्यवस्थापित करण्यासाठी तुमचा परिचालन इंटरफेस.',
  'ob.welcome.sub': 'पाण्याखालील गुप्तहेरखबरी आणि प्रतिसाद व्यासपीठ',
  'ob.welcome.title': 'Oceanix मध्ये आपले स्वागत आहे',
  'rep.csv': 'CSV निर्यात करा',
  'rep.date': 'दिनांक श्रेणी',
  'rep.pdf': 'PDF डाउनलोड करा',
  'rep.preview': 'पूर्वावलोकन',
  'rep.print': 'प्रिंट',
  'rep.running': 'अहवाल तयार होत आहे',
  'set.anim': 'अॅनिमेशन पातळी',
  'set.beam': 'बीम रुंदी',
  'set.classes': 'कचरा वर्ग',
  'set.confidence': 'डिटेक्शन आत्मविश्वास उंबरठा',
  'set.critonly': 'केवळ गंभीर',
  'set.demomode': 'डेमो मोड',
  'set.deptalerts': 'विभाग अलर्ट',
  'set.deptrules': 'विभाग नियम',
  'set.email': 'ईमेल अलर्ट',
  'set.equiprules': 'उपकरण नियम',
  'set.freq': 'वारंवारता',
  'set.gain': 'गेन',
  'set.notify': 'सूचना प्राधान्ये',
  'set.push': 'पुश सूचना',
  'set.range': 'रेंज',
  'set.response': 'अलर्ट प्रतिसाद वेळा',
  'set.risk': 'जोखीम उंबरठे',
  'set.sonar': 'सोनार कॅलिब्रेशन',
  'set.sound': 'ध्वनी अलर्ट',
  'set.systemalerts': 'सिस्टम अलर्ट',
  'set.tour': 'प्रॉडक्ट टूर पुन्हा प्ले करा',
  'set.tourbtn': 'टूर सुरू करा',
  'set.tvg': 'टीव्हीजी',
  'sfy.category': 'सुरक्षा / आपत्कालीन',
  'sfy.reply': 'शोध व बचाव प्राधान्य म्हणून हाताळा. किनारपट्टी सेवांशी समन्वय करा.',
  'st.acknowledged': 'मान्य केलेले',
  'st.assigned': 'नियुक्त',
  'st.closed': 'बंद',
  'st.escalated': 'एस्केलेट केलेले',
  'st.in_progress': 'प्रगतीपथावर',
  'st.manual_verification': 'पडताळणी आवश्यक',
  'st.new': 'नवीन',
  'st.open': 'उघडे',
  'st.overdue': 'मुदत ओलांडलेले',
  'st.pending': 'प्रलंबित',
  'st.resolved': 'निकाली काढलेले',
  'st.unacknowledged': 'मान्य न केलेले',
  'st.verification': 'पडताळणी आवश्यक',
  'st.verified': 'पडताळलेले',
  'sys.ok': 'सिस्टम सामान्य',
  'sys.version': 'v2.4.1',
  'tok.login': 'सत्र सक्रिय',
  'time.justNow': 'अत्ताच',
  'time.minAgo': '{m} मिनिटांपूर्वी',
  'time.hrAgo': '{h} तासांपूर्वी',
  'time.dayAgo': '{d} दिवसांपूर्वी',
};