export const xEn: Record<string, string> = {
  'batch.status.cancelled': 'Cancelled',
  'batch.sub': 'Queue multiple Side-Scan frames and run the detection core across the batch.',
  'batch.cleared.title': 'Queue cleared',
  'batch.cleared.text': 'All batch items removed.',
  'batch.added.title': '{n} file(s) added',
  'batch.added.text': 'Sonar frames staged for batch processing.',
  'batch.finished.title': 'Batch finished',
  'batch.finished.text': '{done} frame(s) resolved, {failed} failed.',
  'batch.finished.retry': 'Retry available.',
  'batch.exported.title': 'Results exported',
  'batch.exported.csv': '{file} written as CSV.',
  'batch.exported.json': '{file} written as JSON.',
  'batch.clear': 'Clear',
  'batch.stat.processed': 'Processed',
  'batch.stat.frames': 'frames loaded',
  'batch.stat.running': '{n} running',
  'batch.stat.idle': 'idle',
  'batch.stat.objects': 'Objects found',
  'batch.stat.across': 'across batch',
  'batch.stat.avgconf': 'Avg confidence',
  'batch.stat.failed': '{n} failed',
  'batch.stat.allclear': 'all clear',
  'batch.overall': 'Overall progress',
  'batch.complete': 'COMPLETE',
  'batch.addfiles': 'Add Files',
  'batch.addfolder': 'Add Folder',
  'batch.exportcsv': 'Export CSV',
  'batch.exportjson': 'Export JSON',
  'batch.addframes': 'Add Sonar Frames',
  'batch.obj': '{n} obj',
  'batch.remove': 'Remove',
};

export const xHi: Record<string, string> = {
  'batch.status.cancelled': 'रद्द किया गया',
  'batch.sub': 'एकाधिक साइड-स्कैन फ्रेम कतार में जोड़ें और पूरे बैच में डिटेक्शन कोर चलाएं।',
  'batch.cleared.title': 'कतार साफ़ की गई',
  'batch.cleared.text': 'सभी बैच आइटम हटा दिए गए।',
  'batch.added.title': '{n} फ़ाइलें जोड़ी गईं',
  'batch.added.text': 'सोनार फ्रेम बैच प्रोसेसिंग के लिए चरणबद्ध कर दिए गए।',
  'batch.finished.title': 'बैच समाप्त',
  'batch.finished.text': '{done} फ्रेम सफल, {failed} विफल।',
  'batch.finished.retry': 'पुनः प्रयास उपलब्ध है।',
  'batch.exported.title': 'परिणाम निर्यात किए गए',
  'batch.exported.csv': '{file} को CSV के रूप में लिखा गया।',
  'batch.exported.json': '{file} को JSON के रूप में लिखा गया।',
  'batch.clear': 'साफ़ करें',
  'batch.stat.processed': 'प्रसंस्कृत',
  'batch.stat.frames': 'फ्रेम लोड हुए',
  'batch.stat.running': '{n} चालू',
  'batch.stat.idle': 'निष्क्रिय',
  'batch.stat.objects': 'मिली वस्तुएं',
  'batch.stat.across': 'पूरे बैच में',
  'batch.stat.avgconf': 'औसत विश्वास',
  'batch.stat.failed': '{n} विफल',
  'batch.stat.allclear': 'सब साफ़',
  'batch.overall': 'कुल प्रगति',
  'batch.complete': 'पूर्ण',
  'batch.addfiles': 'फ़ाइलें जोड़ें',
  'batch.addfolder': 'फ़ोल्डर जोड़ें',
  'batch.exportcsv': 'CSV निर्यात करें',
  'batch.exportjson': 'JSON निर्यात करें',
  'batch.addframes': 'सोनार फ्रेम जोड़ें',
  'batch.obj': '{n} वस्तु',
  'batch.remove': 'हटाएं',
};

export const xMr: Record<string, string> = {
  'batch.status.cancelled': 'रद्द केले',
  'batch.sub': 'एकाधिक साइड-स्कॅन फ्रेम्स रांगेत जोडा आणि संपूर्ण बॅचवर डिटेक्शन कोर चालवा.',
  'batch.cleared.title': 'रांग साफ केली',
  'batch.cleared.text': 'सर्व बॅच आयटम काढून टाकले.',
  'batch.added.title': '{n} फाइली जोडल्या',
  'batch.added.text': 'सोनार फ्रेम्स बॅच प्रोसेसिंगसाठी स्टेज केल्या.',
  'batch.finished.title': 'बॅच समाप्त',
  'batch.finished.text': '{done} फ्रेम्स सफल, {failed} अयशस्वी.',
  'batch.finished.retry': 'पुन्हा प्रयत्न उपलब्ध आहे.',
  'batch.exported.title': 'निकाल निर्यात केले',
  'batch.exported.csv': '{file} CSV म्हणून लिहिला गेला.',
  'batch.exported.json': '{file} JSON म्हणून लिहिला गेला.',
  'batch.clear': 'साफ करा',
  'batch.stat.processed': 'प्रक्रिया केलेले',
  'batch.stat.frames': 'फ्रेम्स लोड झाल्या',
  'batch.stat.running': '{n} चालू',
  'batch.stat.idle': 'निष्क्रिय',
  'batch.stat.objects': 'सापडलेल्या वस्तू',
  'batch.stat.across': 'संपूर्ण बॅचमध्ये',
  'batch.stat.avgconf': 'सरासरी आत्मविश्वास',
  'batch.stat.failed': '{n} अयशस्वी',
  'batch.stat.allclear': 'सर्व स्पष्ट',
  'batch.overall': 'एकूण प्रगती',
  'batch.complete': 'पूर्ण',
  'batch.addfiles': 'फाइली जोडा',
  'batch.addfolder': 'फोल्डर जोडा',
  'batch.exportcsv': 'CSV निर्यात करा',
  'batch.exportjson': 'JSON निर्यात करा',
  'batch.addframes': 'सोनार फ्रेम्स जोडा',
  'batch.obj': '{n} वस्तू',
  'batch.remove': 'काढा',
};