export const xEn: Record<string, string> = {
  'dpt.title': 'Departments & command',
  'dpt.sub': 'Six response units organised around the OCEONIX routing engine. Scores below are computed live from the ledger.',
  'dpt.ktCommand': 'command chain',
  'dpt.workflow': 'Response workflow',
  'dpt.step.detect': 'Detect',
  'dpt.step.classify': 'Classify',
  'dpt.step.riskScore': 'Risk score',
  'dpt.step.route': 'Route',
  'dpt.step.assign': 'Assign',
  'dpt.step.respond': 'Respond',
  'dpt.step.verify': 'Verify',
  'dpt.role.marineOps': 'Removal, extraction and port logistics for shipwrecks, pipelines and cylinders.',
  'dpt.role.marineEng': 'Scour, structural and subsea engineering work for pipelines and infrastructure.',
  'dpt.role.marineEnv': 'Sea-floor impact, ghost-gear recovery and biodiversity assessments.',
  'dpt.role.searchRescue': 'Detection-to-escalation for human & SAR-class events, immediate response.',
  'dpt.role.oceanSurvey': 'Sonar-mounted monitoring, marine-life tracking and baseline surveys.',
  'dpt.role.recoveryResp': 'Heavy-lift subsea aircraft and debris recovery, coordinated verification.',
  'dpt.role.systemAdmin': 'Routing engine, calibration and platform administration.',
  'dpt.openAlerts': 'Open alerts',
  'dpt.detections': '— detections',
  'dpt.operators': '{n} operators',
  'dpt.inFlight': '{n} in flight',
  'dpt.myDeptView': 'My dept view',
};

export const xHi: Record<string, string> = {
  'dpt.title': 'विभाग और कमान',
  'dpt.sub': 'ओसियोनिक्स रूटिंग इंजन के इर्द-गिर्द संगठित छह प्रतिक्रिया इकाइयाँ। नीचे दिए स्कोर लेजर से लाइव गणना किए जाते हैं।',
  'dpt.ktCommand': 'कमांड चेन',
  'dpt.workflow': 'प्रतिक्रिया कार्यप्रवाह',
  'dpt.step.detect': 'पहचान',
  'dpt.step.classify': 'वर्गीकरण',
  'dpt.step.riskScore': 'जोखिम स्कोर',
  'dpt.step.route': 'रूटिंग',
  'dpt.step.assign': 'नियुक्ति',
  'dpt.step.respond': 'प्रतिक्रिया',
  'dpt.step.verify': 'सत्यापन',
  'dpt.role.marineOps': 'जहाज़ के मलबे, पाइपलाइनों और सिलेंडरों के निष्कासन, निकासी तथा बंदरगाह लॉजिस्टिक्स।',
  'dpt.role.marineEng': 'पाइपलाइनों व बुनियादी ढाँचे के लिए कटाव, संरचनात्मक और समुद्र-तल इंजीनियरिंग कार्य।',
  'dpt.role.marineEnv': 'समुद्र-तल प्रभाव, भूतिया जाल की बरामदगी तथा जैव-विविधता आकलन।',
  'dpt.role.searchRescue': 'मानव व एसएआर श्रेणी की घटनाओं के लिए पहचान से एस्केलेशन तक, तत्काल प्रतिक्रिया।',
  'dpt.role.oceanSurvey': 'सोनार-आधारित निगरानी, समुद्री जीवन ट्रैकिंग तथा आधारभूत सर्वेक्षण।',
  'dpt.role.recoveryResp': 'भारी-उठाव समुद्र-तल विमान और मलबा बरामदगी, समन्वित सत्यापन।',
  'dpt.role.systemAdmin': 'रूटिंग इंजन, कैलिब्रेशन तथा प्लेटफ़ॉर्म प्रशासन।',
  'dpt.openAlerts': 'खुले अलर्ट',
  'dpt.detections': '— डिटेक्शन',
  'dpt.operators': '{n} ऑपरेटर',
  'dpt.inFlight': '{n} कार्यरत',
  'dpt.myDeptView': 'मेरे विभाग का दृश्य',
};

export const xMr: Record<string, string> = {
  'dpt.title': 'विभाग व कमान',
  'dpt.sub': 'ओसियोनिक्स रूटिंग इंजनभोवती संघटित सहा प्रतिसाद एकके. खालील गुणांक लेजरवरून थेट मोजले जातात.',
  'dpt.ktCommand': 'कमांड चेन',
  'dpt.workflow': 'प्रतिसाद कार्यप्रवाह',
  'dpt.step.detect': 'शोध',
  'dpt.step.classify': 'वर्गीकरण',
  'dpt.step.riskScore': 'जोखीम गुणांक',
  'dpt.step.route': 'रूटिंग',
  'dpt.step.assign': 'नेमणूक',
  'dpt.step.respond': 'प्रतिसाद',
  'dpt.step.verify': 'पडताळणी',
  'dpt.role.marineOps': 'जहाजाचे अवशेष, पाइपलाइन आणि सिलिंडर काढणे व बंदरगाह लॉजिस्टिक्स.',
  'dpt.role.marineEng': 'पाइपलाइन व पायाभूत सुविधांसाठी कटाव, संरचनात्मक व समुद्रतळ अभियांत्रिकी कामे.',
  'dpt.role.marineEnv': 'समुद्रतळावरील परिणाम, भुताच्या जाळ्यांची पुनर्प्राप्ती व जैवविविधता मूल्यांकन.',
  'dpt.role.searchRescue': 'मानवी व एसएआर श्रेणीच्या घटनांसाठी शोधापासून स्केलेशनपर्यंत, त्वरित प्रतिसाद.',
  'dpt.role.oceanSurvey': 'सोनार-आधारित निरीक्षण, सागरी जीवन ट्रॅकिंग व आधारभूत सर्वेक्षण.',
  'dpt.role.recoveryResp': 'जड-उचल समुद्रतळ विमान व कचरा पुनर्प्राप्ती, समन्वित पडताळणी.',
  'dpt.role.systemAdmin': 'रूटिंग इंजिन, कॅलिब्रेशन व प्लॅटफॉर्म प्रशासन.',
  'dpt.openAlerts': 'उघडे अलर्ट',
  'dpt.detections': '— डिटेक्शन',
  'dpt.operators': '{n} ऑपरेटर',
  'dpt.inFlight': '{n} चालू',
  'dpt.myDeptView': 'माझ्या विभागाचे दृश्य',
};