export const xEn: Record<string, string> = {
  'detail.kickerCase': 'Case management',
  'detail.kickerMonitor': 'Monitoring ledger',
  'detail.notFound': 'Detection not found',
  'detail.notFoundSub': 'This detection record is unavailable or has been purged.',
  'detail.noSuchCase': 'No such case',
  'detail.noRecordMatch': "No detection record matches '{id}'.",
  'detail.backToHistory': 'Back to history',
  'detail.actionApplied': 'Action applied',
  'detail.sonarRecord': 'Sonar record',
  'detail.detectedObject': 'Detected object',
  'detail.aiModel': 'AI · {model}',
  'detail.sonarFrameAlt': 'Sonar frame',
  'detail.badgeMonitoring': 'Monitoring',
  'detail.badgeDebrisAnomaly': 'Debris / Anomaly',
  'detail.safetyCategory': 'Safety / Emergency category',
  'detail.responseWindow': 'Response window {hours} hours.',
  'detail.marineNote': 'Monitoring only — no debris-removal alert generated. Logged to Ocean Survey ledger.',
  'detail.riskScore': 'Risk score',
  'detail.detectionTime': 'Detection time',
  'detail.estimatedSize': 'Estimated size',
  'detail.estimatedWeight': 'Estimated weight',
  'detail.gpsPosition': 'GPS position',
  'detail.gpsAccuracy': 'GPS accuracy',
  'detail.objectNotes': 'Object notes',
  'detail.equipmentRequirements': 'Equipment requirements',
  'detail.logistics': 'Logistics',
  'detail.requestedCount': '{n} requested',
  'detail.notRequested': 'Not requested',
  'detail.equipRequestSent': 'Equipment request sent to logistics',
  'detail.requestFirstLine': 'Request first-line equipment ({equipment})',
  'detail.routing': 'Routing',
  'detail.routingPath': 'Routing path',
  'detail.sonarDetection': 'Sonar detection',
  'detail.primary': 'Primary',
  'detail.yourDept': 'Your dept',
  'detail.escalationLane': 'Escalation lane',
  'detail.alertReference': 'Alert reference',
  'detail.operator': 'Operator',
  'detail.caseActions': 'Case actions',
  'detail.ackAcceptCase': 'Acknowledge & accept case',
  'detail.claimThisAlert': 'Claim this alert for your department',
  'detail.caseAccepted': 'Case accepted',
  'detail.assignOpOpt': 'Assign operator…',
  'detail.assign': 'Assign',
  'detail.assignedTo': 'Assigned to {operator}',
  'detail.markedInProgress': 'Marked in progress',
  'detail.verificationRequested': 'Verification requested',
  'detail.escalatedNextLane': 'Escalated to next lane',
  'detail.markedResolved': 'Marked resolved',
  'detail.resolutionVerified': 'Resolution verified',
  'detail.verifiedClosed': 'Verified & closed',
  'detail.addNotePlaceholder': 'Add internal note…',
  'detail.noteRecorded': 'Note recorded in ledger',
  'detail.belongsTo': 'This case belongs to ',
  'detail.readOnlyHint': '. You are viewing as read-only.',
  'detail.lifecycle': 'Lifecycle',
  'detail.timeline': 'Timeline',
  'detail.sonarDetRecorded': 'Sonar detection recorded',
  'detail.monitorLedgerEntry': 'Monitoring ledger entry — no alert raised for marine life.',
  'detail.loggedSurvey': 'Logged to survey ledger',
  'detail.mantaObservation': 'Manta observation recorded for Ocean Survey & Monitoring.',
  'detail.internal': 'Internal',
  'detail.departmentNotes': 'Department notes',
};

export const xHi: Record<string, string> = {
  'detail.kickerCase': 'केस प्रबंधन',
  'detail.kickerMonitor': 'निगरानी रजिस्टर',
  'detail.notFound': 'डिटेक्शन नहीं मिला',
  'detail.notFoundSub': 'यह डिटेक्शन रिकॉर्ड उपलब्ध नहीं है या हटा दिया गया है।',
  'detail.noSuchCase': 'ऐसा कोई मामला नहीं',
  'detail.noRecordMatch': "'{id}' से कोई डिटेक्शन रिकॉर्ड मेल नहीं खाता।",
  'detail.backToHistory': 'इतिहास पर वापस जाएँ',
  'detail.actionApplied': 'कार्रवाई लागू की गई',
  'detail.sonarRecord': 'सोनार रिकॉर्ड',
  'detail.detectedObject': 'पहचानी गई वस्तु',
  'detail.aiModel': 'एआई · {model}',
  'detail.sonarFrameAlt': 'सोनार फ़्रेम',
  'detail.badgeMonitoring': 'निगरानी',
  'detail.badgeDebrisAnomaly': 'मलबा / विसंगति',
  'detail.safetyCategory': 'सुरक्षा / आपातकालीन श्रेणी',
  'detail.responseWindow': 'प्रतिक्रिया विंडो {hours} घंटे।',
  'detail.marineNote': 'केवल निगरानी — कोई मलबा-हटाने का अलर्ट नहीं बनाया गया। महासागर सर्वेक्षण रजिस्टर में दर्ज किया गया।',
  'detail.riskScore': 'जोखिम स्कोर',
  'detail.detectionTime': 'डिटेक्शन समय',
  'detail.estimatedSize': 'अनुमानित आकार',
  'detail.estimatedWeight': 'अनुमानित भार',
  'detail.gpsPosition': 'जीपीएस स्थिति',
  'detail.gpsAccuracy': 'जीपीएस सटीकता',
  'detail.objectNotes': 'वस्तु टिप्पणियाँ',
  'detail.equipmentRequirements': 'उपकरण आवश्यकताएँ',
  'detail.logistics': 'लॉजिस्टिक्स',
  'detail.requestedCount': '{n} अनुरोधित',
  'detail.notRequested': 'अनुरोधित नहीं',
  'detail.equipRequestSent': 'उपकरण अनुरोध लॉजिस्टिक्स को भेजा गया',
  'detail.requestFirstLine': 'पहली-पंक्ति उपकरण का अनुरोध करें ({equipment})',
  'detail.routing': 'रूटिंग',
  'detail.routingPath': 'रूटिंग मार्ग',
  'detail.sonarDetection': 'सोनार डिटेक्शन',
  'detail.primary': 'प्राथमिक',
  'detail.yourDept': 'आपका विभाग',
  'detail.escalationLane': 'एस्केलेशन लेन',
  'detail.alertReference': 'अलर्ट संदर्भ',
  'detail.operator': 'ऑपरेटर',
  'detail.caseActions': 'मामले की कार्रवाइयाँ',
  'detail.ackAcceptCase': 'स्वीकार करें और मामला लें',
  'detail.claimThisAlert': 'अपने विभाग के लिए यह अलर्ट दावा करें',
  'detail.caseAccepted': 'मामला स्वीकार किया गया',
  'detail.assignOpOpt': 'ऑपरेटर नियुक्त करें…',
  'detail.assign': 'नियुक्त करें',
  'detail.assignedTo': '{operator} को नियुक्त किया गया',
  'detail.markedInProgress': 'प्रगति में चिह्नित किया गया',
  'detail.verificationRequested': 'सत्यापन का अनुरोध किया गया',
  'detail.escalatedNextLane': 'अगली लेन पर एस्केलेट किया गया',
  'detail.markedResolved': 'हल के रूप में चिह्नित किया गया',
  'detail.resolutionVerified': 'समाधान सत्यापित किया गया',
  'detail.verifiedClosed': 'सत्यापित और बंद किया गया',
  'detail.addNotePlaceholder': 'आंतरिक नोट जोड़ें…',
  'detail.noteRecorded': 'नोट रजिस्टर में दर्ज किया गया',
  'detail.belongsTo': 'यह मामला ',
  'detail.readOnlyHint': ' विभाग का है। आप केवल-पठन मोड में देख रहे हैं।',
  'detail.lifecycle': 'जीवनचक्र',
  'detail.timeline': 'समयरेखा',
  'detail.sonarDetRecorded': 'सोनार डिटेक्शन दर्ज किया गया',
  'detail.monitorLedgerEntry': 'निगरानी रजिस्टर प्रविष्टि — समुद्री जीवन के लिए कोई अलर्ट नहीं बनाया गया।',
  'detail.loggedSurvey': 'सर्वेक्षण रजिस्टर में दर्ज',
  'detail.mantaObservation': 'मंटा अवलोकन महासागर सर्वेक्षण व निगरानी के लिए दर्ज किया गया।',
  'detail.internal': 'आंतरिक',
  'detail.departmentNotes': 'विभागीय नोट्स',
};

export const xMr: Record<string, string> = {
  'detail.kickerCase': 'केस व्यवस्थापन',
  'detail.kickerMonitor': 'निरीक्षण नोंदवही',
  'detail.notFound': 'डिटेक्शन सापडले नाही',
  'detail.notFoundSub': 'हा डिटेक्शन रेकॉर्ड उपलब्ध नाही किंवा हटवला गेला आहे.',
  'detail.noSuchCase': 'असा कोणताही केस नाही',
  'detail.noRecordMatch': "'{id}' शी कोणताही डिटेक्शन रेकॉर्ड जुळत नाही.",
  'detail.backToHistory': 'इतिहासावर परत जा',
  'detail.actionApplied': 'कृती लागू केली',
  'detail.sonarRecord': 'सोनार रेकॉर्ड',
  'detail.detectedObject': 'ओळखलेली वस्तू',
  'detail.aiModel': 'एआय · {model}',
  'detail.sonarFrameAlt': 'सोनार फ्रेम',
  'detail.badgeMonitoring': 'निरीक्षण',
  'detail.badgeDebrisAnomaly': 'कचरा / विसंगती',
  'detail.safetyCategory': 'सुरक्षा / आपत्कालीन श्रेणी',
  'detail.responseWindow': 'प्रतिसाद विंडो {hours} तास.',
  'detail.marineNote': 'फक्त निरीक्षण — कचरा-काढण्याचा अलर्ट तयार केलेला नाही. महासागर सर्वेक्षण नोंदवहीत नोंदवला.',
  'detail.riskScore': 'जोखीम स्कोअर',
  'detail.detectionTime': 'डिटेक्शन वेळ',
  'detail.estimatedSize': 'अंदाजित आकार',
  'detail.estimatedWeight': 'अंदाजित वजन',
  'detail.gpsPosition': 'जीपीएस स्थिती',
  'detail.gpsAccuracy': 'जीपीएस अचूकता',
  'detail.objectNotes': 'वस्तू नोट्स',
  'detail.equipmentRequirements': 'उपकरणांच्या गरजा',
  'detail.logistics': 'लॉजिस्टिक्स',
  'detail.requestedCount': '{n} विनंती',
  'detail.notRequested': 'विनंती केलेली नाही',
  'detail.equipRequestSent': 'उपकरण विनंती लॉजिस्टिक्सला पाठवली',
  'detail.requestFirstLine': 'पहिल्या-ओळीतील उपकरणाची विनंती करा ({equipment})',
  'detail.routing': 'रूटिंग',
  'detail.routingPath': 'रूटिंग मार्ग',
  'detail.sonarDetection': 'सोनार डिटेक्शन',
  'detail.primary': 'प्राथमिक',
  'detail.yourDept': 'तुमचा विभाग',
  'detail.escalationLane': 'एस्केलेशन लेन',
  'detail.alertReference': 'अलर्ट संदर्भ',
  'detail.operator': 'ऑपरेटर',
  'detail.caseActions': 'केस कृती',
  'detail.ackAcceptCase': 'मान्य करा आणि केस स्वीकारा',
  'detail.claimThisAlert': 'तुमच्या विभागासाठी हा अलर्ट दावा करा',
  'detail.caseAccepted': 'केस स्वीकारला',
  'detail.assignOpOpt': 'ऑपरेटर नेमा…',
  'detail.assign': 'नेमा',
  'detail.assignedTo': '{operator} यांना नेमले',
  'detail.markedInProgress': 'प्रगतीपथावर म्हणून चिन्हांकित',
  'detail.verificationRequested': 'पडताळणीची विनंती केली',
  'detail.escalatedNextLane': 'पुढील लेनवर एस्केलेट केले',
  'detail.markedResolved': 'निकाली म्हणून चिन्हांकित',
  'detail.resolutionVerified': 'उत्तर सत्यापित केले',
  'detail.verifiedClosed': 'सत्यापित आणि बंद केले',
  'detail.addNotePlaceholder': 'अंतर्गत नोट जोडा…',
  'detail.noteRecorded': 'नोट नोंदवहीत नोंदवली',
  'detail.belongsTo': 'हा केस ',
  'detail.readOnlyHint': ' विभागाचा आहे. तुम्ही फक्त-वाचन मोडमध्ये पाहत आहात.',
  'detail.lifecycle': 'जीवनचक्र',
  'detail.timeline': 'टाइमलाइन',
  'detail.sonarDetRecorded': 'सोनार डिटेक्शन नोंदवले',
  'detail.monitorLedgerEntry': 'निरीक्षण नोंदवही नोंद — सागरी जीवनासाठी अलर्ट उठवला नाही.',
  'detail.loggedSurvey': 'सर्वेक्षण नोंदवहीत नोंदवले',
  'detail.mantaObservation': 'मांटा निरीक्षण महासागर सर्वेक्षण व निरीक्षणासाठी नोंदवले.',
  'detail.internal': 'अंतर्गत',
  'detail.departmentNotes': 'विभागीय नोट्स',
};