export const xEn: Record<string, string> = {
  'det.sub': "Single frame analysis — drop a Side-Scan Sonar image and run the detection core.",
  'det.ktPipeline': "analysis pipeline",
  'det.analyzing': "Analyzing frame",
  'det.complete': "COMPLETE",
  'det.sonarFrame': "Sonar frame",
  'det.pipelineComplete': "pipeline complete",
  'det.pipelineRunning': "pipeline running",
  'det.ktAnalysis': "analysis",
  'det.emptyHint': "Run the pipeline to generate a detection summary — classification, confidence, size and routing are derived from the uploaded frame.",
  'det.tagModel': "DETECTION MODEL · {file}",
  'det.onDevice': "ON-DEVICE ESTIMATE",
  'det.modelOutput': "MODEL OUTPUT · {label}",
  'det.sounding': "SOUNDING @ {freq} kHz",
  'det.bboxVerified': "BBOX GEOMETRY VERIFIED",
  'det.reqVer': "VERIFICATION REQUIRED",
  'det.autoVerified': "AUTO-VERIFIED",
  'det.riskScore': "Risk score",
  'det.responseWindow': "Response window",
  'det.estDims': "Estimated dimensions",
  'det.estWeight': "Estimated weight",
  'det.position': "Position",
  'det.gpsAccuracy': "{n} m accuracy",
  'det.depthCol': "Depth column",
  'det.removalRouting': "Removal & routing",
  'det.routed': "ROUTED",
  'det.removalMethod': "Removal method",
  'det.respDept': "Responsible department",
  'det.monitorOnly': "Monitoring only — no debris-removal alert generated.",
  'det.escalationLane': "Escalation lane: {dept}",
  'det.noEscalation': "no escalation",
  'det.inspectFull': "Inspect full case",
  'det.runAnother': "Run another frame",
};

export const xHi: Record<string, string> = {
  'det.sub': "एकल फ़्रेम विश्लेषण — साइड-स्कैन सोनार छवि यहाँ डालें और डिटेक्शन कोर चलाएँ।",
  'det.ktPipeline': "विश्लेषण पाइपलाइन",
  'det.analyzing': "फ़्रेम का विश्लेषण जारी है",
  'det.complete': "पूर्ण",
  'det.sonarFrame': "सोनार फ़्रेम",
  'det.pipelineComplete': "पाइपलाइन पूर्ण",
  'det.pipelineRunning': "पाइपलाइन चल रही है",
  'det.ktAnalysis': "विश्लेषण",
  'det.emptyHint': "डिटेक्शन सारांश बनाने के लिए पाइपलाइन चलाएँ — वर्गीकरण, विश्वास स्तर, आकार और रूटिंग अपलोड किए गए फ़्रेम से निकाले जाते हैं।",
  'det.tagModel': "डिटेक्शन मॉडल · {file}",
  'det.onDevice': "डिवाइस-आधारित अनुमान",
  'det.modelOutput': "मॉडल आउटपुट · {label}",
  'det.sounding': "ध्वनि नाप @ {freq} kHz",
  'det.bboxVerified': "BBOX ज्यामिति सत्यापित",
  'det.reqVer': "सत्यापन आवश्यक",
  'det.autoVerified': "स्वतः-सत्यापित",
  'det.riskScore': "जोखिम स्कोर",
  'det.responseWindow': "प्रतिक्रिया अवधि",
  'det.estDims': "अनुमानित आयाम",
  'det.estWeight': "अनुमानित भार",
  'det.position': "स्थिति",
  'det.gpsAccuracy': "{n} मी सटीकता",
  'det.depthCol': "गहराई स्तंभ",
  'det.removalRouting': "निष्कासन और रूटिंग",
  'det.routed': "रूट किया गया",
  'det.removalMethod': "निष्कासन विधि",
  'det.respDept': "उत्तरदायी विभाग",
  'det.monitorOnly': "केवल निगरानी — कोई कचरा-निष्कासन अलर्ट नहीं बनाया गया।",
  'det.escalationLane': "एस्केलेशन लेन: {dept}",
  'det.noEscalation': "कोई एस्केलेशन नहीं",
  'det.inspectFull': "पूरा मामला देखें",
  'det.runAnother': "एक और फ़्रेम चलाएँ",
};

export const xMr: Record<string, string> = {
  'det.sub': "एकल फ्रेम विश्लेषण — साइड-स्कॅन सोनार प्रतिमा इथे टाका आणि डिटेक्शन कोर चालवा.",
  'det.ktPipeline': "विश्लेषण पाइपलाइन",
  'det.analyzing': "फ्रेमचे विश्लेषण सुरू आहे",
  'det.complete': "पूर्ण",
  'det.sonarFrame': "सोनार फ्रेम",
  'det.pipelineComplete': "पाइपलाइन पूर्ण",
  'det.pipelineRunning': "पाइपलाइन चालू आहे",
  'det.ktAnalysis': "विश्लेषण",
  'det.emptyHint': "डिटेक्शन सारांश तयार करण्यासाठी पाइपलाइन चालवा — वर्गीकरण, आत्मविश्वास, आकार आणि रूटिंग अपलोड केलेल्या फ्रेमवरून मिळतात.",
  'det.tagModel': "डिटेक्शन मॉडेल · {file}",
  'det.onDevice': "डिव्हाइस-आधारित अंदाज",
  'det.modelOutput': "मॉडेल आउटपुट · {label}",
  'det.sounding': "ध्वनि नाप @ {freq} kHz",
  'det.bboxVerified': "BBOX भूमिती सत्यापित",
  'det.reqVer': "पडताळणी आवश्यक",
  'det.autoVerified': "स्वयं-सत्यापित",
  'det.riskScore': "जोखीम स्कोअर",
  'det.responseWindow': "प्रतिसाद अवधि",
  'det.estDims': "अंदाजित परिमाणे",
  'det.estWeight': "अंदाजित वजन",
  'det.position': "स्थान",
  'det.gpsAccuracy': "{n} मी अचूकता",
  'det.depthCol': "खोली स्तंभ",
  'det.removalRouting': "काढणे आणि रूटिंग",
  'det.routed': "रूट केले",
  'det.removalMethod': "काढण्याची पद्धत",
  'det.respDept': "जबाबदार विभाग",
  'det.monitorOnly': "केवळ निरीक्षण — कोणताही कचरा-निष्कासन अलर्ट तयार केला गेला नाही.",
  'det.escalationLane': "एस्कलेशन मार्ग: {dept}",
  'det.noEscalation': "एस्कलेशन नाही",
  'det.inspectFull': "संपूर्ण प्रकरण पहा",
  'det.runAnother': "आणखी एक फ्रेम चालवा",
};
