export const xEn: Record<string, string> = {
  'his.sub': '{count} total detections in the ledger.',
  'his.cat.debris': 'Debris',
  'his.cat.anomalies': 'Anomalies',
  'his.cat.infrastructure': 'Infrastructure',
  'his.cat.safety': 'Safety',
  'his.cat.marineLife': 'Marine Life',
  'his.clsAll': 'Class: all',
  'his.riskAll': 'Risk: all',
  'his.searchPh': 'Search ID / class / dept\u2026',
  'his.col.detection': 'Detection',
  'his.col.object': 'Object',
  'his.col.conf': 'Conf.',
  'his.col.dept': 'Dept',
  'his.col.position': 'Position',
  'his.col.detected': 'Detected',
  'his.monitor': 'MONIT.',
  'his.oceanSurvey': 'Ocean Survey',
  'his.emptyTitle': 'No records',
  'his.emptyDesc': 'Try widening the filters or search.',
  'his.clearFilters': 'Clear filters',
  'his.exported': 'History exported',
  'his.exportedText': '{count} records written to CSV.',
  'his.pagination': '{shown} of {total} shown (limit {limit})',
  'his.loadMore': 'Load more',
};

export const xHi: Record<string, string> = {
  'his.sub': '{count} कुल डिटेक्शन लेजर में दर्ज हैं।',
  'his.cat.debris': 'मलबा',
  'his.cat.anomalies': 'विसंगतियाँ',
  'his.cat.infrastructure': 'अवसंरचना',
  'his.cat.safety': 'सुरक्षा',
  'his.cat.marineLife': 'समुद्री जीवन',
  'his.clsAll': 'क्लास: सभी',
  'his.riskAll': 'जोखिम: सभी',
  'his.searchPh': 'आईडी / क्लास / विभाग खोजें\u2026',
  'his.col.detection': 'डिटेक्शन',
  'his.col.object': 'ऑब्जेक्ट',
  'his.col.conf': 'विश्वास',
  'his.col.dept': 'विभाग',
  'his.col.position': 'स्थिति',
  'his.col.detected': 'पता चला',
  'his.monitor': 'मॉनिट.',
  'his.oceanSurvey': 'महासागर सर्वेक्षण',
  'his.emptyTitle': 'कोई रिकॉर्ड नहीं',
  'his.emptyDesc': 'फ़िल्टर या खोज को व्यापक करने का प्रयास करें।',
  'his.clearFilters': 'फ़िल्टर साफ़ करें',
  'his.exported': 'इतिहास निर्यात हुआ',
  'his.exportedText': '{count} रिकॉर्ड CSV में लिखे गए।',
  'his.pagination': '{shown} में से {total} दिखाए गए (सीमा {limit})',
  'his.loadMore': 'और लोड करें',
};

export const xMr: Record<string, string> = {
  'his.sub': '{count} एकूण डिटेक्शन खातेवहीत आहेत।',
  'his.cat.debris': 'कचरा',
  'his.cat.anomalies': 'विसंगती',
  'his.cat.infrastructure': 'पायाभूत सुविधा',
  'his.cat.safety': 'सुरक्षा',
  'his.cat.marineLife': 'सागरी जीवन',
  'his.clsAll': 'वर्ग: सर्व',
  'his.riskAll': 'जोखीम: सर्व',
  'his.searchPh': 'आयडी / वर्ग / विभाग शोधा\u2026',
  'his.col.detection': 'डिटेक्शन',
  'his.col.object': 'वस्तू',
  'his.col.conf': 'आत्मविश्वास',
  'his.col.dept': 'विभाग',
  'his.col.position': 'स्थान',
  'his.col.detected': 'आढळले',
  'his.monitor': 'मॉनिट.',
  'his.oceanSurvey': 'महासागर सर्वेक्षण',
  'his.emptyTitle': 'नोंदी नाहीत',
  'his.emptyDesc': 'फिल्टर किंवा शोध व्यापक करून पहा.',
  'his.clearFilters': 'फिल्टर साफ करा',
  'his.exported': 'इतिहास निर्यात झाला',
  'his.exportedText': '{count} नोंदी CSV मध्ये लिहिल्या गेल्या.',
  'his.pagination': '{shown} पैकी {total} दाखवले (मर्यादा {limit})',
  'his.loadMore': 'अधिक लोड करा',
};