export const xEn: Record<string, string> = {
  'his.sub': '{count} total detections in the ledger.',
  'his.cat.debris': 'Debris',
  'his.cat.anomalies': 'Anomalies',
  'his.cat.infrastructure': 'Infrastructure',
  'his.cat.safety': 'Safety',
  'his.cat.marineLife': 'Marine Life',
  'his.clsAll': 'Class: all',
  'his.riskAll': 'Risk: all',
  'his.searchPh': 'Search ID / class / dept…',
  'his.col.detection': 'Detection',
  'his.col.object': 'Object',
  'his.col.conf': 'Conf.',
  'his.col.dept': 'Dept',
  'his.col.position': 'Position',
  'his.col.detected': 'Detected',
  'his.monitor': 'MONIT.',
  'his.oceanSurvey': 'Ocean Survey',
  'his.emptyTitle': 'No records',
  'his.emptyDesc': 'Try widening the filters or search.',
  'his.clearFilters': 'Clear filters',
  'his.exported': 'History exported',
  'his.exportedText': '{count} records written to CSV.',
  'his.pagination': '{shown} of {total} shown (limit {limit})',
  'his.loadMore': 'Load more',

  'rpt.generate': 'Generate Report',
  'rpt.ktBuilder': 'REPORT BUILDER',
  'rpt.parameters': 'Report Parameters',
  'rpt.timeWindow': 'TIME WINDOW',
  'rpt.deptScope': 'DEPARTMENT SCOPE',
  'rpt.allDepts': 'All Departments',
  'rpt.generateNow': 'Generate Report Now',
  'rpt.builderHint': 'Choose a reporting period and department scope, then generate an operational detection summary.',
  'rpt.ktHistory': 'REPORT HISTORY',
  'rpt.generatedReports': 'Generated Reports',
  'rpt.emptyTitle': 'No reports generated',
  'rpt.emptyDesc': 'Choose report parameters above and generate a report to see it here.',
  'rpt.ktReport': 'REPORT · {window}',
  'rpt.win24': 'Last 24 hours',
  'rpt.win7': 'Last 7 days',
  'rpt.win30': 'Last 30 days',
  'rpt.win90': 'Last 90 days',
  'rpt.cohortTitle': 'Operational Detection Report',
  'rpt.col.objectClass': 'Object Class',
  'rpt.col.count': 'Detections',
  'rpt.col.avgConf': 'Average Confidence',
  'rpt.col.topRegion': 'Primary Department',
  'rpt.statGenerated': 'Generated',
  'rpt.statWindow': 'Reporting Period',
  'rpt.statDetections': 'Total Detections',
  'rpt.statOpenAlerts': 'Open Alerts',
  'rpt.statCritical': 'Critical Risk',
  'rpt.statHigh': 'High Risk',
  'rpt.bodyIntro': 'This report summarizes underwater detection activity for the selected reporting period and department scope.',
  'rpt.bodyObjectDist': 'OBJECT DISTRIBUTION · {n} detections across {c} detected object classes.',
  'rpt.bodyRiskPosture': 'RISK POSTURE · {crit} critical, {high} high, {med} medium, and {low} low-risk detections.',
  'rpt.bodyResponseState': 'RESPONSE STATE · {open} open alerts and {resolved} resolved cases.',
  'rpt.bodyClassFindings': 'CLASS FINDING · {cls} is the most frequently detected class with {n} detection(s).',
  'rpt.toastGen': 'Report generated',
  'rpt.toastGenText': 'Report {id} is ready to review and export.',
  'rpt.toastExport': 'Report exported',
  'rpt.toastExportText': '{file} was generated successfully.',
  'rpt.toastExportError': 'Could not generate {file}.',
  'rpt.pdfId': 'Report ID: {id}',
  'rpt.pdfWindow': 'Reporting Period: {window}',
  'rpt.pdfDepartment': 'Department Scope: {dept}',
  'rpt.pdfGenerated': 'Generated: {date}',
  'rpt.pdfKeyMetrics': 'Key Metrics',
  'rpt.pdfFindings': 'Findings',
  'rpt.pdfDataTable': 'Detection Summary',
};

export const xHi: Record<string, string> = {
  'his.sub': '{count} कुल डिटेक्शन लेजर में दर्ज हैं।',
  'his.cat.debris': 'मलबा',
  'his.cat.anomalies': 'विसंगतियाँ',
  'his.cat.infrastructure': 'अवसंरचना',
  'his.cat.safety': 'सुरक्षा',
  'his.cat.marineLife': 'समुद्री जीवन',
  'his.clsAll': 'क्लास: सभी',
  'his.riskAll': 'जोखिम: सभी',
  'his.searchPh': 'आईडी / क्लास / विभाग खोजें…',
  'his.col.detection': 'डिटेक्शन',
  'his.col.object': 'ऑब्जेक्ट',
  'his.col.conf': 'विश्वास',
  'his.col.dept': 'विभाग',
  'his.col.position': 'स्थिति',
  'his.col.detected': 'पता चला',
  'his.monitor': 'मॉनिट.',
  'his.oceanSurvey': 'महासागर सर्वेक्षण',
  'his.emptyTitle': 'कोई रिकॉर्ड नहीं',
  'his.emptyDesc': 'फ़िल्टर या खोज को व्यापक करने का प्रयास करें।',
  'his.clearFilters': 'फ़िल्टर साफ़ करें',
  'his.exported': 'इतिहास निर्यात हुआ',
  'his.exportedText': '{count} रिकॉर्ड CSV में लिखे गए।',
  'his.pagination': '{shown} में से {total} दिखाए गए (सीमा {limit})',
  'his.loadMore': 'और लोड करें',

  'rpt.generate': 'रिपोर्ट बनाएँ',
  'rpt.ktBuilder': 'रिपोर्ट बिल्डर',
  'rpt.parameters': 'रिपोर्ट पैरामीटर',
  'rpt.timeWindow': 'समय अवधि',
  'rpt.deptScope': 'विभाग दायरा',
  'rpt.allDepts': 'सभी विभाग',
  'rpt.generateNow': 'रिपोर्ट अभी बनाएँ',
  'rpt.builderHint': 'समय अवधि और विभाग चुनें, फिर परिचालन डिटेक्शन सारांश बनाएँ।',
  'rpt.ktHistory': 'रिपोर्ट इतिहास',
  'rpt.generatedReports': 'बनाई गई रिपोर्ट',
  'rpt.emptyTitle': 'अभी कोई रिपोर्ट नहीं',
  'rpt.emptyDesc': 'ऊपर रिपोर्ट पैरामीटर चुनें और रिपोर्ट बनाएँ।',
  'rpt.ktReport': 'रिपोर्ट · {window}',
  'rpt.win24': 'पिछले 24 घंटे',
  'rpt.win7': 'पिछले 7 दिन',
  'rpt.win30': 'पिछले 30 दिन',
  'rpt.win90': 'पिछले 90 दिन',
  'rpt.cohortTitle': 'परिचालन डिटेक्शन रिपोर्ट',
  'rpt.col.objectClass': 'ऑब्जेक्ट क्लास',
  'rpt.col.count': 'डिटेक्शन',
  'rpt.col.avgConf': 'औसत विश्वास',
  'rpt.col.topRegion': 'प्रमुख विभाग',
  'rpt.statGenerated': 'बनाई गई',
  'rpt.statWindow': 'रिपोर्टिंग अवधि',
  'rpt.statDetections': 'कुल डिटेक्शन',
  'rpt.statOpenAlerts': 'खुले अलर्ट',
  'rpt.statCritical': 'गंभीर जोखिम',
  'rpt.statHigh': 'उच्च जोखिम',
  'rpt.bodyIntro': 'यह रिपोर्ट चुनी गई अवधि और विभाग दायरे के लिए पानी के भीतर की डिटेक्शन गतिविधि का सारांश देती है।',
  'rpt.bodyObjectDist': 'ऑब्जेक्ट वितरण · {n} डिटेक्शन और {c} ऑब्जेक्ट क्लास।',
  'rpt.bodyRiskPosture': 'जोखिम स्थिति · {crit} गंभीर, {high} उच्च, {med} मध्यम और {low} निम्न जोखिम डिटेक्शन।',
  'rpt.bodyResponseState': 'प्रतिक्रिया स्थिति · {open} खुले अलर्ट और {resolved} हल किए गए मामले।',
  'rpt.bodyClassFindings': 'क्लास निष्कर्ष · {cls} सबसे अधिक पाया गया क्लास है, जिसमें {n} डिटेक्शन हैं।',
  'rpt.toastGen': 'रिपोर्ट तैयार है',
  'rpt.toastGenText': 'रिपोर्ट {id} समीक्षा और निर्यात के लिए तैयार है।',
  'rpt.toastExport': 'रिपोर्ट निर्यात हुई',
  'rpt.toastExportText': '{file} सफलतापूर्वक बनाई गई।',
  'rpt.toastExportError': '{file} नहीं बनाई जा सकी।',
  'rpt.pdfId': 'रिपोर्ट आईडी: {id}',
  'rpt.pdfWindow': 'रिपोर्टिंग अवधि: {window}',
  'rpt.pdfDepartment': 'विभाग दायरा: {dept}',
  'rpt.pdfGenerated': 'बनाई गई: {date}',
  'rpt.pdfKeyMetrics': 'मुख्य मेट्रिक्स',
  'rpt.pdfFindings': 'निष्कर्ष',
  'rpt.pdfDataTable': 'डिटेक्शन सारांश',
};

export const xMr: Record<string, string> = {
  'his.sub': '{count} एकूण डिटेक्शन खातेवहीत आहेत।',
  'his.cat.debris': 'कचरा',
  'his.cat.anomalies': 'विसंगती',
  'his.cat.infrastructure': 'पायाभूत सुविधा',
  'his.cat.safety': 'सुरक्षा',
  'his.cat.marineLife': 'सागरी जीवन',
  'his.clsAll': 'वर्ग: सर्व',
  'his.riskAll': 'जोखीम: सर्व',
  'his.searchPh': 'आयडी / वर्ग / विभाग शोधा…',
  'his.col.detection': 'डिटेक्शन',
  'his.col.object': 'वस्तू',
  'his.col.conf': 'आत्मविश्वास',
  'his.col.dept': 'विभाग',
  'his.col.position': 'स्थान',
  'his.col.detected': 'आढळले',
  'his.monitor': 'मॉनिट.',
  'his.oceanSurvey': 'महासागर सर्वेक्षण',
  'his.emptyTitle': 'नोंदी नाहीत',
  'his.emptyDesc': 'फिल्टर किंवा शोध व्यापक करून पहा.',
  'his.clearFilters': 'फिल्टर साफ करा',
  'his.exported': 'इतिहास निर्यात झाला',
  'his.exportedText': '{count} नोंदी CSV मध्ये लिहिल्या गेल्या.',
  'his.pagination': '{shown} पैकी {total} दाखवले (मर्यादा {limit})',
  'his.loadMore': 'अधिक लोड करा',

  'rpt.generate': 'अहवाल तयार करा',
  'rpt.ktBuilder': 'अहवाल बिल्डर',
  'rpt.parameters': 'अहवाल पॅरामीटर्स',
  'rpt.timeWindow': 'कालावधी',
  'rpt.deptScope': 'विभाग व्याप्ती',
  'rpt.allDepts': 'सर्व विभाग',
  'rpt.generateNow': 'अहवाल आत्ताच तयार करा',
  'rpt.builderHint': 'कालावधी आणि विभाग निवडा, त्यानंतर परिचालन डिटेक्शन सारांश तयार करा.',
  'rpt.ktHistory': 'अहवाल इतिहास',
  'rpt.generatedReports': 'तयार केलेले अहवाल',
  'rpt.emptyTitle': 'अजून कोणतेही अहवाल नाहीत',
  'rpt.emptyDesc': 'वरील अहवाल पॅरामीटर्स निवडा आणि अहवाल तयार करा.',
  'rpt.ktReport': 'अहवाल · {window}',
  'rpt.win24': 'मागील 24 तास',
  'rpt.win7': 'मागील 7 दिवस',
  'rpt.win30': 'मागील 30 दिवस',
  'rpt.win90': 'मागील 90 दिवस',
  'rpt.cohortTitle': 'परिचालन डिटेक्शन अहवाल',
  'rpt.col.objectClass': 'ऑब्जेक्ट वर्ग',
  'rpt.col.count': 'डिटेक्शन',
  'rpt.col.avgConf': 'सरासरी आत्मविश्वास',
  'rpt.col.topRegion': 'प्रमुख विभाग',
  'rpt.statGenerated': 'तयार केले',
  'rpt.statWindow': 'अहवाल कालावधी',
  'rpt.statDetections': 'एकूण डिटेक्शन',
  'rpt.statOpenAlerts': 'उघडे अलर्ट',
  'rpt.statCritical': 'गंभीर जोखीम',
  'rpt.statHigh': 'उच्च जोखीम',
  'rpt.bodyIntro': 'हा अहवाल निवडलेल्या कालावधी आणि विभाग व्याप्तीसाठी पाण्याखालील डिटेक्शन क्रियाकलापाचा सारांश देतो.',
  'rpt.bodyObjectDist': 'ऑब्जेक्ट वितरण · {n} डिटेक्शन आणि {c} ऑब्जेक्ट वर्ग.',
  'rpt.bodyRiskPosture': 'जोखीम स्थिती · {crit} गंभीर, {high} उच्च, {med} मध्यम आणि {low} कमी जोखीम डिटेक्शन.',
  'rpt.bodyResponseState': 'प्रतिसाद स्थिती · {open} उघडे अलर्ट आणि {resolved} निकाली काढलेली प्रकरणे.',
  'rpt.bodyClassFindings': 'वर्ग निष्कर्ष · {cls} हा सर्वाधिक आढळलेला वर्ग आहे, ज्यामध्ये {n} डिटेक्शन आहेत.',
  'rpt.toastGen': 'अहवाल तयार झाला',
  'rpt.toastGenText': 'अहवाल {id} पुनरावलोकन आणि निर्यातीसाठी तयार आहे.',
  'rpt.toastExport': 'अहवाल निर्यात झाला',
  'rpt.toastExportText': '{file} यशस्वीरित्या तयार झाली.',
  'rpt.toastExportError': '{file} तयार करता आली नाही.',
  'rpt.pdfId': 'अहवाल आयडी: {id}',
  'rpt.pdfWindow': 'अहवाल कालावधी: {window}',
  'rpt.pdfDepartment': 'विभाग व्याप्ती: {dept}',
  'rpt.pdfGenerated': 'तयार केले: {date}',
  'rpt.pdfKeyMetrics': 'मुख्य मेट्रिक्स',
  'rpt.pdfFindings': 'निष्कर्ष',
  'rpt.pdfDataTable': 'डिटेक्शन सारांश',
};
