export const xEn: Record<string, string> = {
  'lan.how': 'How it works',
  'lan.capabilities': 'Capabilities',
  'lan.classes': 'Detection classes',
  'lan.response': 'Response',
  'lan.live': 'Live',
  'lan.data': 'Data',
  'lan.openPortal': 'Open Portal',
  'lan.heroBadge': 'SIDE-SCAN SONAR INTELLIGENCE',
  'lan.heroTitle1': 'Detect what hides',
  'lan.heroTitle2': 'beneath the surface.',
  'lan.heroLead': 'OCEONIX ingests side-scan sonar frames, classifies debris and anomalies with a YOLO detection core, routes each find to the responsible department, and tracks response to verified resolution.',
  'lan.launchDetection': 'Launch Detection',
  'lan.exploreLive': 'Explore Live Monitor',
  'lan.viewOceanMap': 'View Ocean Map',
  'lan.latitude': 'Latitude (target)',
  'lan.longitude': 'Longitude (target)',
  'lan.waterColumn': 'Water column',
  'lan.sweep': 'SWEEP {n}',
  'lan.confShort': 'conf',
  'lan.routedTo': 'Routed → {dept}',
  'lan.howKicker': 'Detection pipeline',
  'lan.howTitle': 'From acoustic return to verified resolution',
  'lan.howDesc': 'Every object follows a defined chain of analysis, risk assessment, and department routing — so nothing is dropped.',
  'lan.sonarDetection': 'SONAR DETECTION',
  'lan.aiClassification': 'AI CLASSIFICATION',
  'lan.riskAssessment': 'RISK ASSESSMENT',
  'lan.routingRule': 'ROUTING RULE',
  'lan.responsibleDept': 'RESPONSIBLE DEPARTMENT',
  'lan.deptAlertInbox': 'DEPARTMENT ALERT INBOX',
  'lan.operatorAssignment': 'OPERATOR ASSIGNMENT',
  'lan.fieldResponse': 'FIELD RESPONSE',
  'lan.resolution': 'RESOLUTION',
  'lan.verification': 'VERIFICATION',
  'lan.wfSideScanSonar': 'SIDE-SCAN SONAR',
  'lan.wfImageUpload': 'IMAGE UPLOAD',
  'lan.wfAiDetection': 'AI DETECTION',
  'lan.wfObjectClassification': 'OBJECT CLASSIFICATION',
  'lan.wfConfidenceVerification': 'CONFIDENCE VERIFICATION',
  'lan.wfGpsTagging': 'GPS TAGGING',
  'lan.wfSizeEstimation': 'SIZE ESTIMATION',
  'lan.wfWeightEstimation': 'WEIGHT ESTIMATION',
  'lan.wfDepartmentRouting': 'DEPARTMENT ROUTING',
  'lan.wfEquipmentAllocation': 'EQUIPMENT ALLOCATION',
  'lan.wfResponse': 'RESPONSE',
  'lan.capKicker': 'AI capabilities',
  'lan.capTitle': 'Acoustic models built for the seafloor',
  'lan.capDesc': 'An analysis core tuned on side-scan returns — from confidence verification to weight estimation and response planning.',
  'lan.cap1Title': 'Sonar frame ingestion',
  'lan.cap1Desc': '600 kHz side-scan frames, gain and TVG-corrected, with towfish metadata preserved end to end.',
  'lan.cap2Title': 'YOLO object detection',
  'lan.cap2Desc': 'Seven target classes — shipwreck, pipeline, ghost gear, cylinder, manta, aircraft, person — from a trained best.pt core.',
  'lan.cap3Title': 'Estimate engine',
  'lan.cap3Desc': 'Dimensions and weight ranges derived from sonar shadow geometry with a stated confidence per estimate.',
  'lan.cap4Title': 'Risk & priority scoring',
  'lan.cap4Desc': 'Environmental impact and hazard scoring assign an explicit response deadline before a single operator is involved.',
  'lan.cap5Title': 'Automatic routing',
  'lan.cap5Desc': 'Object class + risk resolve to a responsible department by rule — with escalation paths and delivery confirmations.',
  'lan.cap6Title': 'Verification loop',
  'lan.cap6Desc': 'Every resolved case closes with imagery review and an operator confirmation before analytics are updated.',
  'lan.clsTitle': 'Seven classes, one sonar signature language',
  'lan.clsDesc': 'Simulated frames rendered from acoustic return models — debris, infrastructure, marine life, and safety categories with distinct handling.',
  'lan.riskColon': 'risk:',
  'lan.respKicker': 'Response intelligence',
  'lan.respTitle': 'Alerts that already know their department',
  'lan.respDesc': 'Routing rules, escalation lanes, equipment assignment, and deadlines are resolved the moment a detection is confirmed.',
  'lan.ruleTable': 'Rule table',
  'lan.liveRoutingEvent': 'Live routing event',
  'lan.tagAiRouted': 'AI ROUTED',
  'lan.tagRuleBased': 'RULE-BASED ASSIGNMENT',
  'lan.tagVerification': 'VERIFICATION REQUIRED',
  'lan.frameCaptured': '{code} frame captured',
  'lan.routeClassified': '{cls} · {conf}',
  'lan.routeRiskDeadline': '{risk} · deadline {hours}h',
  'lan.routeEnvDept': 'Marine Environmental',
  'lan.active': 'ACTIVE',
  'lan.routeEnRoute': 'En route → {code} · {dept}',
  'lan.routeDispatch': '{detail} · resp. {hours}h',
  'lan.liveKicker': 'Live monitoring',
  'lan.liveTitle': 'The control room, running in your browser',
  'lan.liveDesc': 'A full monitoring surface — radar sweep, incoming detections, signal telemetry, and system health — simulated for demonstration.',
  'lan.liveSweep': 'LIVE SWEEP',
  'lan.openLive': 'Open Live Monitor',
  'lan.signal': 'Signal strength',
  'lan.depth': 'Scan depth',
  'lan.objects': 'Detected objects',
  'lan.alerts': 'Active alerts',
  'lan.gps': 'GPS fix',
  'lan.health': 'System health',
  'lan.aiCorePct': 'AI Core {pct}%',
  'lan.healthSonar': 'Sonar array optimal',
  'lan.healthGps': 'GPS fix locked',
  'lan.statsKicker': 'By the numbers',
  'lan.statsTitle': 'Operational scale, demonstrated live',
  'lan.statsDesc': 'All figures are simulated demo telemetry powering the analytics and reporting surfaces of this build.',
  'lan.enterPlatform': 'Enter the platform',
  'lan.statDetections': 'Detections this year',
  'lan.statDebris': 'Débris recovered (tonnes)',
  'lan.statResponse': 'Average response (h)',
  'lan.statCoverage': 'Monitoring coverage (km²)',
  'lan.footerPlatform': 'Platform',
  'lan.copyright': '© {year} OCEONIX Systems',
  'lan.demoBuild': 'Frontend-only demonstration build',
  'lan.versionLine': 'v2.4.1 · sonar link 600 kHz',
};

export const xHi: Record<string, string> = {
  'lan.how': 'यह कैसे काम करता है',
  'lan.capabilities': 'क्षमताएँ',
  'lan.classes': 'डिटेक्शन वर्ग',
  'lan.response': 'प्रतिक्रिया',
  'lan.live': 'लाइव',
  'lan.data': 'डेटा',
  'lan.openPortal': 'पोर्टल खोलें',
  'lan.heroBadge': 'साइड-स्कैन सोनार इंटेलिजेंस',
  'lan.heroTitle1': 'खोजें वह जो छिपा है',
  'lan.heroTitle2': 'सतह के नीचे।',
  'lan.heroLead': 'OCEONIX साइड-स्कैन सोनार फ्रेम लेता है, YOLO डिटेक्शन कोर की मदद से कचरे और विसंगतियों का वर्गीकरण करता है, हर खोज को जिम्मेदार विभाग तक पहुँचाता है, और सत्यापित समाधान तक प्रतिक्रिया को ट्रैक करता है।',
  'lan.launchDetection': 'डिटेक्शन शुरू करें',
  'lan.exploreLive': 'लाइव मॉनिटर देखें',
  'lan.viewOceanMap': 'महासागर नक्शा देखें',
  'lan.latitude': 'अक्षांश (लक्ष्य)',
  'lan.longitude': 'देशांतर (लक्ष्य)',
  'lan.waterColumn': 'जल स्तंभ',
  'lan.sweep': 'SWEEP {n}',
  'lan.confShort': 'विश्वास',
  'lan.routedTo': 'रूटेड → {dept}',
  'lan.howKicker': 'डिटेक्शन पाइपलाइन',
  'lan.howTitle': 'ध्वनिक प्रतिध्वनि से सत्यापित समाधान तक',
  'lan.howDesc': 'हर वस्तु विश्लेषण, जोखिम मूल्यांकन और विभाग रूटिंग की निर्धारित श्रृंखला से गुजरती है — ताकि कुछ भी छूटे नहीं।',
  'lan.sonarDetection': 'सोनार डिटेक्शन',
  'lan.aiClassification': 'एआई वर्गीकरण',
  'lan.riskAssessment': 'जोखिम मूल्यांकन',
  'lan.routingRule': 'रूटिंग नियम',
  'lan.responsibleDept': 'जिम्मेदार विभाग',
  'lan.deptAlertInbox': 'विभाग अलर्ट इनबॉक्स',
  'lan.operatorAssignment': 'ऑपरेटर असाइनमेंट',
  'lan.fieldResponse': 'फ़ील्ड प्रतिक्रिया',
  'lan.resolution': 'समाधान',
  'lan.verification': 'सत्यापन',
  'lan.wfSideScanSonar': 'साइड-स्कैन सोनार',
  'lan.wfImageUpload': 'छवि अपलोड',
  'lan.wfAiDetection': 'एआई डिटेक्शन',
  'lan.wfObjectClassification': 'वस्तु वर्गीकरण',
  'lan.wfConfidenceVerification': 'विश्वास स्तर सत्यापन',
  'lan.wfGpsTagging': 'जीपीएस टैगिंग',
  'lan.wfSizeEstimation': 'आकार अनुमान',
  'lan.wfWeightEstimation': 'वज़न अनुमान',
  'lan.wfDepartmentRouting': 'विभाग रूटिंग',
  'lan.wfEquipmentAllocation': 'उपकरण आवंटन',
  'lan.wfResponse': 'प्रतिक्रिया',
  'lan.capKicker': 'एआई क्षमताएँ',
  'lan.capTitle': 'समुद्र तल के लिए बनाए गए ध्वनिक मॉडल',
  'lan.capDesc': 'साइड-स्कैन प्रतिध्वनियों पर प्रशिक्षित एक विश्लेषण कोर — विश्वास स्तर सत्यापन से लेकर वज़न अनुमान और प्रतिक्रिया योजना तक।',
  'lan.cap1Title': 'सोनार फ्रेम अंतर्ग्रहण',
  'lan.cap1Desc': '600 kHz साइड-स्कैन फ्रेम, गेन और TVG-सुधारित, टोफिश मेटाडेटा अंत तक संरक्षित।',
  'lan.cap2Title': 'YOLO वस्तु डिटेक्शन',
  'lan.cap2Desc': 'सात लक्ष्य वर्ग — जहाज का मलबा, पाइपलाइन, भूतिया जाल, सिलेंडर, मंटा किरण, विमान, व्यक्ति — प्रशिक्षित best.pt कोर से।',
  'lan.cap3Title': 'अनुमान इंजन',
  'lan.cap3Desc': 'सोनार छाया ज्यामिति से प्राप्त आयाम और वज़न सीमाएँ, हर अनुमान के लिए स्पष्ट विश्वास स्तर के साथ।',
  'lan.cap4Title': 'जोखिम व प्राथमिकता स्कोरिंग',
  'lan.cap4Desc': 'पर्यावरणीय प्रभाव और खतरा स्कोरिंग किसी भी ऑपरेटर के शामिल होने से पहले स्पष्ट प्रतिक्रिया समय-सीमा निर्धारित करती है।',
  'lan.cap5Title': 'स्वचालित रूटिंग',
  'lan.cap5Desc': 'वस्तु वर्ग + जोखिम नियम के अनुसार जिम्मेदार विभाग तय करते हैं — एस्केलेशन मार्ग और वितरण पुष्टि के साथ।',
  'lan.cap6Title': 'सत्यापन चक्र',
  'lan.cap6Desc': 'हर हल मामला इमेजरी समीक्षा और ऑपरेटर पुष्टि के साथ बंद होता है, इससे पहले एनालिटिक्स अपडेट हों।',
  'lan.clsTitle': 'सात वर्ग, एक सोनार सिग्नेचर भाषा',
  'lan.clsDesc': 'ध्वनिक प्रतिध्वनि मॉडल से बनाई गई अनुकरणीय फ्रेम — कचरा, बुनियादी ढाँचा, समुद्री जीवन और सुरक्षा श्रेणियाँ अलग-अलग हैंडलिंग के साथ।',
  'lan.riskColon': 'जोखिम:',
  'lan.respKicker': 'प्रतिक्रिया इंटेलिजेंस',
  'lan.respTitle': 'अलर्ट जो पहले से अपने विभाग को जानते हैं',
  'lan.respDesc': 'रूटिंग नियम, एस्केलेशन पथ, उपकरण आवंटन और समय-सीमाएँ डिटेक्शन की पुष्टि होते ही तय हो जाती हैं।',
  'lan.ruleTable': 'नियम तालिका',
  'lan.liveRoutingEvent': 'लाइव रूटिंग घटना',
  'lan.tagAiRouted': 'एआई रूटेड',
  'lan.tagRuleBased': 'नियम-आधारित असाइनमेंट',
  'lan.tagVerification': 'सत्यापन आवश्यक',
  'lan.frameCaptured': '{code} फ्रेम कैप्चर हुई',
  'lan.routeClassified': '{cls} · {conf}',
  'lan.routeRiskDeadline': '{risk} · समय सीमा {hours}h',
  'lan.routeEnvDept': 'समुद्री पर्यावरण',
  'lan.active': 'सक्रिय',
  'lan.routeEnRoute': 'रास्ते में → {code} · {dept}',
  'lan.routeDispatch': '{detail} · प्रतिक्रिया {hours}h',
  'lan.liveKicker': 'लाइव निगरानी',
  'lan.liveTitle': 'कंट्रोल रूम, सीधे आपके ब्राउज़र में',
  'lan.liveDesc': 'पूर्ण निगरानी सतह — रडार स्वीप, आने वाले डिटेक्शन, सिग्नल टेलीमेट्री और सिस्टम स्वास्थ्य — प्रदर्शन के लिए अनुकरणित।',
  'lan.liveSweep': 'लाइव स्वीप',
  'lan.openLive': 'लाइव मॉनिटर खोलें',
  'lan.signal': 'सिग्नल शक्ति',
  'lan.depth': 'स्कैन गहराई',
  'lan.objects': 'डिटेक्ट की गई वस्तुएँ',
  'lan.alerts': 'सक्रिय अलर्ट',
  'lan.gps': 'जीपीएस फिक्स',
  'lan.health': 'सिस्टम स्वास्थ्य',
  'lan.aiCorePct': 'एआई कोर {pct}%',
  'lan.healthSonar': 'सोनार ऐरे इष्टतम',
  'lan.healthGps': 'जीपीएस फिक्स लॉक',
  'lan.statsKicker': 'आँकड़ों की नज़र से',
  'lan.statsTitle': 'परिचालन पैमाना, लाइव प्रदर्शित',
  'lan.statsDesc': 'सभी आँकड़े अनुकरणित डेमो टेलीमेट्री हैं जो इस बिल्ड के एनालिटिक्स और रिपोर्टिंग को संचालित करते हैं।',
  'lan.enterPlatform': 'प्लेटफ़ॉर्म में प्रवेश करें',
  'lan.statDetections': 'इस वर्ष के डिटेक्शन',
  'lan.statDebris': 'बरामद किया गया मलबा (टन)',
  'lan.statResponse': 'औसत प्रतिक्रिया (घंटे)',
  'lan.statCoverage': 'निगरानी कवरेज (km²)',
  'lan.footerPlatform': 'प्लेटफ़ॉर्म',
  'lan.copyright': '© {year} OCEONIX Systems',
  'lan.demoBuild': 'केवल फ्रंटेंड प्रदर्शन बिल्ड',
  'lan.versionLine': 'v2.4.1 · सोनार लिंक 600 kHz',
};

export const xMr: Record<string, string> = {
  'lan.how': 'हे कसे कार्य करते',
  'lan.capabilities': 'क्षमता',
  'lan.classes': 'डिटेक्शन वर्ग',
  'lan.response': 'प्रतिसाद',
  'lan.live': 'लाइव्ह',
  'lan.data': 'डेटा',
  'lan.openPortal': 'पोर्टल उघडा',
  'lan.heroBadge': 'साइड-स्कॅन सोनार इंटेलिजन्स',
  'lan.heroTitle1': 'शोधा ते जे लपले आहे',
  'lan.heroTitle2': 'पृष्ठभागाखाली.',
  'lan.heroLead': 'OCEONIX साइड-स्कॅन सोनार फ्रेम घेते, YOLO डिटेक्शन कोअरच्या साह्याने कचरा व विसंगतींचे वर्गीकरण करते, प्रत्येक शोध जबाबदार विभागापर्यंत पोहोचवते, आणि प्रमाणित निराकरणापर्यंत प्रतिसाद ट्रॅक करते.',
  'lan.launchDetection': 'डिटेक्शन सुरू करा',
  'lan.exploreLive': 'लाइव्ह मॉनिटर पहा',
  'lan.viewOceanMap': 'महासागर नकाशा पहा',
  'lan.latitude': 'अक्षांश (लक्ष्य)',
  'lan.longitude': 'रेखांश (लक्ष्य)',
  'lan.waterColumn': 'जल स्तंभ',
  'lan.sweep': 'SWEEP {n}',
  'lan.confShort': 'विश्वास',
  'lan.routedTo': 'रूट केले → {dept}',
  'lan.howKicker': 'डिटेक्शन पाइपलाइन',
  'lan.howTitle': 'ध्वनिक परावर्तनापासून प्रमाणित निराकरणापर्यंत',
  'lan.howDesc': 'प्रत्येक वस्तू विश्लेषण, जोखीम मूल्यांकन आणि विभाग रूटिंगच्या निश्चित साखळीतून जाते — म्हणून काहीही सुटत नाही.',
  'lan.sonarDetection': 'सोनार डिटेक्शन',
  'lan.aiClassification': 'एआय वर्गीकरण',
  'lan.riskAssessment': 'जोखीम मूल्यांकन',
  'lan.routingRule': 'रूटिंग नियम',
  'lan.responsibleDept': 'जबाबदार विभाग',
  'lan.deptAlertInbox': 'विभाग अलर्ट इनबॉक्स',
  'lan.operatorAssignment': 'ऑपरेटर नियुक्ती',
  'lan.fieldResponse': 'फील्ड प्रतिसाद',
  'lan.resolution': 'निराकरण',
  'lan.verification': 'प्रमाणीकरण',
  'lan.wfSideScanSonar': 'साइड-स्कॅन सोनार',
  'lan.wfImageUpload': 'प्रतिमा अपलोड',
  'lan.wfAiDetection': 'एआय डिटेक्शन',
  'lan.wfObjectClassification': 'वस्तू वर्गीकरण',
  'lan.wfConfidenceVerification': 'आत्मविश्वास प्रमाणीकरण',
  'lan.wfGpsTagging': 'जीपीएस टॅगिंग',
  'lan.wfSizeEstimation': 'आकार अंदाज',
  'lan.wfWeightEstimation': 'वजन अंदाज',
  'lan.wfDepartmentRouting': 'विभाग रूटिंग',
  'lan.wfEquipmentAllocation': 'उपकरण वाटप',
  'lan.wfResponse': 'प्रतिसाद',
  'lan.capKicker': 'एआय क्षमता',
  'lan.capTitle': 'समुद्रतळासाठी तयार केलेले ध्वनिक मॉडेल',
  'lan.capDesc': 'साइड-स्कॅन परावर्तनांवर प्रशिक्षित विश्लेषण कोअर — आत्मविश्वास प्रमाणीकरणापासून वजन अंदाज आणि प्रतिसाद नियोजनापर्यंत.',
  'lan.cap1Title': 'सोनार फ्रेम संकलन',
  'lan.cap1Desc': '600 kHz साइड-स्कॅन फ्रेम, गेन आणि TVG-दुरुस्त, टॉफिश मेटाडेटा शेवटपर्यंत जतन.',
  'lan.cap2Title': 'YOLO वस्तू डिटेक्शन',
  'lan.cap2Desc': 'सात लक्ष्य वर्ग — जहाजाचे अवशेष, पाइपलाइन, भुताचे जाळे, सिलेंडर, मांटा किरण, विमान, व्यक्ती — प्रशिक्षित best.pt कोअरमधून.',
  'lan.cap3Title': 'अंदाज इंजिन',
  'lan.cap3Desc': 'सोनार सावली भूमितीतून मिळणारे परिमाण व वजन श्रेणी, प्रत्येक अंदाजासाठी नमूद केलेल्या आत्मविश्वासासह.',
  'lan.cap4Title': 'जोखीम व प्राधान्य स्कोअरिंग',
  'lan.cap4Desc': 'पर्यावरणीय परिणाम व धोका स्कोअरिंग कोणत्याही ऑपरेटरचा सहभाग होण्यापूर्वी स्पष्ट प्रतिसाद मुदत ठरवते.',
  'lan.cap5Title': 'स्वयंचलित रूटिंग',
  'lan.cap5Desc': 'वस्तू वर्ग + जोखीम नियमानुसार जबाबदार विभाग ठरवतात — एस्केलेशन मार्ग आणि वितरण पुष्ट्यांसह.',
  'lan.cap6Title': 'प्रमाणीकरण चक्र',
  'lan.cap6Desc': 'प्रत्येक निकाली काढलेला केस प्रतिमा पुनरावलोकन आणि ऑपरेटर पुष्ट्यांसह बंद होतो, विश्लेषण अपडेट होण्यापूर्वी.',
  'lan.clsTitle': 'सात वर्ग, एक सोनार सिग्नेचर भाषा',
  'lan.clsDesc': 'ध्वनिक परावर्तन मॉडेलवरून तयार केलेल्या प्रतिकृती प्रतिमा — कचरा, पायाभूत सुविधा, सागरी जीवन आणि सुरक्षा, वेगळ्या हाताळणीसह.',
  'lan.riskColon': 'जोखीम:',
  'lan.respKicker': 'प्रतिसाद इंटेलिजन्स',
  'lan.respTitle': 'अलर्ट ज्यांना आधीच आपला विभाग माहीत आहे',
  'lan.respDesc': 'रूटिंग नियम, एस्केलेशन मार्ग, उपकरण वाटप आणि मुदती डिटेक्शनची पुष्टी झाल्याबरोबर ठरतात.',
  'lan.ruleTable': 'नियम सारणी',
  'lan.liveRoutingEvent': 'लाइव्ह रूटिंग घटना',
  'lan.tagAiRouted': 'एआय रूटेड',
  'lan.tagRuleBased': 'नियम-आधारित नियुक्ती',
  'lan.tagVerification': 'प्रमाणीकरण आवश्यक',
  'lan.frameCaptured': '{code} फ्रेम कॅप्चर झाली',
  'lan.routeClassified': '{cls} · {conf}',
  'lan.routeRiskDeadline': '{risk} · मुदत {hours}h',
  'lan.routeEnvDept': 'सागरी पर्यावरण',
  'lan.active': 'सक्रिय',
  'lan.routeEnRoute': 'मार्गावर → {code} · {dept}',
  'lan.routeDispatch': '{detail} · प्रतिसाद {hours}h',
  'lan.liveKicker': 'लाइव्ह निरीक्षण',
  'lan.liveTitle': 'कंट्रोल रूम, तुमच्या ब्राउझरमध्येच',
  'lan.liveDesc': 'संपूर्ण निरीक्षण पृष्ठ — रडार स्वीप, येणारे डिटेक्शन, सिग्नल टेलिमेट्री आणि सिस्टम आरोग्य — प्रात्यक्षिकासाठी सिम्युलेटेड.',
  'lan.liveSweep': 'लाइव्ह स्वीप',
  'lan.openLive': 'लाइव्ह मॉनिटर उघडा',
  'lan.signal': 'सिग्नल ताकद',
  'lan.depth': 'स्कॅन खोली',
  'lan.objects': 'डिटेक्ट केलेल्या वस्तू',
  'lan.alerts': 'सक्रिय अलर्ट',
  'lan.gps': 'जीपीएस फिक्स',
  'lan.health': 'सिस्टम आरोग्य',
  'lan.aiCorePct': 'एआय कोअर {pct}%',
  'lan.healthSonar': 'सोनार ॲरे इष्टतम',
  'lan.healthGps': 'जीपीएस फिक्स लॉक',
  'lan.statsKicker': 'आकड्यांच्या दृष्टीने',
  'lan.statsTitle': 'परिचालन माप, लाइव्ह प्रदर्शित',
  'lan.statsDesc': 'सर्व आकडे ही सिम्युलेटेड डेमो टेलिमेट्री आहेत जी या बिल्डचे विश्लेषण व अहवाल पृष्ठ चालवतात.',
  'lan.enterPlatform': 'प्लॅटफॉर्ममध्ये प्रवेश करा',
  'lan.statDetections': 'या वर्षातील डिटेक्शन',
  'lan.statDebris': 'बरामद केलेला कचरा (टन)',
  'lan.statResponse': 'सरासरी प्रतिसाद (तास)',
  'lan.statCoverage': 'निरीक्षण कव्हरेज (km²)',
  'lan.footerPlatform': 'प्लॅटफॉर्म',
  'lan.copyright': '© {year} OCEONIX Systems',
  'lan.demoBuild': 'केवळ फ्रंटएंड प्रात्यक्षिक बिल्ड',
  'lan.versionLine': 'v2.4.1 · सोनार लिंक 600 kHz',
};