export const xEn: Record<string, string> = {
  'live.sub': "Continuous side-scan stream — events above the alert threshold are flagged live.",
  'live.stop': "Stop",
  'live.sonarLine': "600 kHz · TVG {tvg}dB · range {range}m",
  'live.statusActive': "SWEEP ACTIVE",
  'live.statusPaused': "PAUSED",
  'live.statusStandby': "STANDBY",
  'live.radarRange': "RANGE 120 m",
  'live.flagged': "Flagged",
  'live.incomingKt': "incoming stream",
  'live.incoming': "Incoming detections",
  'live.buffered': "BUFFERED",
  'live.awaiting': "Awaiting first acoustic return…",
  'live.conf': "{pct}% conf",
  'live.depthValue': "{d}m depth",
  'live.thresholdMet': "THRESHOLD MET",
  'live.monitoring': "MONITORING",
  'live.streamControlsKt': "stream controls",
  'live.telemetryControls': "Telemetry controls",
  'live.storage': "Storage",
  'live.routingKt': "thresholding",
  'live.routingRules': "Routing rules in effect",
  'live.monitor': "MONITOR",
  'live.recentRecords': "Recent persisted records",
};

export const xHi: Record<string, string> = {
  'live.sub': "निरंतर साइड-स्कैन स्ट्रीम — अलर्ट सीमा से ऊपर की घटनाओं को लाइव चिह्नित किया जाता है।",
  'live.stop': "रोकें",
  'live.sonarLine': "600 किलोहर्ट्ज़ · TVG {tvg}dB · रेंज {range}मी",
  'live.statusActive': "स्वीप सक्रिय",
  'live.statusPaused': "रोका गया",
  'live.statusStandby': "स्टैंडबाय",
  'live.radarRange': "रेंज 120 मीटर",
  'live.flagged': "चिह्नित",
  'live.incomingKt': "आगामी स्ट्रीम",
  'live.incoming': "आगामी डिटेक्शन",
  'live.buffered': "बफर में",
  'live.awaiting': "पहली ध्वनिक प्रतिध्वनि की प्रतीक्षा…",
  'live.conf': "{pct}% विश्वास",
  'live.depthValue': "{d}m गहराई",
  'live.thresholdMet': "सीमा पूर्ण हुई",
  'live.monitoring': "निगरानी",
  'live.streamControlsKt': "स्ट्रीम नियंत्रण",
  'live.telemetryControls': "टेलीमेट्री नियंत्रण",
  'live.storage': "स्टोरेज",
  'live.routingKt': "थ्रेशोल्डिंग",
  'live.routingRules': "लागू रूटिंग नियम",
  'live.monitor': "निगरानी",
  'live.recentRecords': "हालिया संग्रहित रिकॉर्ड",
};

export const xMr: Record<string, string> = {
  'live.sub': "सतत साइड-स्कॅन स्ट्रीम — अलर्ट मर्यादेपेक्षा वरील घटना लाइव्ह चिन्हांकित केल्या जातात।",
  'live.stop': "थांबवा",
  'live.sonarLine': "600 किलोहर्ट्झ · TVG {tvg}dB · रेंज {range}मी",
  'live.statusActive': "स्वीप सक्रिय",
  'live.statusPaused': "थांबवले",
  'live.statusStandby': "स्टँडबाय",
  'live.radarRange': "रेंज 120 मीटर",
  'live.flagged': "चिन्हांकित",
  'live.incomingKt': "येणारा स्ट्रीम",
  'live.incoming': "येणारे डिटेक्शन",
  'live.buffered': "बफरमध्ये",
  'live.awaiting': "पहिल्या ध्वनिक परतीची प्रतीक्षा…",
  'live.conf': "{pct}% आत्मविश्वास",
  'live.depthValue': "{d}m खोली",
  'live.thresholdMet': "मर्यादा गाठली",
  'live.monitoring': "निरीक्षण",
  'live.streamControlsKt': "स्ट्रीम नियंत्रणे",
  'live.telemetryControls': "टेलिमेट्री नियंत्रणे",
  'live.storage': "स्टोरेज",
  'live.routingKt': "थ्रेशोल्डिंग",
  'live.routingRules': "लागू असलेले रूटिंग नियम",
  'live.monitor': "निरीक्षण",
  'live.recentRecords': "अलीकडील संग्रहित नोंदी",
};