export const xEn: Record<string, string> = {
  'map.sub': 'GPS-tagged detections across surveyed grids — cluster size reflects detection volume at each position.',
  'map.ktLocal': 'local search',
  'map.clsLabel': 'Detection class',
  'map.riskLevel': 'Risk level',
  'map.timeWindow': 'Time window',
  'map.windowAll': 'All history',
  'map.windowHours': 'Last {n} hours',
  'map.windowDays': 'Last {n} days',
  'map.resultsTitle': '{clusters} clusters · {detections} detections',
  'map.empty': 'No detections match the current filters.',
  'map.viewCase': 'View case',
  'map.locationCluster': 'Location cluster',
  'map.bundled': '{n} detection{s} bundled at this position',
  'map.conf': '{pct}% conf',
  'map.legend.marine': 'Marine',
  'map.legend.grid': 'GRID 3° / ISOBATH 100·200m',
  'map.basemap': 'BASEMAP',
  'map.gisConnecting': 'Satellite feed connecting…',
};

export const xHi: Record<string, string> = {
  'map.sub': 'सर्वेक्षण किए गए ग्रिडों पर जीपीएस-टैग की गई डिटेक्शन — प्रत्येक स्थान पर क्लस्टर का आकार डिटेक्शन की मात्रा दर्शाता है।',
  'map.ktLocal': 'स्थानीय खोज',
  'map.clsLabel': 'डिटेक्शन क्लास',
  'map.riskLevel': 'जोखिम स्तर',
  'map.timeWindow': 'समय अवधि',
  'map.windowAll': 'पूरा इतिहास',
  'map.windowHours': 'पिछले {n} घंटे',
  'map.windowDays': 'पिछले {n} दिन',
  'map.resultsTitle': '{clusters} क्लस्टर · {detections} डिटेक्शन',
  'map.empty': 'वर्तमान फ़िल्टर से कोई डिटेक्शन मेल नहीं खाती।',
  'map.viewCase': 'मामला देखें',
  'map.locationCluster': 'स्थान क्लस्टर',
  'map.bundled': '{n} डिटेक्शन इस स्थान पर एकत्र हैं',
  'map.conf': '{pct}% विश्वास',
  'map.legend.marine': 'समुद्री',
  'map.legend.grid': 'ग्रिड 3° / समान गहराई रेखा 100·200मी',
  'map.basemap': 'बेसमैप',
  'map.gisConnecting': 'सैटेलाइट फ़ीड कनेक्ट हो रहा है…',
};

export const xMr: Record<string, string> = {
  'map.sub': 'सर्वेक्षण केलेल्या ग्रिडवर जीपीएस-टॅग केलेले डिटेक्शन — प्रत्येक ठिकाणी क्लस्टरचा आकार डिटेक्शनची संख्या दर्शवतो.',
  'map.ktLocal': 'स्थानिक शोध',
  'map.clsLabel': 'डिटेक्शन वर्ग',
  'map.riskLevel': 'जोखीम पातळी',
  'map.timeWindow': 'कालावधी',
  'map.windowAll': 'संपूर्ण इतिहास',
  'map.windowHours': 'गेले {n} तास',
  'map.windowDays': 'गेले {n} दिवस',
  'map.resultsTitle': '{clusters} क्लस्टर्स · {detections} डिटेक्शन',
  'map.empty': 'सध्याच्या फिल्टरशी कोणतेही डिटेक्शन जुळत नाही.',
  'map.viewCase': 'केस पहा',
  'map.locationCluster': 'स्थान क्लस्टर',
  'map.bundled': '{n} डिटेक्शन या ठिकाणी एकत्र आहेत',
  'map.conf': '{pct}% आत्मविश्वास',
  'map.legend.marine': 'सागरी',
  'map.legend.grid': 'ग्रिड 3° / समान खोली रेषा 100·200मी',
  'map.basemap': 'बेसमॅप',
  'map.gisConnecting': 'सॅटेलाइट फीड कनेक्ट होत आहे…',
};