export const xEn: Record<string, string> = {
  'my.deptSub': 'Command view for {dept}. Live workload, open cases and equipment drawn from the simulation ledger.',
  'my.alertConsole': 'Alert console',
  'my.openCases': 'Open cases',
  'my.operators': 'Operators',
  'my.ktActiveCases': 'active cases',
  'my.deptWorkload': 'Department workload',
  'my.allClear': 'All clear',
  'my.noCasesMatch': 'No cases match this view right now.',
  'my.confShort': 'conf',
  'my.assignedTo': 'assigned to {name}',
  'my.unassigned': 'unassigned',
  'my.accept': 'Accept',
  'my.review': 'Review',
  'my.roster': 'roster',
  'my.myTeam': 'My team',
  'my.field': 'field',
  'my.rosterHint': 'Operators accept alerts from the console and drive cases to a verified resolution.',
  'my.onSite': 'on-site',
  'my.equipAndAssets': 'Equipment & assets',
  'my.onCall': 'On-call status',
  'my.ready': 'READY',
  'my.quickAction': 'quick action',
  'my.assignOpenCase': 'Assign open case',
  'my.selectOpenCase': 'Select an open case\u2026',
  'my.operatorOpt': 'Operator\u2026',
  'my.operatorAssigned': 'Operator assigned',
  'my.assignedText': '{operator} now owns {alertId}.',
  'my.assign': 'Assign',
};

export const xHi: Record<string, string> = {
  'my.deptSub': '{dept} के लिए कमांड व्यू। लाइव कार्यभार, खुले मामले और सिमुलेशन लेजर से लिए गए उपकरण।',
  'my.alertConsole': 'अलर्ट कंसोल',
  'my.openCases': 'खुले मामले',
  'my.operators': 'ऑपरेटर',
  'my.ktActiveCases': 'सक्रिय मामले',
  'my.deptWorkload': 'विभाग का कार्यभार',
  'my.allClear': 'सब कुछ साफ़',
  'my.noCasesMatch': 'अभी इस व्यू से कोई मामला मेल नहीं खाता।',
  'my.confShort': 'विश्वास',
  'my.assignedTo': '{name} को नियुक्त',
  'my.unassigned': 'अनियुक्त',
  'my.accept': 'स्वीकारें',
  'my.review': 'समीक्षा करें',
  'my.roster': 'टीम सूची',
  'my.myTeam': 'मेरी टीम',
  'my.field': 'मैदान',
  'my.rosterHint': 'ऑपरेटर कंसोल से अलर्ट स्वीकारते हैं और मामलों को सत्यापित समाधान तक पहुँचाते हैं।',
  'my.onSite': 'ऑन-साइट',
  'my.equipAndAssets': 'उपकरण और संपत्तियाँ',
  'my.onCall': 'ऑन-कॉल स्थिति',
  'my.ready': 'तैयार',
  'my.quickAction': 'त्वरित कार्रवाई',
  'my.assignOpenCase': 'खुला मामला नियुक्त करें',
  'my.selectOpenCase': 'एक खुला मामला चुनें\u2026',
  'my.operatorOpt': 'ऑपरेटर\u2026',
  'my.operatorAssigned': 'ऑपरेटर नियुक्त किया गया',
  'my.assignedText': '{operator} अब {alertId} की ज़िम्मेदारी रखते हैं।',
  'my.assign': 'नियुक्त करें',
};

export const xMr: Record<string, string> = {
  'my.deptSub': '{dept} साठी कमांड व्यू. लाइव्ह कामाचा ताण, खुली प्रकरणे आणि सिम्युलेशन नोंदवहीतून घेतलेली उपकरणे.',
  'my.alertConsole': 'अलर्ट कन्सोल',
  'my.openCases': 'खुली प्रकरणे',
  'my.operators': 'ऑपरेटर',
  'my.ktActiveCases': 'सक्रिय प्रकरणे',
  'my.deptWorkload': 'विभागाचा कामाचा ताण',
  'my.allClear': 'सर्व काही ठीक',
  'my.noCasesMatch': 'सध्या या व्यूशी कोणतेही प्रकरण जुळत नाही.',
  'my.confShort': 'आत्मविश्वास',
  'my.assignedTo': '{name} यांना नेमले',
  'my.unassigned': 'अनियुक्त',
  'my.accept': 'स्वीकारा',
  'my.review': 'पुनरावलोकन',
  'my.roster': 'संघ यादी',
  'my.myTeam': 'माझी टीम',
  'my.field': 'मैदान',
  'my.rosterHint': 'ऑपरेटर कन्सोलवरून अलर्ट स्वीकारतात आणि प्रकरणे सत्यापित निकालापर्यंत नेतात.',
  'my.onSite': 'ऑन-साइट',
  'my.equipAndAssets': 'उपकरणे व संपत्ती',
  'my.onCall': 'ऑन-कॉल स्थिती',
  'my.ready': 'तयार',
  'my.quickAction': 'त्वरित कृती',
  'my.assignOpenCase': 'खुले प्रकरण नेमा',
  'my.selectOpenCase': 'खुले प्रकरण निवडा\u2026',
  'my.operatorOpt': 'ऑपरेटर\u2026',
  'my.operatorAssigned': 'ऑपरेटर नेमला',
  'my.assignedText': '{operator} आता {alertId} ची जबाबदारी सांभाळतात.',
  'my.assign': 'नेमा',
};