export const xEn: Record<string, string> = {
  'ngx.title': "Debris Navigation",
  'ngx.sub': "Enter the debris coordinates captured from a scan image to track its live position, distance from your vessel, and the route to site.",
  'ngx.manualTarget': "Manual target",
  'ngx.detOption': "{id} · {cls} · {coords}",
  'ngx.manualEntry': "— manual entry —",
  'ngx.pickFromDet': "Pick from detections",
  'ngx.latField': "Latitude (YN)",
  'ngx.latPh': "e.g. 18.6000",
  'ngx.lngField': "Longitude (YE)",
  'ngx.lngPh': "e.g. 72.9800",
  'ngx.lockTarget': "Lock target",
  'ngx.rangeNote': "Range {latMin}–{latMax}°N · {lonMin}–{lonMax}°E. Coordinates are read from the scanned sonar frame.",
  'ngx.targetLockKt': "target lock",
  'ngx.debrisCoords': "Debris coordinates",
  'ngx.lockedTarget': "Locked target",
  'ngx.myPosKt': "my position",
  'ngx.vesselOrigin': "Vessel origin",
  'ngx.locLive': "LIVE GPS",
  'ngx.locLocating': "LOCATING…",
  'ngx.locDenied': "GPS DENIED",
  'ngx.locFallback': "FALLBACK",
  'ngx.locSim': "SIMULATED",
  'ngx.trackingAuto': "TRACKING AUTO",
  'ngx.offlineMode': "OFFLINE MODE",
  'ngx.disableGps': "Disable GPS",
  'ngx.enableGps': "Enable live GPS",
  'ngx.originNote': "Set my position or enable live GPS. Defaults to Goa bank.",
  'ngx.transitKt': "transit plan",
  'ngx.routeEta': "Route & ETA",
  'ngx.vesselSpeed': "Vessel speed",
  'ngx.speedTrawl': "{kn} kn — trawl",
  'ngx.speedSurvey': "{kn} kn — survey",
  'ngx.speedResponse': "{kn} kn — response",
  'ngx.speedMax': "{kn} kn — max",
  'ngx.distToSite': "Distance to site",
  'ngx.bearing': "Bearing",
  'ngx.eta': "Estimated arrival",
  'ngx.gcRoute': "Great-circle route",
  'ngx.waypoints': "{count} waypoints",
  'ngx.noTarget': "Lock a target to compute the route.",
  'ngx.you': "YOU",
  'ngx.debris': "DEBRIS",
  'ngx.legendVessel': "Vessel (you)",
  'ngx.legendDebris': "Debris target",
  'ngx.legendRoute': "Route",
  'ngx.greatCircle': "GREAT-CIRCLE",
  'ngx.wptCount': "{count} WPT",
  'ngx.noTargetMono': "NO TARGET",
  'ngx.liveStatusKt': "live status",
  'ngx.navSummary': "Navigation summary",
  'ngx.originLine': "Origin · {label}",
  'ngx.toSite': "to site {km} / {nm}",
  'ngx.debrisLine': "Debris · {src}",
  'ngx.manualSrc': "manual",
  'ngx.etaAt': "ETA at {kn} kn → {eta}",
};

export const xHi: Record<string, string> = {
  'ngx.title': "मलबा नेविगेशन",
  'ngx.sub': "स्कैन छवि से पकड़े गए मलबे के निर्देशांक दर्ज करें ताकि उसकी लाइव स्थिति, आपके जहाज़ से दूरी और स्थल तक का मार्ग ट्रैक किया जा सके।",
  'ngx.manualTarget': "मैनुअल लक्ष्य",
  'ngx.detOption': "{id} · {cls} · {coords}",
  'ngx.manualEntry': "— मैनुअल प्रविष्टि —",
  'ngx.pickFromDet': "डिटेक्शन से चुनें",
  'ngx.latField': "अक्षांश (YN)",
  'ngx.latPh': "जैसे 18.6000",
  'ngx.lngField': "देशांतर (YE)",
  'ngx.lngPh': "जैसे 72.9800",
  'ngx.lockTarget': "लक्ष्य लॉक करें",
  'ngx.rangeNote': "सीमा {latMin}–{latMax}°N · {lonMin}–{lonMax}°E। निर्देशांक स्कैन की गई सोनार फ़्रेम से पढ़े जाते हैं।",
  'ngx.targetLockKt': "लक्ष्य लॉक",
  'ngx.debrisCoords': "मलबा निर्देशांक",
  'ngx.lockedTarget': "लॉक किया गया लक्ष्य",
  'ngx.myPosKt': "मेरी स्थिति",
  'ngx.vesselOrigin': "जहाज़ का मूल स्थान",
  'ngx.locLive': "लाइव जीपीएस",
  'ngx.locLocating': "पता लगाया जा रहा है…",
  'ngx.locDenied': "जीपीएस अस्वीकृत",
  'ngx.locFallback': "फ़ॉलबैक",
  'ngx.locSim': "सिम्युलेटेड",
  'ngx.trackingAuto': "स्वचालित ट्रैकिंग",
  'ngx.offlineMode': "ऑफ़लाइन मोड",
  'ngx.disableGps': "जीपीएस अक्षम करें",
  'ngx.enableGps': "लाइव जीपीएस चालू करें",
  'ngx.originNote': "अपनी स्थिति सेट करें या लाइव जीपीएस चालू करें। डिफ़ॉल्ट गोवा बैंक।",
  'ngx.transitKt': "पारगमन योजना",
  'ngx.routeEta': "मार्ग और अनुमानित आगमन",
  'ngx.vesselSpeed': "जहाज़ की गति",
  'ngx.speedTrawl': "{kn} kn — ट्रॉल",
  'ngx.speedSurvey': "{kn} kn — सर्वेक्षण",
  'ngx.speedResponse': "{kn} kn — प्रतिक्रिया",
  'ngx.speedMax': "{kn} kn — अधिकतम",
  'ngx.distToSite': "स्थल तक दूरी",
  'ngx.bearing': "दिगंश",
  'ngx.eta': "अनुमानित आगमन",
  'ngx.gcRoute': "ग्रेट-सर्कल मार्ग",
  'ngx.waypoints': "{count} वेपॉइंट",
  'ngx.noTarget': "मार्ग की गणना के लिए कोई लक्ष्य लॉक करें।",
  'ngx.you': "आप",
  'ngx.debris': "मलबा",
  'ngx.legendVessel': "जहाज़ (आप)",
  'ngx.legendDebris': "मलबा लक्ष्य",
  'ngx.legendRoute': "मार्ग",
  'ngx.greatCircle': "ग्रेट-सर्कल",
  'ngx.wptCount': "{count} WPT",
  'ngx.noTargetMono': "कोई लक्ष्य नहीं",
  'ngx.liveStatusKt': "लाइव स्थिति",
  'ngx.navSummary': "नेविगेशन सारांश",
  'ngx.originLine': "मूल स्थान · {label}",
  'ngx.toSite': "स्थल तक {km} / {nm}",
  'ngx.debrisLine': "मलबा · {src}",
  'ngx.manualSrc': "मैनुअल",
  'ngx.etaAt': "{kn} kn पर अनुमानित आगमन → {eta}",
};

export const xMr: Record<string, string> = {
  'ngx.title': "कचरा नेव्हिगेशन",
  'ngx.sub': "स्कॅन प्रतिमेतून पकडलेले कचरा निर्देशांक प्रविष्ट करा जेणेकरून त्याचे लाइव्ह स्थान, तुमच्या जहाजापासूनचे अंतर आणि ठिकाणापर्यंतचा मार्ग ट्रॅक करता येईल.",
  'ngx.manualTarget': "मॅन्युअल लक्ष्य",
  'ngx.detOption': "{id} · {cls} · {coords}",
  'ngx.manualEntry': "— मॅन्युअल नोंद —",
  'ngx.pickFromDet': "डिटेक्शनमधून निवडा",
  'ngx.latField': "अक्षांश (YN)",
  'ngx.latPh': "उदा. 18.6000",
  'ngx.lngField': "रेखांश (YE)",
  'ngx.lngPh': "उदा. 72.9800",
  'ngx.lockTarget': "लक्ष्य लॉक करा",
  'ngx.rangeNote': "श्रेणी {latMin}–{latMax}°N · {lonMin}–{lonMax}°E. निर्देशांक स्कॅन केलेल्या सोनार फ्रेममधून वाचले जातात.",
  'ngx.targetLockKt': "लक्ष्य लॉक",
  'ngx.debrisCoords': "कचरा निर्देशांक",
  'ngx.lockedTarget': "लॉक केलेले लक्ष्य",
  'ngx.myPosKt': "माझे स्थान",
  'ngx.vesselOrigin': "जहाजाचे ठिकाण",
  'ngx.locLive': "लाइव्ह जीपीएस",
  'ngx.locLocating': "स्थान शोधत आहोत…",
  'ngx.locDenied': "जीपीएस नाकारले",
  'ngx.locFallback': "फॉलबॅक",
  'ngx.locSim': "सिम्युलेटेड",
  'ngx.trackingAuto': "स्वयंचलित ट्रॅकिंग",
  'ngx.offlineMode': "ऑफलाइन मोड",
  'ngx.disableGps': "जीपीएस बंद करा",
  'ngx.enableGps': "लाइव्ह जीपीएस चालू करा",
  'ngx.originNote': "तुमचे स्थान सेट करा किंवा लाइव्ह जीपीएस चालू करा. डीफॉल्ट गोवा बँक.",
  'ngx.transitKt': "संक्रमण योजना",
  'ngx.routeEta': "मार्ग आणि अंदाजित आगमन",
  'ngx.vesselSpeed': "जहाजाचा वेग",
  'ngx.speedTrawl': "{kn} kn — ट्रॉल",
  'ngx.speedSurvey': "{kn} kn — सर्वेक्षण",
  'ngx.speedResponse': "{kn} kn — प्रतिसाद",
  'ngx.speedMax': "{kn} kn — कमाल",
  'ngx.distToSite': "ठिकाणापर्यंतचे अंतर",
  'ngx.bearing': "दिगंश",
  'ngx.eta': "अंदाजित आगमन",
  'ngx.gcRoute': "ग्रेट-सर्कल मार्ग",
  'ngx.waypoints': "{count} वेपॉइंट्स",
  'ngx.noTarget': "मार्ग काढण्यासाठी लक्ष्य लॉक करा.",
  'ngx.you': "तुम्ही",
  'ngx.debris': "कचरा",
  'ngx.legendVessel': "जहाज (तुम्ही)",
  'ngx.legendDebris': "कचरा लक्ष्य",
  'ngx.legendRoute': "मार्ग",
  'ngx.greatCircle': "ग्रेट-सर्कल",
  'ngx.wptCount': "{count} WPT",
  'ngx.noTargetMono': "लक्ष्य नाही",
  'ngx.liveStatusKt': "लाइव्ह स्थिती",
  'ngx.navSummary': "नेव्हिगेशन सारांश",
  'ngx.originLine': "मूळ स्थान · {label}",
  'ngx.toSite': "ठिकाणापर्यंत {km} / {nm}",
  'ngx.debrisLine': "कचरा · {src}",
  'ngx.manualSrc': "मॅन्युअल",
  'ngx.etaAt': "{kn} kn वर अंदाजित आगमन → {eta}",
};