export const xEn: Record<string, string> = {
  'rpt.sub': 'Assemble cohort reports from the survey ledger and export them as CSV, JSON or PDF.',
  'rpt.generate': 'Generate report',
  'rpt.snapshot': 'Ledger snapshot',
  'rpt.ktSnapshot': 'ledger snapshot',
  'rpt.parameters': 'Parameters',
  'rpt.ktBuilder': 'report builder',
  'rpt.timeWindow': 'Time window',
  'rpt.deptScope': 'Department scope',
  'rpt.allDepts': 'All departments',
  'rpt.generateNow': 'Generate now',
  'rpt.builderHint': 'Report includes stats, class table and findings. Exported as CSV, JSON or PDF.',
  'rpt.generatedReports': 'Generated reports',
  'rpt.ktHistory': 'history',
  'rpt.emptyTitle': 'No reports yet',
  'rpt.emptyDesc': 'Reports you generate appear here.',
  'rpt.ktReport': 'report · {window}',
  'rpt.win24': 'Last 24h',
  'rpt.win7': 'Last 7 days',
  'rpt.win30': 'Last 30 days',
  'rpt.win90': 'Last 90 days',
  'rpt.cohortTitle': 'Cohort survey report',
  'rpt.statGenerated': 'Generated',
  'rpt.statWindow': 'Window',
  'rpt.statDetections': 'Detections',
  'rpt.statOpenAlerts': 'Open alerts',
  'rpt.statCritical': 'Critical risk',
  'rpt.statHigh': 'High risk',
  'rpt.statTotal': 'Total detections',
  'rpt.statDepartments': 'Departments',
  'rpt.col.objectClass': 'Object class',
  'rpt.col.count': 'Count',
  'rpt.col.avgConf': 'Avg conf',
  'rpt.col.topRegion': 'Top region',
  'rpt.bodyIntro': 'OCEONIX Underwater Intelligence — automated cohort summary. This document is generated from the frontend simulation ledger, not a real survey.',
  'rpt.bodyObjectDist': 'OBJECT DISTRIBUTION — {n} object(s) classified across {c} target classes.',
  'rpt.bodyRiskPosture': 'RISK POSTURE — {crit} critical / {high} high / {med} medium / {low} low.',
  'rpt.bodyResponseState': 'RESPONSE STATE — {open} open alert(s), {resolved} case(s) closed and verified.',
  'rpt.bodyClassFindings': 'CLASS FINDINGS — top object class is {cls} with {n} hit(s).',
  'rpt.toastGen': 'Report generated',
  'rpt.toastGenText': '{id} ready for review.',
  'rpt.toastExport': 'Report exported',
  'rpt.toastExportText': '{file} written.',
  'rpt.toastExportError': 'Could not export {file}.',
  'rpt.pdfId': 'ID: {id}',
  'rpt.pdfWindow': 'Window: {window}',
  'rpt.pdfDepartment': 'Department: {dept}',
  'rpt.pdfGenerated': 'Generated: {date}',
  'rpt.pdfKeyMetrics': 'Key metrics',
  'rpt.pdfFindings': 'Findings',
  'rpt.pdfDataTable': 'Data table',
};

export const xHi: Record<string, string> = {
  'rpt.sub': 'सर्वेक्षण लेजर से कोहॉर्ट रिपोर्ट तैयार करें और उन्हें CSV, JSON या PDF के रूप में निर्यात करें।',
  'rpt.generate': 'रिपोर्ट बनाएँ',
  'rpt.snapshot': 'लेजर स्नैपशॉट',
  'rpt.ktSnapshot': 'लेजर स्नैपशॉट',
  'rpt.parameters': 'पैरामीटर',
  'rpt.ktBuilder': 'रिपोर्ट बिल्डर',
  'rpt.timeWindow': 'समय अवधि',
  'rpt.deptScope': 'विभाग दायरा',
  'rpt.allDepts': 'सभी विभाग',
  'rpt.generateNow': 'अभी बनाएँ',
  'rpt.builderHint': 'रिपोर्ट में आँकड़े, क्लास तालिका और निष्कर्ष शामिल हैं। CSV, JSON या PDF के रूप में निर्यात करें।',
  'rpt.generatedReports': 'बनाई गई रिपोर्ट',
  'rpt.ktHistory': 'इतिहास',
  'rpt.emptyTitle': 'अभी कोई रिपोर्ट नहीं',
  'rpt.emptyDesc': 'आपके द्वारा बनाई गई रिपोर्ट यहाँ दिखाई देंगी।',
  'rpt.ktReport': 'रिपोर्ट · {window}',
  'rpt.win24': 'पिछले 24 घंटे',
  'rpt.win7': 'पिछले 7 दिन',
  'rpt.win30': 'पिछले 30 दिन',
  'rpt.win90': 'पिछले 90 दिन',
  'rpt.cohortTitle': 'कोहॉर्ट सर्वेक्षण रिपोर्ट',
  'rpt.statGenerated': 'जनरेट किया गया',
  'rpt.statWindow': 'समय अवधि',
  'rpt.statDetections': 'डिटेक्शन',
  'rpt.statOpenAlerts': 'खुले अलर्ट',
  'rpt.statCritical': 'गंभीर जोखिम',
  'rpt.statHigh': 'उच्च जोखिम',
  'rpt.statTotal': 'कुल डिटेक्शन',
  'rpt.statDepartments': 'विभाग',
  'rpt.col.objectClass': 'ऑब्जेक्ट क्लास',
  'rpt.col.count': 'गिनती',
  'rpt.col.avgConf': 'औसत विश्वास',
  'rpt.col.topRegion': 'शीर्ष क्षेत्र',
  'rpt.bodyIntro': 'OCEONIX अंडरवाटर इंटेलिजेंस — स्वचालित कोहॉर्ट सारांश। यह दस्तावेज़ फ्रंटएंड सिमुलेशन लेजर से तैयार किया गया है, यह वास्तविक सर्वेक्षण नहीं है।',
  'rpt.bodyObjectDist': 'ऑब्जेक्ट वितरण — {n} वस्तु(एँ) {c} लक्ष्य क्लास में वर्गीकृत।',
  'rpt.bodyRiskPosture': 'जोखिम स्थिति — {crit} गंभीर / {high} उच्च / {med} मध्यम / {low} निम्न।',
  'rpt.bodyResponseState': 'प्रतिक्रिया स्थिति — {open} खुले अलर्ट, {resolved} मामले बंद और सत्यापित।',
  'rpt.bodyClassFindings': 'क्लास निष्कर्ष — शीर्ष ऑब्जेक्ट क्लास {cls} है, जिसमें {n} हिट हैं।',
  'rpt.toastGen': 'रिपोर्ट बनाई गई',
  'rpt.toastGenText': '{id} समीक्षा के लिए तैयार है।',
  'rpt.toastExport': 'रिपोर्ट निर्यात हुई',
  'rpt.toastExportText': '{file} लिखी गई।',
  'rpt.toastExportError': '{file} निर्यात नहीं हो सकी।',
  'rpt.pdfId': 'आईडी: {id}',
  'rpt.pdfWindow': 'समय अवधि: {window}',
  'rpt.pdfDepartment': 'विभाग: {dept}',
  'rpt.pdfGenerated': 'जनरेट किया गया: {date}',
  'rpt.pdfKeyMetrics': 'मुख्य मीट्रिक्स',
  'rpt.pdfFindings': 'निष्कर्ष',
  'rpt.pdfDataTable': 'डेटा तालिका',
};

export const xMr: Record<string, string> = {
  'rpt.sub': 'सर्वेक्षण खातेवहीतून कोहॉर्ट अहवाल तयार करा आणि ते CSV, JSON किंवा PDF स्वरूपात निर्यात करा.',
  'rpt.generate': 'अहवाल तयार करा',
  'rpt.snapshot': 'खातेवही स्नॅपशॉट',
  'rpt.ktSnapshot': 'खातेवही स्नॅपशॉट',
  'rpt.parameters': 'पॅरामीटर्स',
  'rpt.ktBuilder': 'अहवाल बिल्डर',
  'rpt.timeWindow': 'कालावधी',
  'rpt.deptScope': 'विभाग व्याप्ती',
  'rpt.allDepts': 'सर्व विभाग',
  'rpt.generateNow': 'आता तयार करा',
  'rpt.builderHint': 'अहवालात आकडेवारी, वर्ग सारणी आणि निष्कर्ष समाविष्ट आहेत. CSV, JSON किंवा PDF स्वरूपात निर्यात करा.',
  'rpt.generatedReports': 'तयार केलेले अहवाल',
  'rpt.ktHistory': 'इतिहास',
  'rpt.emptyTitle': 'अद्याप अहवाल नाहीत',
  'rpt.emptyDesc': 'तुम्ही तयार केलेले अहवाल येथे दिसतील.',
  'rpt.ktReport': 'अहवाल · {window}',
  'rpt.win24': 'मागील २४ तास',
  'rpt.win7': 'मागील ७ दिवस',
  'rpt.win30': 'मागील ३० दिवस',
  'rpt.win90': 'मागील ९० दिवस',
  'rpt.cohortTitle': 'कोहॉर्ट सर्वेक्षण अहवाल',
  'rpt.statGenerated': 'तयार केले',
  'rpt.statWindow': 'कालावधी',
  'rpt.statDetections': 'डिटेक्शन',
  'rpt.statOpenAlerts': 'खुले अलर्ट',
  'rpt.statCritical': 'गंभीर जोखीम',
  'rpt.statHigh': 'उच्च जोखीम',
  'rpt.statTotal': 'एकूण डिटेक्शन',
  'rpt.statDepartments': 'विभाग',
  'rpt.col.objectClass': 'वस्तू वर्ग',
  'rpt.col.count': 'संख्या',
  'rpt.col.avgConf': 'सरासरी आत्मविश्वास',
  'rpt.col.topRegion': 'अव्वल प्रदेश',
  'rpt.bodyIntro': 'OCEONIX अंडरवॉटर इंटेलिजन्स — स्वयंचलित कोहॉर्ट सारांश. हा दस्तऐवज फ्रंटएंड सिम्युलेशन खातेवहीतून तयार केला गेला आहे, वास्तविक सर्वेक्षण नाही.',
  'rpt.bodyObjectDist': 'वस्तू वितरण — {n} वस्तू {c} लक्ष्य वर्गांमध्ये वर्गीकृत.',
  'rpt.bodyRiskPosture': 'जोखीम स्थिती — {crit} गंभीर / {high} उच्च / {med} मध्यम / {low} कमी.',
  'rpt.bodyResponseState': 'प्रतिसाद स्थिती — {open} खुले अलर्ट, {resolved} प्रकरणे बंद आणि सत्यापित.',
  'rpt.bodyClassFindings': 'वर्ग निष्कर्ष — अव्वल वस्तू वर्ग {cls} आहे, ज्यात {n} हिट आहेत.',
  'rpt.toastGen': 'अहवाल तयार झाला',
  'rpt.toastGenText': '{id} पुनरावलोकनासाठी तयार आहे.',
  'rpt.toastExport': 'अहवाल निर्यात झाला',
  'rpt.toastExportText': '{file} लिहिले.',
  'rpt.toastExportError': '{file} निर्यात करता आली नाही.',
  'rpt.pdfId': 'आयडी: {id}',
  'rpt.pdfWindow': 'कालावधी: {window}',
  'rpt.pdfDepartment': 'विभाग: {dept}',
  'rpt.pdfGenerated': 'तयार केले: {date}',
  'rpt.pdfKeyMetrics': 'मुख्य मेट्रिक्स',
  'rpt.pdfFindings': 'निष्कर्ष',
  'rpt.pdfDataTable': 'डेटा सारणी',
};