export const xEn: Record<string, string> = {
  'set.headSub': "Detection thresholds, sonar calibration, routing rules, notifications and demo mode live here.",
  'set.saveChanges': "Save changes",
  'set.savedNote': "Changes persisted to this browser.",
  'set.resetDefaults': "Reset defaults",
  'set.resetTitle': "Settings reset",
  'set.resetNote': "Defaults restored.",
  'set.appearanceKt': "appearance",
  'set.themeLang': "Theme & language",
  'set.prefNote': "Language & theme preferences are stored on this device.",
  'set.detectionKt': "detection engine",
  'set.classAlerts': "Classification & alerts",
  'set.confThreshold': "Detection confidence threshold",
  'set.alertClasses': "Alert-generating debris classes",
  'set.classesHint': "Classes outside this list are logged and monitored, but do not raise alerts.",
  'set.demoMode': "Demo mode",
  'set.demoDesc': "Simulated responses toggled live from the store.",
  'set.sensorKt': "sensor head",
  'set.sonarCal': "Sonar calibration",
  'set.sonarHint': "Calibration applies to the simulated sweep profile shown across the product.",
  'set.beamWidth': "Beam width",
  'set.routingKt': "routing policy",
  'set.riskWindows': "Risk thresholds & response windows",
  'set.riskRow': "{risk} risk · score ≥ {score}",
  'set.responseWindow': "{hours}h window",
  'set.riskHint': "Scores override the base risk while response windows feed the deadline clock on every alert.",
  'set.notificationsKt': "notifications",
  'set.notifyPrefs': "Notification preferences",
  'set.critOnly': "Critical alerts only",
  'set.sysStatus': "System status",
  'set.emailDigest': "Email digest",
  'set.browserPush': "Browser push",
  'set.audioAlert': "Audio alert",
  'set.dailySummary': "Daily summary",
  'set.accountKt': "account & data",
  'set.demoUtility': "Demo utility",
  'set.replayTour': "Replay product tour",
  'set.tourDesc': "Walk through the routing, detection, monitoring and department workflow again.",
  'set.clearData': "Clear all data",
  'set.clearDesc': "Empty the ledger — detections, alerts and notifications in this browser.",
  'set.clearBtn': "Clear data",
  'set.dataCleared': "Data cleared",
  'set.ledgerEmptied': "Ledger emptied.",
  'set.datasetNote': "Simulated dataset · no external calls",
  'set.versionBadge': "OCEONIX v1.0",
};

export const xHi: Record<string, string> = {
  'set.headSub': "डिटेक्शन थ्रेशोल्ड, सोनार कैलिब्रेशन, रूटिंग नियम, सूचनाएँ और डेमो मोड यहाँ रहते हैं।",
  'set.saveChanges': "बदलाव सहेजें",
  'set.savedNote': "बदलाव इस ब्राउज़र में सहेज लिए गए हैं।",
  'set.resetDefaults': "डिफ़ॉल्ट रीसेट करें",
  'set.resetTitle': "सेटिंग्स रीसेट हुईं",
  'set.resetNote': "डिफ़ॉल्ट मान बहाल कर दिए गए हैं।",
  'set.appearanceKt': "दृश्य",
  'set.themeLang': "थीम और भाषा",
  'set.prefNote': "भाषा और थीम की पसंद इस डिवाइस पर संग्रहीत की जाती है।",
  'set.detectionKt': "डिटेक्शन इंजन",
  'set.classAlerts': "वर्गीकरण और अलर्ट",
  'set.confThreshold': "डिटेक्शन विश्वास सीमा",
  'set.alertClasses': "अलर्ट उत्पन्न करने वाले कचरा वर्ग",
  'set.classesHint': "इस सूची से बाहर के वर्गों को लॉग किया जाता है और उन पर नज़र रखी जाती है, पर अलर्ट नहीं उठाए जाते।",
  'set.demoMode': "डेमो मोड",
  'set.demoDesc': "स्टोर से लाइव टॉगल किए गए सिम्युलेटेड प्रतिक्रियाएँ।",
  'set.sensorKt': "सेंसर हेड",
  'set.sonarCal': "सोनार कैलिब्रेशन",
  'set.sonarHint': "कैलिब्रेशन पूरे उत्पाद में दिखाए गए सिम्युलेटेड स्वीप प्रोफ़ाइल पर लागू होता है।",
  'set.beamWidth': "बीम चौड़ाई",
  'set.routingKt': "रूटिंग नीति",
  'set.riskWindows': "जोखिम सीमाएँ और प्रतिक्रिया समय-सीमाएँ",
  'set.riskRow': "{risk} जोखिम · स्कोर ≥ {score}",
  'set.responseWindow': "{hours} घंटे की समय-सीमा",
  'set.riskHint': "स्कोर आधार जोखिम को ओवरराइड करते हैं, जबकि प्रतिक्रिया समय-सीमाएँ हर अलर्ट पर मुद्दत की घड़ी चलाती हैं।",
  'set.notificationsKt': "सूचनाएँ",
  'set.notifyPrefs': "सूचना प्राथमिकताएँ",
  'set.critOnly': "केवल गंभीर अलर्ट",
  'set.sysStatus': "सिस्टम स्थिति",
  'set.emailDigest': "ईमेल डाइजेस्ट",
  'set.browserPush': "ब्राउज़र पुश",
  'set.audioAlert': "ऑडियो अलर्ट",
  'set.dailySummary': "दैनिक सारांश",
  'set.accountKt': "खाता और डेटा",
  'set.demoUtility': "डेमो उपकरण",
  'set.replayTour': "प्रोडक्ट टूर फिर से चलाएँ",
  'set.tourDesc': "रूटिंग, डिटेक्शन, निगरानी और विभाग वर्कफ़्लो फिर से देखें।",
  'set.clearData': "सभी डेटा साफ़ करें",
  'set.clearDesc': "बही-खाता खाली करें — इस ब्राउज़र में डिटेक्शन, अलर्ट और सूचनाएँ।",
  'set.clearBtn': "डेटा साफ़ करें",
  'set.dataCleared': "डेटा साफ़ हो गया",
  'set.ledgerEmptied': "बही-खाता खाली कर दिया गया।",
  'set.datasetNote': "सिम्युलेटेड डेटासेट · कोई बाहरी कॉल नहीं",
  'set.versionBadge': "OCEONIX v1.0",
};

export const xMr: Record<string, string> = {
  'set.headSub': "डिटेक्शन थ्रेशोल्ड, सोनार कॅलिब्रेशन, रूटिंग नियम, सूचना आणि डेमो मोड येथे राहतात.",
  'set.saveChanges': "बदल जतन करा",
  'set.savedNote': "बदल या ब्राउझरमध्ये जतन केले गेले.",
  'set.resetDefaults': "डीफॉल्ट रीसेट करा",
  'set.resetTitle': "सेटिंग्ज रीसेट झाल्या",
  'set.resetNote': "डीफॉल्ट मूल्ये पुनर्संचयित केली गेली.",
  'set.appearanceKt': "स्वरूप",
  'set.themeLang': "थीम आणि भाषा",
  'set.prefNote': "भाषा आणि थीमची प्राधान्ये या डिव्हाइसवर संग्रहित केली जातात.",
  'set.detectionKt': "डिटेक्शन इंजिन",
  'set.classAlerts': "वर्गीकरण आणि अलर्ट",
  'set.confThreshold': "डिटेक्शन आत्मविश्वास मर्यादा",
  'set.alertClasses': "अलर्ट निर्माण करणारे कचरा वर्ग",
  'set.classesHint': "या यादीबाहेरील वर्गांची नोंद व देखरेख केली जाते, पण अलर्ट उठवले जात नाहीत.",
  'set.demoMode': "डेमो मोड",
  'set.demoDesc': "स्टोअरमधून लाइव्ह टॉगल केलेल्या सिम्युलेटेड प्रतिसाद.",
  'set.sensorKt': "सेन्सर हेड",
  'set.sonarCal': "सोनार कॅलिब्रेशन",
  'set.sonarHint': "कॅलिब्रेशन संपूर्ण उत्पादनामध्ये दर्शविल्या जाणाऱ्या सिम्युलेटेड स्वीप प्रोफाइलला लागू होते.",
  'set.beamWidth': "बीम रुंदी",
  'set.routingKt': "रूटिंग धोरण",
  'set.riskWindows': "जोखीम मर्यादा आणि प्रतिसाद कालमर्यादा",
  'set.riskRow': "{risk} जोखीम · स्कोअर ≥ {score}",
  'set.responseWindow': "{hours} तासांची कालमर्यादा",
  'set.riskHint': "स्कोअर मूळ जोखीम ओव्हरराइड करतात, तर प्रतिसाद कालमर्यादा प्रत्येक अलर्टवरील मुदत घड्याळ चालवतात.",
  'set.notificationsKt': "सूचना",
  'set.notifyPrefs': "सूचना प्राधान्ये",
  'set.critOnly': "केवळ गंभीर अलर्ट",
  'set.sysStatus': "सिस्टम स्थिती",
  'set.emailDigest': "ईमेल डायजेस्ट",
  'set.browserPush': "ब्राउझर पुश",
  'set.audioAlert': "ऑडिओ अलर्ट",
  'set.dailySummary': "दैनिक सारांश",
  'set.accountKt': "खाते आणि डेटा",
  'set.demoUtility': "डेमो उपयुक्तता",
  'set.replayTour': "प्रॉडक्ट टूर पुन्हा सुरू करा",
  'set.tourDesc': "रूटिंग, डिटेक्शन, निरीक्षण आणि विभाग वर्कफ्लो पुन्हा पाहा.",
  'set.clearData': "सर्व डेटा साफ करा",
  'set.clearDesc': "खातेबही रिकामी करा — या ब्राउझरमधील डिटेक्शन, अलर्ट आणि सूचना.",
  'set.clearBtn': "डेटा साफ करा",
  'set.dataCleared': "डेटा साफ झाला",
  'set.ledgerEmptied': "खातेबही रिकामी केली.",
  'set.datasetNote': "सिम्युलेटेड डेटासेट · कोणतेही बाह्य कॉल नाहीत",
  'set.versionBadge': "OCEONIX v1.0",
};