export const xEn: Record<string, string> = {
  'shl.deptEnv': "Marine Environmental",
  'shl.deptRec': "Recovery & Response",
  'shl.deptChipId': "DEPT {id} · OPERATOR 01",
  'shl.navAria': "Primary",
  'shl.menuAria': "Open navigation",
  'shl.breadOps': "OPS",
  'shl.system': "SYSTEM NOMINAL",
  'shl.sonarLink': "SONAR LINK 600 kHz",
  'shl.purge': "Purge",
  'shl.notif0': "No notifications",
  'shl.footBrand': "OCEONIX · Undersea Intelligence Platform",
  'shl.footLocal': "Local session — detections recorded from your uploads",
  'shl.time.justNow': "just now",
  'shl.time.m': "{m}m ago",
  'shl.time.h': "{h}h ago",
  'shl.time.d': "{d}d ago",
};

export const xHi: Record<string, string> = {
  'shl.deptEnv': "समुद्री पर्यावरण",
  'shl.deptRec': "बचाव व प्रतिक्रिया",
  'shl.deptChipId': "DEPT {id} · ऑपरेटर 01",
  'shl.navAria': "प्राथमिक",
  'shl.menuAria': "नेविगेशन खोलें",
  'shl.breadOps': "संचालन",
  'shl.system': "सिस्टम नॉमिनल",
  'shl.sonarLink': "सोनार लिंक 600 kHz",
  'shl.purge': "साफ़ करें",
  'shl.notif0': "कोई सूचना नहीं",
  'shl.footBrand': "OCEONIX · अंडरसी इंटेलिजेंस प्लेटफ़ॉर्म",
  'shl.footLocal': "लोकल सत्र — आपके अपलोड से दर्ज डिटेक्शन",
  'shl.time.justNow': "अभी",
  'shl.time.m': "{m} मिनट पहले",
  'shl.time.h': "{h} घंटे पहले",
  'shl.time.d': "{d} दिन पहले",
};

export const xMr: Record<string, string> = {
  'shl.deptEnv': "सागरी पर्यावरण",
  'shl.deptRec': "बचाव व प्रतिसाद",
  'shl.deptChipId': "DEPT {id} · ऑपरेटर 01",
  'shl.navAria': "प्राथमिक",
  'shl.menuAria': "नेव्हिगेशन उघडा",
  'shl.breadOps': "संचालन",
  'shl.system': "सिस्टम नॉमिनल",
  'shl.sonarLink': "सोनार लिंक 600 kHz",
  'shl.purge': "साफ करा",
  'shl.notif0': "सूचना नाहीत",
  'shl.footBrand': "OCEONIX · अंडरसी इंटेलिजन्स प्लॅटफॉर्म",
  'shl.footLocal': "लोकल सत्र — तुमच्या अपलोडमधून नोंदवलेले डिटेक्शन",
  'shl.time.justNow': "आत्ताच",
  'shl.time.m': "{m} मिनिटांपूर्वी",
  'shl.time.h': "{h} तासांपूर्वी",
  'shl.time.d': "{d} दिवसांपूर्वी",
};