export const xEn: Record<string, string> = {
  'stx.loginRejected': 'Login rejected',
  'stx.loginRejectedText': 'This account belongs to {dept}.',
  'stx.invalidCredentials': 'Invalid credentials',
  'stx.invalidCredentialsText': 'Password does not match the registered account.',
  'stx.authSuccess': 'Authentication successful',
  'stx.authSuccessText': 'Session established. Welcome back, operator.',
  'stx.allFieldsRequired': 'All fields are required.',
  'stx.invalidEmail': 'Enter a valid email address.',
  'stx.passwordTooShort': 'Password must be at least 6 characters.',
  'stx.usernameTaken': 'That username is already registered.',
  'stx.emailExists': 'An account with that email already exists.',
  'stx.accountCreated': 'Account created',
  'stx.accountCreatedText': '{name} registered under {dept}.',
  'stx.sessionEnded': 'Session ended',
  'stx.sessionEndedText': 'You have been logged out of the operations portal.',
  'stx.marineLifeObserved': 'Marine life observed',
  'stx.marineLifeObservedBody': 'Manta ray signature logged. Monitoring only — no removal action.',
  'stx.marineObservation': 'Marine life observation',
  'stx.marineObservationText': 'Manta ray logged to monitoring ledger. No alert raised.',
  'stx.viewAlert': 'View Alert',
  'stx.view': 'View',
  'stx.taskAssigned': 'Task assigned',
  'stx.taskAssignedNote': '{operator} assigned to {target}.',
  'stx.taskAssignedText': '{id} routed to {target} → {operator}.',
  'stx.settingsSaved': 'Settings saved',
  'stx.settingsSavedText': 'Configuration written to demo state and persisted locally.',
  'stx.settingsReset': 'Settings reset',
  'stx.settingsResetText': 'Configuration restored to defaults.',
  'stx.tlDetection': 'Sonar detection recorded',
  'stx.tlDetectionDesc': 'Side-scan frame captured and ingested at full resolution.',
  'stx.tlAnalysis': 'Marine intelligence analysis',
  'stx.tlAnalysisDesc': '{desc} Confidence {pct}%.',
  'stx.tlRouted': 'Alert routed',
  'stx.tlRoutedDesc': 'Routed to {dept} by routing rule.',
  'stx.emergencyNotif': 'Emergency alert — person detected',
  'stx.newDetectionNotif': 'New {cls} detection',
  'stx.safetyBody': 'Safety category. Search & Rescue routed. Immediate response required.',
  'stx.detectBody': '{pct}% confidence · {risk} risk · {dept}.',
  'stx.emergencyToast': 'EMERGENCY — person detected',
  'stx.priorityToast': 'New {risk}-priority alert',
  'stx.toastText': '{dept} · {pct}% conf · deadline {deadline}',
};

export const xHi: Record<string, string> = {
  'stx.loginRejected': 'लॉगिन अस्वीकृत',
  'stx.loginRejectedText': 'यह खाता {dept} से संबंधित है।',
  'stx.invalidCredentials': 'अमान्य क्रेडेंशियल',
  'stx.invalidCredentialsText': 'पासवर्ड पंजीकृत खाते से मेल नहीं खाता।',
  'stx.authSuccess': 'प्रमाणीकरण सफल',
  'stx.authSuccessText': 'सत्र स्थापित हुआ। वापसी पर स्वागत है, ऑपरेटर।',
  'stx.allFieldsRequired': 'सभी फ़ील्ड आवश्यक हैं।',
  'stx.invalidEmail': 'मान्य ईमेल पता दर्ज करें।',
  'stx.passwordTooShort': 'पासवर्ड में कम से कम 6 अक्षर होने चाहिए।',
  'stx.usernameTaken': 'यह उपयोगकर्ता नाम पहले से पंजीकृत है।',
  'stx.emailExists': 'इस ईमेल से एक खाता पहले से मौजूद है।',
  'stx.accountCreated': 'खाता बन गया',
  'stx.accountCreatedText': '{name} को {dept} में पंजीकृत किया गया।',
  'stx.sessionEnded': 'सत्र समाप्त',
  'stx.sessionEndedText': 'आपको संचालन पोर्टल से लॉग आउट कर दिया गया है।',
  'stx.marineLifeObserved': 'समुद्री जीवन देखा गया',
  'stx.marineLifeObservedBody': 'मंटा किरण का सिग्नल दर्ज किया गया। केवल निगरानी — कोई निष्कासन कार्रवाई नहीं।',
  'stx.marineObservation': 'समुद्री जीवन अवलोकन',
  'stx.marineObservationText': 'मंटा किरण को मॉनिटरिंग लेजर में दर्ज किया गया। कोई अलर्ट नहीं उठाया गया।',
  'stx.viewAlert': 'अलर्ट देखें',
  'stx.view': 'देखें',
  'stx.taskAssigned': 'कार्य सौंपा गया',
  'stx.taskAssignedNote': '{operator} को {target} सौंपा गया।',
  'stx.taskAssignedText': '{id} को {target} → {operator} को भेजा गया।',
  'stx.settingsSaved': 'सेटिंग्स सहेज ली गईं',
  'stx.settingsSavedText': 'कॉन्फ़िगरेशन डेमो स्थिति में लिखा गया और स्थानीय रूप से सहेजा गया।',
  'stx.settingsReset': 'सेटिंग्स रीसेट कर दी गईं',
  'stx.settingsResetText': 'कॉन्फ़िगरेशन डिफ़ॉल्ट पर बहाल कर दिया गया।',
  'stx.tlDetection': 'सोनार डिटेक्शन दर्ज किया गया',
  'stx.tlDetectionDesc': 'साइड-स्कैन फ्रेम पूर्ण रिज़ॉल्यूशन पर कैप्चर एवं संग्रहित किया गया।',
  'stx.tlAnalysis': 'समुद्री खुफिया विश्लेषण',
  'stx.tlAnalysisDesc': '{desc} विश्वास स्तर {pct}%।',
  'stx.tlRouted': 'अलर्ट भेजा गया',
  'stx.tlRoutedDesc': 'नियम के अनुसार {dept} को भेजा गया।',
  'stx.emergencyNotif': 'आपातकालीन अलर्ट — व्यक्ति का पता चला',
  'stx.newDetectionNotif': 'नई {cls} डिटेक्शन',
  'stx.safetyBody': 'सुरक्षा श्रेणी। खोज व बचाव को भेजा गया। तत्काल प्रतिक्रिया आवश्यक।',
  'stx.detectBody': '{pct}% विश्वास · {risk} जोखिम · {dept}।',
  'stx.emergencyToast': 'आपातकाल — व्यक्ति का पता चला',
  'stx.priorityToast': 'नया {risk}-जोखिम अलर्ट',
  'stx.toastText': '{dept} · {pct}% विश्वास · समय सीमा {deadline}',
};

export const xMr: Record<string, string> = {
  'stx.loginRejected': 'लॉगिन नामंजूर',
  'stx.loginRejectedText': 'हे खाते {dept} चे आहे.',
  'stx.invalidCredentials': 'अवैध क्रेडेंशियल',
  'stx.invalidCredentialsText': 'पासवर्ड नोंदणीकृत खात्याशी जुळत नाही.',
  'stx.authSuccess': 'प्रमाणीकरण यशस्वी',
  'stx.authSuccessText': 'सत्र सुरू झाले. परत स्वागत आहे, ऑपरेटर.',
  'stx.allFieldsRequired': 'सर्व फील्ड आवश्यक आहेत.',
  'stx.invalidEmail': 'वैध ईमेल पत्ता प्रविष्ट करा.',
  'stx.passwordTooShort': 'पासवर्ड किमान ६ वर्णांचा असावा.',
  'stx.usernameTaken': 'हे वापरकर्तानाव आधीच नोंदणीकृत आहे.',
  'stx.emailExists': 'या ईमेलवर आधीपासून खाते आहे.',
  'stx.accountCreated': 'खाते तयार झाले',
  'stx.accountCreatedText': '{name} यांची {dept} मध्ये नोंदणी झाली.',
  'stx.sessionEnded': 'सत्र संपले',
  'stx.sessionEndedText': 'तुम्हाला संचालन पोर्टलमधून लॉग आउट करण्यात आले आहे.',
  'stx.marineLifeObserved': 'सागरी जीवन दिसले',
  'stx.marineLifeObservedBody': 'मांटा किरणाची सिग्नल नोंद झाली. केवळ निरीक्षण — कोणतीही काढणी कारवाई नाही.',
  'stx.marineObservation': 'सागरी जीवन निरीक्षण',
  'stx.marineObservationText': 'मांटा किरण मॉनिटरिंग लेजरमध्ये नोंदवला गेला. कोणताही अलर्ट उठवला गेला नाही.',
  'stx.viewAlert': 'अलर्ट पहा',
  'stx.view': 'पहा',
  'stx.taskAssigned': 'कार्य नियुक्त केले',
  'stx.taskAssignedNote': '{operator} यांना {target} नियुक्त केले.',
  'stx.taskAssignedText': '{id} याला {target} → {operator} कडे वळवले.',
  'stx.settingsSaved': 'सेटिंग्ज जतन झाल्या',
  'stx.settingsSavedText': 'कॉन्फिगरेशन डेमो स्थितीत लिहिले गेले आणि स्थानिकरित्या जतन केले.',
  'stx.settingsReset': 'सेटिंग्ज रीसेट झाल्या',
  'stx.settingsResetText': 'कॉन्फिगरेशन डीफॉल्टवर पुनर्संचयित केले.',
  'stx.tlDetection': 'सोनार डिटेक्शन नोंदवले',
  'stx.tlDetectionDesc': 'साइड-स्कॅन फ्रेम पूर्ण रिझोल्यूशनवर टिपून संग्रहित केला.',
  'stx.tlAnalysis': 'सागरी गुप्तचर विश्लेषण',
  'stx.tlAnalysisDesc': '{desc} आत्मविश्वास {pct}%.',
  'stx.tlRouted': 'अलर्ट वळवला',
  'stx.tlRoutedDesc': 'नियमानुसार {dept} कडे वळवला.',
  'stx.emergencyNotif': 'आपत्कालीन अलर्ट — व्यक्ती आढळली',
  'stx.newDetectionNotif': 'नवीन {cls} डिटेक्शन',
  'stx.safetyBody': 'सुरक्षा श्रेणी. शोध व बचाव कडे वळवले. तात्काळ प्रतिसाद आवश्यक.',
  'stx.detectBody': '{pct}% आत्मविश्वास · {risk} जोखीम · {dept}.',
  'stx.emergencyToast': 'आपत्काल — व्यक्ती आढळली',
  'stx.priorityToast': 'नवीन {risk}-जोखीम अलर्ट',
  'stx.toastText': '{dept} · {pct}% विश्वास · मुदत {deadline}',
};