export const xEn: Record<string, string> = {
  'w.kt': "region meteorology",
  'w.loading': "Loading weather outlook…",
  'w.fetching': "Fetching marine forecast for this location.",
  'w.unavailable': "Weather unavailable",
  'w.offline': "OFFLINE",
  'w.errorBody': "Marine forecast could not be reached — no network or service blocked. Visit-window guidance is unavailable for this location.",
  'w.dayOutlook': "7-DAY OUTLOOK",
  'w.seaState': "Sea state",
  'w.wind': "Wind",
  'w.sky': "Sky",
  'w.air': "Air",
  'w.seaCalm': "CALM",
  'w.seaModerate': "MODERATE",
  'w.seaRough': "ROUGH",
  'w.seaVeryRough': "VERY ROUGH",
  'w.windLight': "Light",
  'w.windGentle': "Gentle",
  'w.windModerate': "Moderate",
  'w.windStrong': "Strong",
  'w.windGale': "Gale",
  'w.skyClear': "Clear",
  'w.skyMostlyClear': "Mostly clear",
  'w.skyPartlyCloudy': "Partly cloudy",
  'w.skyOvercast': "Overcast",
  'w.skyFog': "Fog",
  'w.skyDrizzle': "Drizzle",
  'w.skyRain': "Rain",
  'w.skyFreezingRain': "Freezing rain",
  'w.skySnow': "Snow",
  'w.skyRainShowers': "Rain showers",
  'w.skySnowShowers': "Snow showers",
  'w.skyThunder': "Thunderstorms",
  'w.period': "Period {v} s",
  'w.wavesFrom': "Waves from {dir}",
  'w.dayWaves': "waves {v}",
  'w.dayRain': "rain {v}%",
  'w.good': "GOOD",
  'w.caution': "CAUTION",
  'w.poor': "POOR",
  'w.hoursToDeadline': "{h} h to deadline",
  'w.verdict.onTrack': "ON TRACK",
  'w.verdict.tight': "TIGHT",
  'w.verdict.atRisk': "AT RISK",
  'w.verdict.missed': "MISSED",
  'w.verdict.outlook': "OUTLOOK",
  'w.taskHeading': "When to complete this task",
  'w.h.missed': "Response window has passed ({deadline})",
  'w.riskCriticalEsc': "critical — escalate now",
  'w.riskEscOverdue': "escalated / overdue",
  'w.d.missed': "Treat as {risk}: dispatch only in the next calm gap (waves below 1.5 m, wind under 30 km/h), complete the run, then close the case.",
  'w.h.outlook': "Deadline {deadline} is beyond the 7-day outlook",
  'w.tomorrow': "tomorrow",
  'w.d.outlook': "Re-check the forecast after {date}. Execute only once waves stay below 1.5 m for 24 h and wind remains under 30 km/h.",
  'w.h.atRisk': "Sea state blocks dispatch before {deadline}",
  'w.d.atRisk': "Every day before the deadline is rated {level} (waves ≥ 2.5 m / strong wind / heavy rain). Do not sail — hold or escalate the case, and keep monitoring until conditions ease.",
  'w.h.onTrack': "Complete during {window}",
  'w.d.onTrack': "{count}-day calm window opens before the {deadline} deadline (waves ≤ 1.2 m, wind ≤ 26 km/h, rain ≤ 50%). Book the day-run for {start} — starting earlier in the window leaves buffer if conditions shift. {hours} h remain.",
  'w.h.tight': "Tight — best attempt {day} at first light",
  'w.d.tight': "No fully-good day before {deadline}. Least-rough pre-deadline day is {day} (waves {wave} m, wind {wind} km/h, rain {rain}%). Sail at dawn, verify on departure, and keep manual verification on return.",
  'w.recWindow': "Recommended visit window",
  'w.visitGuidance': "Visit guidance",
  'w.whenToVisit': "WHEN TO VISIT",
  'w.day': "day",
  'w.days': "days",
  'w.safeSeaDays': "{n} {unit} of safe sea state",
  'w.bestCond': "Best conditions for the recovery / survey run — waves ≤ 1.2 m, wind ≤ 26 km/h, rain chance ≤ 50%.",
  'w.avoidDay': "Avoid {day}: {wave} waves with {rain}% rain.",
  'w.planDaylight': "Plan daylight operations; calmest sea state is usually before 11:00 local.",
  'w.noSafeWindow': "No safe window inside this 7-day outlook. Monitor the forecast daily — rough season now, window typically reopens when wave height drops below 1.2 m for 24 h. Re-check before dispatch.",
};

export const xHi: Record<string, string> = {
  'w.kt': "क्षेत्रीय मौसम विज्ञान",
  'w.loading': "मौसम पूर्वानुमान लोड हो रहा है…",
  'w.fetching': "इस स्थान के लिए समुद्री पूर्वानुमान प्राप्त किया जा रहा है।",
  'w.unavailable': "मौसम उपलब्ध नहीं है",
  'w.offline': "ऑफ़लाइन",
  'w.errorBody': "समुद्री पूर्वानुमान प्राप्त नहीं हो सका — नेटवर्क उपलब्ध नहीं है या सेवा अवरुद्ध है। इस स्थान के लिए भ्रमण-अवधि सलाह उपलब्ध नहीं है।",
  'w.dayOutlook': "7-दिवसीय पूर्वानुमान",
  'w.seaState': "समुद्र की स्थिति",
  'w.wind': "हवा",
  'w.sky': "आकाश",
  'w.air': "वायु",
  'w.seaCalm': "शांत",
  'w.seaModerate': "मध्यम",
  'w.seaRough': "अशांत",
  'w.seaVeryRough': "अत्यधिक अशांत",
  'w.windLight': "हल्की",
  'w.windGentle': "मंद",
  'w.windModerate': "मध्यम",
  'w.windStrong': "तेज़",
  'w.windGale': "झंझा",
  'w.skyClear': "साफ़",
  'w.skyMostlyClear': "अधिकतर साफ़",
  'w.skyPartlyCloudy': "आंशिक बादल",
  'w.skyOvercast': "घटाटोप",
  'w.skyFog': "कोहरा",
  'w.skyDrizzle': "बूंदाबांदी",
  'w.skyRain': "बारिश",
  'w.skyFreezingRain': "जमा देने वाली बारिश",
  'w.skySnow': "बर्फ़बारी",
  'w.skyRainShowers': "बौछारें",
  'w.skySnowShowers': "बर्फ़ की बौछारें",
  'w.skyThunder': "आंधी-तूफान",
  'w.period': "अवधि {v} s",
  'w.wavesFrom': "लहरें {dir} से",
  'w.dayWaves': "लहरें {v}",
  'w.dayRain': "वर्षा {v}%",
  'w.good': "अनुकूल",
  'w.caution': "सावधान",
  'w.poor': "खराब",
  'w.hoursToDeadline': "समय सीमा तक {h} घंटे",
  'w.verdict.onTrack': "सही रास्ते पर",
  'w.verdict.tight': "कठिन",
  'w.verdict.atRisk': "जोखिम पर",
  'w.verdict.missed': "छूट गया",
  'w.verdict.outlook': "पूर्वानुमान",
  'w.taskHeading': "यह कार्य कब पूरा करें",
  'w.h.missed': "प्रतिक्रिया अवधि बीत चुकी है ({deadline})",
  'w.riskCriticalEsc': "गंभीर — तुरंत स्तर बढ़ाएँ",
  'w.riskEscOverdue': "स्तर बढ़ाया गया / विलंबित",
  'w.d.missed': "{risk} मानें: केवल अगले शांत अंतराल में टीम भेजें (लहरें 1.5 m से कम, हवा 30 km/h से कम), कार्य पूरा करें, फिर मामला बंद करें।",
  'w.h.outlook': "समय सीमा {deadline} 7-दिवसीय पूर्वानुमान से आगे है",
  'w.tomorrow': "कल",
  'w.d.outlook': "{date} के बाद पूर्वानुमान पुनः जाँचें। केवल तभी कार्य करें जब लहरें 24 h तक 1.5 m से नीचे रहें और हवा 30 km/h से कम रहे।",
  'w.h.atRisk': "समुद्र की स्थिति {deadline} से पहले कार्यवाही रोक रही है",
  'w.d.atRisk': "समय सीमा से पहले का हर दिन {level} दर्जे का है (लहरें ≥ 2.5 m / तेज़ हवा / भारी बारिश)। नाव न भेजें — मामला रोकें या स्तर बढ़ाएँ और स्थितियाँ सुधरने तक निगरानी जारी रखें।",
  'w.h.onTrack': "{window} के दौरान पूरा करें",
  'w.d.onTrack': "{deadline} समय सीमा से पहले {count}-दिवसीय शांत अंतराल खुलता है (लहरें ≤ 1.2 m, हवा ≤ 26 km/h, वर्षा ≤ 50%)। {start} के दिन की कार्यवाही तय करें — अंतराल में जल्दी शुरू करने से स्थिति बदलने पर बफर रहेगा। {hours} घंटे शेष हैं।",
  'w.h.tight': "कठिन — {day} भोर में सर्वोत्तम प्रयास",
  'w.d.tight': "{deadline} से पहले कोई भी पूर्णतः अनुकूल दिन नहीं है। समय सीमा से पहले सबसे कम अशांत दिन {day} है (लहरें {wave} m, हवा {wind} km/h, वर्षा {rain}%)। भोर में प्रस्थान करें, रवानगी से पहले सत्यापन करें और लौटते समय मैन्युअल सत्यापन करें।",
  'w.recWindow': "अनुशंसित भ्रमण अवधि",
  'w.visitGuidance': "भ्रमण सलाह",
  'w.whenToVisit': "कब भ्रमण करें",
  'w.day': "दिन",
  'w.days': "दिन",
  'w.safeSeaDays': "{n} {unit} सुरक्षित समुद्री स्थिति",
  'w.bestCond': "बचाव / सर्वेक्षण अभियान के लिए सर्वोत्तम स्थितियाँ — लहरें ≤ 1.2 m, हवा ≤ 26 km/h, वर्षा संभावना ≤ 50%।",
  'w.avoidDay': "{day} को टालें: {wave} की लहरें, {rain}% वर्षा।",
  'w.planDaylight': "दिन के उजाले में कार्य की योजना बनाएँ; समुद्र आमतौर पर स्थानीय समय 11:00 से पहले सबसे शांत रहता है।",
  'w.noSafeWindow': "इस 7-दिवसीय पूर्वानुमान में कोई सुरक्षित अंतराल नहीं है। पूर्वानुमान की रोज़ निगरानी करें — अभी अशांत मौसम है, अंतराल आमतौर पर तब दोबारा खुलता है जब लहर की ऊंचाई 24 h तक 1.2 m से नीचे रहती है। कार्यवाही से पहले पुनः जाँच करें।",
};

export const xMr: Record<string, string> = {
  'w.kt': "क्षेत्रीय हवामानशास्त्र",
  'w.loading': "हवामान अंदाज लोड होत आहे…",
  'w.fetching': "या स्थानासाठी सागरी अंदाज मिळवला जात आहे.",
  'w.unavailable': "हवामान उपलब्ध नाही",
  'w.offline': "ऑफलाइन",
  'w.errorBody': "सागरी अंदाज मिळू शकला नाही — नेटवर्क उपलब्ध नाही किंवा सेवा अवरुद्ध आहे. या स्थानासाठी भेट-कालावधी मार्गदर्शन उपलब्ध नाही.",
  'w.dayOutlook': "7-दिवसीय अंदाज",
  'w.seaState': "समुद्राची स्थिती",
  'w.wind': "वारा",
  'w.sky': "आकाश",
  'w.air': "हवा",
  'w.seaCalm': "शांत",
  'w.seaModerate': "मध्यम",
  'w.seaRough': "अशांत",
  'w.seaVeryRough': "अत्यंत अशांत",
  'w.windLight': "हलकी",
  'w.windGentle': "मंद",
  'w.windModerate': "मध्यम",
  'w.windStrong': "जोरदार",
  'w.windGale': "वादळी",
  'w.skyClear': "स्वच्छ",
  'w.skyMostlyClear': "बहुतांश स्वच्छ",
  'w.skyPartlyCloudy': "अंशतः ढगाळ",
  'w.skyOvercast': "ढगाळ",
  'w.skyFog': "धुके",
  'w.skyDrizzle': "रिमझिम",
  'w.skyRain': "पाऊस",
  'w.skyFreezingRain': "गोठणारा पाऊस",
  'w.skySnow': "हिमवृष्टी",
  'w.skyRainShowers': "पावसाच्या सरी",
  'w.skySnowShowers': "हिमवृष्टीच्या सरी",
  'w.skyThunder': "गडगडाटी वादळ",
  'w.period': "कालावधी {v} s",
  'w.wavesFrom': "लाटा {dir} कडून",
  'w.dayWaves': "लाटा {v}",
  'w.dayRain': "पाऊस {v}%",
  'w.good': "चांगला",
  'w.caution': "सावधान",
  'w.poor': "खराब",
  'w.hoursToDeadline': "मुदतीपर्यंत {h} तास",
  'w.verdict.onTrack': "मार्गावर",
  'w.verdict.tight': "कठीण",
  'w.verdict.atRisk': "धोक्यात",
  'w.verdict.missed': "चुकले",
  'w.verdict.outlook': "अंदाज",
  'w.taskHeading': "हे काम कधी पूर्ण करावे",
  'w.h.missed': "प्रतिसाद कालावधी संपली आहे ({deadline})",
  'w.riskCriticalEsc': "गंभीर — त्वरित वाढवा",
  'w.riskEscOverdue': "वाढविले / मुदत ओलांडली",
  'w.d.missed': "{risk} माना: फक्त पुढील शांत अंतरातच कार्यवाही करा (लाटा 1.5 m पेक्षा कमी, वारा 30 km/h पेक्षा कमी), काम पूर्ण करा, मग प्रकरण बंद करा.",
  'w.h.outlook': "मुदत {deadline} ही 7-दिवसीय अंदाजाच्या पलीकडे आहे",
  'w.tomorrow': "उद्या",
  'w.d.outlook': "{date} नंतर अंदाज पुन्हा तपासा. लाटा 24 h पर्यंत 1.5 m पेक्षा खाली राहतील आणि वारा 30 km/h पेक्षा कमी राहील तेव्हाच कार्य करा.",
  'w.h.atRisk': "समुद्राची स्थिती {deadline} पूर्वी कार्यवाही अडवत आहे",
  'w.d.atRisk': "मुदतीपूर्वीचा प्रत्येक दिवस {level} दर्जाचा आहे (लाटा ≥ 2.5 m / जोरदार वारा / मुसळधार पाऊस). जहाज पाठवू नका — प्रकरण थांबवा किंवा वाढवा आणि परिस्थिती सुधारेपर्यंत निरीक्षण सुरू ठेवा.",
  'w.h.onTrack': "{window} या काळात पूर्ण करा",
  'w.d.onTrack': "{deadline} मुदतीपूर्वी {count}-दिवसीय शांत कालावधी मिळतो (लाटा ≤ 1.2 m, वारा ≤ 26 km/h, पाऊस ≤ 50%)। {start} रोजी कार्याचे नियोजन करा — कालावधीत लवकर सुरुवात केल्यास परिस्थिती बदलल्यास जागा राहते. {hours} तास शिल्लक आहेत.",
  'w.h.tight': "कठीण — {day} पहाटे सर्वोत्तम प्रयत्न",
  'w.d.tight': "{deadline} पूर्वी एकही पूर्णतः योग्य दिवस नाही. मुदतीपूर्वी सर्वात कमी अशांत दिवस {day} आहे (लाटा {wave} m, वारा {wind} km/h, पाऊस {rain}%)। पहाटे निघा, सुटण्यापूर्वी पडताळणी करा आणि परतताना मॅन्युअल पडताळणी करा.",
  'w.recWindow': "शिफारस केलेला भेट कालावधी",
  'w.visitGuidance': "भेट मार्गदर्शन",
  'w.whenToVisit': "कधी भेट द्यावी",
  'w.day': "दिवस",
  'w.days': "दिवस",
  'w.safeSeaDays': "{n} {unit} सुरक्षित समुद्री स्थिती",
  'w.bestCond': "बचाव / सर्वेक्षण मोहिमेसाठी सर्वोत्तम परिस्थिती — लाटा ≤ 1.2 m, वारा ≤ 26 km/h, पावसाची शक्यता ≤ 50%.",
  'w.avoidDay': "{day} टाळा: {wave} च्या लाटा, {rain}% पाऊस.",
  'w.planDaylight': "दिवसाच्या प्रकाशात कार्याचे नियोजन करा; सहसा स्थानिक वेळेनुसार 11:00 पूर्वी समुद्र सर्वात शांत असतो.",
  'w.noSafeWindow': "या 7-दिवसीय अंदाजात एकही सुरक्षित कालावधी नाही. अंदाजावर दररोज लक्ष ठेवा — सध्या अशांत हंगाम आहे, सहसा लाटांची उंची 24 h पर्यंत 1.2 m पेक्षा खाली राहिल्यावर कालावधी पुन्हा उपलब्ध होतो. कार्यवाहीपूर्वी पुन्हा तपासा.",
};