"""align database indexes

Revision ID: 8003edab95eb
Revises: 0001_initial
Create Date: 2026-09-28 01:32:34.702977
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8003edab95eb'
down_revision: Union[str, Sequence[str], None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('alerts_alert_id_key'), 'alerts', type_='unique')
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_detection_id'), 'alerts', ['detection_id'], unique=False)
    op.drop_constraint(op.f('auth_sessions_token_hash_key'), 'auth_sessions', type_='unique')
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=True)
    op.drop_constraint(op.f('detections_detection_id_key'), 'detections', type_='unique')
    op.create_index('ix_detections_department_created_at', 'detections', ['department', 'created_at'], unique=False)
    op.create_index(op.f('ix_detections_detection_id'), 'detections', ['detection_id'], unique=True)
    op.create_unique_constraint('uq_detections_detection_id', 'detections', ['detection_id'])
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_detections_detection_id', 'detections', type_='unique')
    op.drop_index(op.f('ix_detections_detection_id'), table_name='detections')
    op.drop_index('ix_detections_department_created_at', table_name='detections')
    op.create_unique_constraint(op.f('detections_detection_id_key'), 'detections', ['detection_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_auth_sessions_token_hash'), table_name='auth_sessions')
    op.create_index(op.f('ix_auth_sessions_token_hash'), 'auth_sessions', ['token_hash'], unique=False)
    op.create_unique_constraint(op.f('auth_sessions_token_hash_key'), 'auth_sessions', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_alerts_detection_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.create_unique_constraint(op.f('alerts_alert_id_key'), 'alerts', ['alert_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
